### ISSUE TITLE
config file can't be optional

### ISSUE THREAD

**Issue by joshuarubin** [spf13/viper#1]
It would be more useful if ReadInConfig could return an error instead of causing the process to Exit if the config can't be found. This would enable the case where the whole file can be optional and the values read from defaults.

``` go
func ReadInConfig() {
    jww.INFO.Println("Attempting to read in config file")

    if !stringInSlice(getConfigType(), SupportedExts) {
        jww.ERROR.Fatalf("Unsupported Config Type %q", getConfigType())
    }

    ...
```

**Comment by stevenroose** [comment]
So it is really not possible to have Viper not error when the config file does not exist?

**Comment by balta2ar** [comment]
> So it is really not possible to have Viper not error when the config file does not exist?

I have the same question... @spf13 @joshuarubin?

**Comment by sagikazarmark** [comment]
Leaving the solution here for future reference:

```go
	err := viper.ReadInConfig()
	if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
		panic(err)
	}
```

Basically you just have to check the error and ignore it if it is a config not found error.

**Comment by alex-shpak** [comment]
If somebody interested, alternative solution
```
if err := config.ReadConfig(strings.NewReader("")); err != nil {
	log.Fatal(err)
}
```

**Comment by sagikazarmark** [comment]
Hm, calling `ReadConfig` is totally optional, you only need it if you want to read a config file, so I'm failing to see how this helps.

**Comment by alex-shpak** [comment]
Oh, yeah, you are right.
Scratch that.
