### ISSUE TITLE
PFlag in PersistentFlags() being ignored

### ISSUE THREAD

**Issue by BrianHicks** [spf13/viper#100]
I'm having a bit of trouble between viper and cobra... I'm defining a "log-level" variable as a persistent flag on the root command, and despite binding it in viper it's being ignored. Here's my code snippet:

```
// logging
CmdTellusRoot.PersistentFlags().String("log-level", "info", "verbosity level for logs")
viper.BindPFlag("log-level", CmdTellusRoot.PersistentFlags().Lookup("log-level"))
viper.BindEnv("log-level")
```

That's the last thing in `init`, and I'm not setting things manually anywhere. The environment variable isn't set either. To be specific, when I call `viper.GetString("log-level")` I always get "info", even if I'm passing "debug" in the flags.

**Comment by BrianHicks** [comment]
@spf13 any ideas what could be causing this?

**Comment by spf13** [comment]
Is this code available publicly? 

Viper has some debugging functions. Does Debug() help?
https://github.com/spf13/viper/blob/master/viper.go#L970

**Comment by BrianHicks** [comment]
It's not, but here's a minimal program demonstrating the problem (or my understanding of it?): https://gist.github.com/b9ee755f37a88abdca80

And the corresponding output when called with `go run main.go --log-level=debug --log-format=json`:

```
Aliases:
map[string]string{}
Override:
map[string]interface {}{
}
PFlags
map[string]*pflag.Flag{
    "log-level": &pflag.Flag{
        Name:                "log-level",
        Shorthand:           "",
        Usage:               "one of debug, info, warn, error, or fatal",
        Value:               &"info",
        DefValue:            "info",
        Changed:             false,
        NoOptDefVal:         "",
        Deprecated:          "",
        ShorthandDeprecated: "",
        Annotations:         {},
    },
    "log-format": &pflag.Flag{
        Name:                "log-format",
        Shorthand:           "",
        Usage:               "specify output (text or json)",
        Value:               &"text",
        DefValue:            "text",
        Changed:             false,
        NoOptDefVal:         "",
        Deprecated:          "",
        ShorthandDeprecated: "",
        Annotations:         {},
    },
}
Env:
map[string]string{}
Key/Value Store:
map[string]interface {}{
}
Config:
map[string]interface {}{
}
Defaults:
map[string]interface {}{
    "log-level":  "info",
    "log-format": "text",
}
INFO[0000] loading files
```

**Comment by BrianHicks** [comment]
I found the error, thanks to J Walter Weatherman teaching me a lesson. In my code sample above, the flags aren't being parsed before I'm accessing them with viper. To fix this, I moved the logging initialization to a `PersistentPreRun` command on the root.
