### ISSUE TITLE
array indices by using numbers

### ISSUE THREAD

**Issue by bluedogtwo** [spf13/viper#1003]
I read this
"Viper can access array indices by using numbers in the path. For example:"

toml file
hosts = ["alpha","omega"]

fmt.Println(viper.GetStringSlice("hosts")[0])   // works
fmt.Println(viper.Get("hosts.0"))  // doesn't work, shouldn't this work?

**Comment by ctfrancia** [comment]
In short, no, dot notation is used for objects while brackets are used for slice indices.

**Comment by sagikazarmark** [comment]
I think #861 implements this feature.
