### ISSUE TITLE
SafeWriteConfig() failing with file not found error

### ISSUE THREAD

**Issue by carvalhais** [spf13/viper#1004]
Hi, I'm trying to use SafeWriteConfig() to create a new config file with the following snippet of code:
```
// if a config file is found, read it in
if err := viper.ReadInConfig(); err == nil {
    fmt.Println("Using config file:", viper.ConfigFileUsed())
    // else, create a new one
} else {
    if err := viper.SafeWriteConfig(); err != nil {
        fmt.Println(err)
    }
}
```

However when I run the code, the call fails with the following message:
```
open /home/carvalhais/.ghi/conf.toml: no such file or directory
```

From my understanding, shouldn't SafeWriteConfig() create a new file if none exists?

**Comment by priyanka-tw** [comment]
@carvalhais Could you state the config type, name, and path stated before this code snippet?

**Comment by ctfrancia** [comment]
@carvalhais silly question, but, have you created the file before trying to read/write? is there any error when trying to write to it? Maybe control flow issue? need more information.

**Comment by carvalhais** [comment]
Hi gentlemen,

First of all, thanks for you kind input to this matter and time dedicated to my issue.

Regarding the issue itself, since I opened it, I managed to get SafeWriteConfig() working with an intermediate solution. I noticed I'm able to write to the config file if I omit the intermediary ".ghi" directory in the following path (which didn't exist at the time of writing, I was expecting SafeWriteConfig() to create it):

`/home/carvalhais/.ghi/conf.toml`

If I try to use my home directory directly, I'm able to successfully create the file. I was trying to create an intermediary directory so I would be able to hold more assets in it, but I change my strategy for the moment.

@priyanka-tw I was previously doing something in the lines of the following:
```
if cfgFile != "" {
	// use config file from the flag
	viper.SetConfigFile(cfgFile)
} else {
	// find home directory
	home, err := homedir.Dir()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// search for config files in user's home dir and also current dir
	viper.AddConfigPath(home + "/.ghi")
	viper.AddConfigPath(".")
	viper.SetConfigName("conf")
	viper.SetConfigType("toml")
}
```

@ctfrancia I didn't try to create the file beforehand since I was trying to implement a behaviour in which my application would first check for a config file, and if not present it would create it with the current configuration (preserving any default values for flags thatd idn't get overrided). I haven't noticed any particular errors related to not being able to write the file. I'm still inexperienced with Go, but from my code above I'm not expecting it to be related to control flow issues.

**Comment by ctfrancia** [comment]
If you are looking to see if the directory already exists I think a better approach would be:
```go
	configDir := filepath.Join(usr.HomeDir, ".config", "godot")

	if configExists(configDir) {
		fmt.Println("file exists")
                // create path here
		return
	}

func configExists(p string) bool {
	if _, err := os.Stat(p); !os.IsNotExist(err) {
		// file exists
		return true
	}
	return false
}
```

there are a couple reasons for this. One: it's easier to test, and two it makes your code easier to understand (imo)

**Comment by carvalhais** [comment]
@ctfrancia I appreciate your advice, and I'll follow it for the time being. I'll be closing the issue, since I now understand this is not a bug in SafeWriteConfig().

If I may, I would suggest documenting this specific behaviour, at least to me it seems reasonable to assume the directory specified in the config path is the one the user wants the file to be in, so it could be created if it didn't exist beforehand. At least that's what happen for the config file itself, so it would be consistent with that.

I can help with documenting this behaviour if it is desirable.

**Comment by KEINOS** [comment]
+1 to clarify the doc that `SafeWriteConfig()` and `SafeWriteConfigAs()` will only create a file **if the directory path already exists**.

---

> From my understanding, shouldn't `SafeWriteConfig()` create a new file if none exists?

By reading the below sentence in [README.md](https://github.com/spf13/viper/blob/0594522560e470473af1d9a417c0b0f69e5fe368/README.md#writing-config-files) and the returned error, I agree with @carvalhais' doubt.

> - SafeWriteConfig - writes the current viper configuration to the predefined path. Errors if no predefined path. Will not overwrite the current config file, if it exists.

```shellsession
open /tmp/TestInit1883891090/001/.config/myconfig.json: no such file or directory:
```

The above error was targeting the right path as I expected.

So I assumed that the predefined path (`Viper.SetConfigName` and `Viper.AddConfigPath` setting) were ok. Then, since the file **doesn't exist**, I assumed it will create the conf file. But it returns an inconsistent error.

After a fuss, I realized that actually, the error was telling me that `/tmp/TestInit1883891090/001/.config` directory didn't exist.

According to the `README.md`, I felt the user will assume that it will `os.MkdirAll()` the directory path then create the file.

So, I felt it would be nice to have in the doc something like:

```diff
- - SafeWriteConfig - writes the current viper configuration to the predefined path. Errors if
-                     no predefined path. Will not overwrite the current config file, if it exists.
+ - SafeWriteConfig - writes the current viper configuration to the predefined path. Errors if
+                     no predefined path or no target directory exists. Will not overwrite the 
+                     current config file, if the file exists.
```
