### ISSUE TITLE
Not able to preserve TOML comments

### ISSUE THREAD

**Issue by kpvenugo** [spf13/viper#1006]
Hi folks,
I am trying to modify a certain field in a TOML file, by reading and writing as follows

```
viper.SetConfigName("config")
viper.AddConfigPath(".") 
err := viper.ReadInConfig()

if err != nil { // Handle errors reading the config file
  panic(fmt.Errorf("Fatal error config file: %s", err))
}

viper.Set("database.user", "newuser"))
viper.Set("owner.name", "John"))

viper.WriteConfig()
```

But this removes all the comments from the TOML files. 
Probably this might be because the comments were not read to the viper object. 
Could you let me know if this is right way to retain the comments?

Advance Thanks

**Comment by sagikazarmark** [comment]
Hi @kpvenugo !

That's indeed the case: Viper does not (and cannot) read comments from your file. That's unfortunately the expected behavior.

If you need to keep comments in the file, don't use Viper for writing configuration.
