### ISSUE TITLE
Nacos support?

### ISSUE THREAD

**Issue by yuzhichang** [spf13/viper#1008]
[Nacos](https://github.com/alibaba/nacos) provides dynamic service discovery and configuration and service management. 
Would viper add Nacos support?

**Comment by sagikazarmark** [comment]
Viper 2 is going to remove support for remote config sources from the core and will provide an API for registering config sources.

As for Viper 1, I suggest providing a package like this: https://github.com/sagikazarmark/viperx

We'd like to avoid increasing the number of dependencies in the core.
