### ISSUE TITLE
Flags defaults override values set by file

### ISSUE THREAD

**Issue by aaronbuchwald** [spf13/viper#1010]
I am running into a problem where the defaults set by go flags are overriding the values set in a json config file. The documentation suggests that this is possible and even the intended use case, but there doesn't seem to be any documentation for reading in both flags and config files.

How would one read in both a config file as well as the values from a set of flags using viper where the default values set by the flags themselves will not override the values set in the config file?

Could an example be added to the documentation?

**Comment by sagikazarmark** [comment]
Can you please provide a code sample (and config file) reproducing your issue? In theory, flag defaults should not override values from files.

**Comment by aaronbuchwald** [comment]
This currently seems to be the case on the simplest example that I try, so any example should do. Could you point to any documentation or examples where it works as intended for me to try?

**Comment by sagikazarmark** [comment]
Here is a (rather complicated) example: https://github.com/sagikazarmark/modern-go-application

As far as I can tell, this works as expected, so any example reproducing the issue should suffice.

**Comment by aaronbuchwald** [comment]
Seems like this was related to the order in which bind flags, etc. was called.

**Comment by fwang2002** [comment]
the problem still exists in v1.10.1
