### ISSUE TITLE
Feature Request: Case Sensitive Keys

### ISSUE THREAD

**Issue by aaronbuchwald** [spf13/viper#1013]
Case sensitive keys are useful in many contexts, but they are not currently possible using viper.

**Comment by aaronbuchwald** [comment]
Actually, even in the case where I call Get on an individual key which maps to a JSON object, it still makes the keys of that JSON object lower case as well.

```
{"key": {"CaseSensitive": {"key":"value"}}}
```

Is there any way to get the value of the "CaseSensitive" key in this example using viper?

**Comment by yongjiapro** [comment]
See [https://github.com/spf13/viper/pull/635/commits/2cb5cbf43cc6d8b777a6f1baae164e3853c8430d](https://github.com/spf13/viper/pull/635/commits/2cb5cbf43cc6d8b777a6f1baae164e3853c8430d)

**Comment by sagikazarmark** [comment]
Duplicate of #1014

**Comment by dreamlu** [comment]
https://github.com/spf13/viper/commit/2cb5cbf43cc6d8b777a6f1baae164e3853c8430d
why delete it? it's useful
