### ISSUE TITLE
Set don't work in toml

### ISSUE THREAD

**Issue by darlandieterich** [spf13/viper#1018]
When I call 'Set' this dont work, the file remains true value

My .toml
```
[cert]
enabled=true
```
My .go
`config.Set("cert.enabled", false)`

**Comment by FuzzyStatic** [comment]
> the file remains true value

Did you try to write to the file after the `Set`? `Set` only updates the file data in memory.

**Comment by darlandieterich** [comment]
No, only `Set`, I had imagined the `Set` automatically save in file. 
What function do I call to write to the file? have any example?

**Comment by FuzzyStatic** [comment]
> No, only `Set`, I had imagined the `Set` automatically save in file.
> What function do I call to write to the file? have any example?

https://pkg.go.dev/github.com/spf13/viper@v1.7.1#WriteConfig

**Comment by darlandieterich** [comment]
@FuzzyStatic why my existent configuration is overwrite?
e.g.:
```
[other]
oldparam="test"
```
and will be `Set`

```
config.SetConfigName("config")
config.SetConfigType("toml")
config.AddConfigPath(".")
config.Set("cert", map[string]bool{"enabled": false})
config.WriteConfig()
```

now
```
[cert]
enabled=false
```

how it should be:
```
[other]
oldparam="test"
[cert]
enabled=false
```

**Comment by FuzzyStatic** [comment]
You really need to read the the documentation. If you want the data from your config you have to read it in first. Once it's in memory you can add to it, update it, remove data from it, etc. Then you can write all your changes to the file.

**Comment by darlandieterich** [comment]
My problem is don't use the function `ReadInConfig` to move to memory.
