### ISSUE TITLE
EnvKeyReplacer replace "." with "_"

### ISSUE THREAD

**Issue by johnmillner** [spf13/viper#1029]
Hello, I'm a bit new to the viper library but loving the potential! 

currently I'm reading config from a yaml file, but I want the ability to override with envVars 
I have subobjects in my yaml, and i want to represent those as "_" for envVars

example 
```yaml
secure:
  key: "testKey"
```

```go
viper.getString("secure.key")
```

but I also want the ability to set an envVar at `PREFIX_SECURE_KEY`

how i've set up my viper is like so 

```go 
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath("config")
	viper.EnvKeyReplacer(strings.NewReplacer(".", "_"))
	viper.SetEnvPrefix("PREFIX")
	viper.AutomaticEnv()
	viper.WatchConfig()

	err := viper.ReadInConfig()

	if err != nil {
		log.Panicf("Fatal error config file: %s", err)
	}
```

however it doesn't find envVar `PREFIX_SECURE_KEY` though it does find `PREFIX_SECURE.KEY` 

am I missing something obvious?

**Comment by johnmillner** [comment]
just for completeness - i've tested the `strings.NewReplacer(".", "_")` 

when i submit 
```go
strings.NewReplacer(".", "_").replace("secure.key")
```
it does return `secure_key`

**Comment by sagikazarmark** [comment]
`strings.NewReplacer("_", ".")` is what you need. You want to transform `PREFIX_SECURE_KEY` to `secure.key`.

**Comment by johnmillner** [comment]
thanks for the response @sagikazarmark! 

running that I still receive the same issue where it doesn't find PREFIX_SECURE_KEY - but does still find PREFIX_SECURE.KEY

updated setup 
```go
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath("config")
	viper.EnvKeyReplacer(strings.NewReplacer("_", "."))
	viper.SetEnvPrefix("PREFIX")
	viper.AutomaticEnv()
	viper.WatchConfig()

	err := viper.ReadInConfig()

	if err != nil {
		log.Panicf("Fatal error config file: %s", err)
	}
```

is there an ordering of the commands that is mixed up? tried shifting things around but didn't notice a difference

testing out of curiosity:
it does look like it is not accidentally replacing the prefix delimiter too like PREFIX.SECURE.KEY
and also tested if removing the prefix worked, but that also does not (finds SECURE.KEY, but not SECURE_KEY)
tried seeing if i needed to escape either the underscore or period, or both in the replacer - but no change

I'm a little at a loss 
its not the end of the world if i have to include `.`'s in the envVar - but definitely a nice to have

**Comment by johnmillner** [comment]
to note - this is running in Windows 10, potentially this is some OS trickery happening that wouldn't in a *nix system.

**Comment by sagikazarmark** [comment]
`EnvKeyReplacer` needs to be passed to `viper.NewWithOptions`.

**Comment by kgalli** [comment]
Just if somebody ended up here like me via google search. The trick is to use 

`viper.SetEnvKeyReplacer(strings.NewReplacer("_", "."))` instead of `viper.EnvKeyReplacer(strings.NewReplacer("_", "."))`. As hopefully obvious now the `Set` is important :-) ...
