### ISSUE TITLE
go version 1.15.5 install viper error

### ISSUE THREAD

**Issue by dcriori** [spf13/viper#1030]
go: found github.com/spf13/viper in github.com/spf13/viper v1.7.1
go: github.com/spf13/viper@v1.7.1 requires
	github.com/grpc-ecosystem/grpc-gateway@v1.9.0/go.mod: verifying module: github.com/grpc-ecosystem/grpc-gateway@v1.9.0/go.mod: cannot authenticate record data in server response

**Comment by sagikazarmark** [comment]
This does not seem to be a Viper issue. Try cleaning your module cache, getting viper in a new gopath, check if you have a go proxy set up, etc. It looks like Go cannot fetch the checksum for the grpc-gateway from the sum db.
