### ISSUE TITLE
viper.Unmarshal returns struct with empty values

### ISSUE THREAD

**Issue by VikingPingvin** [spf13/viper#1042]
Using 1.7.1 latest viper version.

JSON config file
```json
{
    "agentConfig":{
        "server_ip": "127.0.0.1",
        "server_port": "27001",
        "send_concurrent": true,
        "log_path": "./log.txt"
    }    
}
```
```go
type agentCfg struct {
		server_ip       string `mapstructure:"server_ip"`
		server_port     string `mapstructure:"server_port"`
		send_concurrent bool   `mapstructure:"send_concurrent"`
		log_path        string `mapstructure:"log_path"`
	}
type agCfgStruct map[string]agentCfg
testCfg := &agCfgStruct{}

err := viper.UnmarshalExact(&testCfg)
```
`err` is nil, and when debugging the result values are zeroed:
```shell
-> testCfg
  <*vikingPingvin/locker/cmd.agCfgStruct·2>(0xc0000061e0)
     <vikingPingvin/locker/cmd.agCfgStruct·2> (length: 1)
        "agentconfig":<vikingPingvin/locker/cmd.agentCfg·1>
         server_ip:""
         server_port:""
         send_concurrent:false
         log_path:""
```

While debugging the issue I noticed the `func (v *Viper) AllSettings() map[string]interface{}` function in `viper.go`,
there the values are read correctly in line `deepestMap[lastKey] = value`,
but the `return m ` does not contain assigned values, just the initialized structures.

Any idea what I perhaps did wrong?
Thanks!

**Comment by sagikazarmark** [comment]
@VikingPingvin can you please provide a repl.it link reproducing the issue?

Here is an example you can start with: https://repl.it/@sagikazarmark/Viper-example#main.go

**Comment by VikingPingvin** [comment]
@sagikazarmark Here is the Repl: https://repl.it/@VikingPingvin/Viperunmarshallerror

For reference I'm using go 1.15.5, but the behavor is identical in Repl.

**Comment by sagikazarmark** [comment]
Well, I'm not 100% sure whether this should work or not, but the primary use case for `Unmarshal` is to unmarshal config onto structs. So I'd suggest rewriting it as

```go
type agCfgStruct {
    agentConfig agentCfg `mapstructure:"agentConfig"`
}
```


My guess is, mapstructure cannot determine a path to the agent config struct from `map[string]`, but I'd have to dig deeper to find an answer.

Anyway, my recommendation is to use structs on all levels.

**Comment by VikingPingvin** [comment]
Thanks for the reply!
I modified the example Repl code with your suggestion however it still give me zero values.

Am I completely misunderstanding something here?
I am using structs now, mimicking the nested structure of the JSON file.

**Comment by sagikazarmark** [comment]
Ah, sorry, fields must be exported. So it should be like:

```go
type agentCfg struct {
	Server_ip       string `mapstructure:"server_ip"`
	Server_port     string `mapstructure:"server_port"`
	Send_concurrent bool   `mapstructure:"send_concurrent"`
	Log_path        string `mapstructure:"log_path"`
}
type agCfgStruct struct {
	AgentConfig agentCfg `mapstructure:"agentConfig"`
}
```
