### ISSUE TITLE
Replace dashes/hyphens in flag names with underscores

### ISSUE THREAD

**Issue by megapctr** [spf13/viper#1044]
I found a solution, this issue is just for folks who may also be struggling with this. Feel free to close it, unless you think it's worth mentioning in the readme.

I wanted to keep my CLI flags in `kebab-case` and my config keys in `snake_case`. I've been searching for something like `EnvKeyReplacer` but for flags. Turns out `pflag.FlagSet` has a function for normalizing flag names.

This solved my issue:
```go
// bind cmd flags to viper, replacing dashes with underscores
f := cmd.Flags()
normalizeFunc := f.GetNormalizeFunc()
f.SetNormalizeFunc(func(fs *pflag.FlagSet, name string) pflag.NormalizedName {
    result := normalizeFunc(fs, name)
    name = strings.ReplaceAll(string(result), "-", "_")
    return pflag.NormalizedName(name)
 })
 viper.BindPFlags(f)
```

**Comment by sagikazarmark** [comment]
Thanks @megapctr !

I converted this issue into a discussion: https://github.com/spf13/viper/discussions/1054
