### ISSUE TITLE
it seems viper can not get the keys of a map  in toml file, but yaml file works

### ISSUE THREAD

**Issue by lxsnum1** [spf13/viper#1047]
viper.GetStringMap("addrs")  return an empty map

toml file like this:
[addrs]
addr1 = [
    "aaa",
    "bbb",
]

addr2 = [
    "ddd",
    "cccc",
]

**Comment by sagikazarmark** [comment]
Please provide a repl reproducing the issue. You can use this as an example: https://repl.it/@sagikazarmark/Viper-example#main.go
