### ISSUE TITLE
addConfigPath("$XDG_CONFIG_HOME") crashes

### ISSUE THREAD

**Issue by hgschmie** [spf13/viper#1048]
**Expected behavior (what you expected to happen)**:

read the environment variable $XDG_CONFIG_HOME and use its content as a config path.

**Actual behavior (what actually happened)**:

```
github.com/spf13/viper.absPathify(0x141ac48, 0x10, 0x141a947, 0xf)
	/Users/hschmiedehausen/go/src/github.com/spf13/viper/util.go:100 +0x494
github.com/spf13/viper.(*Viper).AddConfigPath(0xc0000c27e0, 0x141ac48, 0x10)
	/Users/hschmiedehausen/go/src/github.com/spf13/viper/viper.go:470 +0x65
github.com/spf13/viper.AddConfigPath(...)
	/Users/hschmiedehausen/go/src/github.com/spf13/viper/viper.go:467
```

**Repl.it link**:

**Code reproducing the issue**:

```go
viper.AddConfigPath("$XDG_CONFIG_HOME")
```

**Environment**:
- Viper version: HEAD
- Config source: file
- File format: TOML

**Anything else we should know?**:

The problem is straightforward: In util.go, line 99 there is an assumption that any environment variable is followed by additional path segments. The code does not assume that there may just be a "naked" variable. Therefore the `strings.Index(inPath, string(os.PathSeparator))` returns -1, which then causes the next line to crash.

**Comment by sagikazarmark** [comment]
Thanks for reporting! Yeah, that's a known issue. I'll try to come up with a fix.

**Comment by sagikazarmark** [comment]
@hgschmie I believe [1.7.1](https://github.com/spf13/viper/releases/tag/v1.7.1) contains a fix for this problem. Can you please double check if this issue still occurs with that version? Thanks!

**Comment by sagikazarmark** [comment]
I think this is fixed.
