### ISSUE TITLE
using more AddConfigPath,can not use structaccess the configuration file 

### ISSUE THREAD

**Issue by xian9Yu** [spf13/viper#1052]
使用多个AddConfigPath时不能使用struct访问配置文件

like this:

//viper
type Config struct {
	ListenOn struct {
		Host string
		Port string
	}
	SQL struct {
		Driver     string
		DataSource string
	}
	JWT struct {
		SecretKey string
		ExpireAt  int64
	}
}

func (c *Config) InitConfig(c1, c2, c3 string) *viper.Viper {
	v := viper.New()

	v.AddConfigPath(c1)
	v.AddConfigPath(c2)
	v.AddConfigPath(c3)
	v.SetConfigName("vconf")
	v.SetConfigType("yaml")

//main
	c1 := path[:index]         
	c2 := getCurrentDirectory() 
	c3 := "."                  
	c := cfg.InitConfig(c1, c2, c3)
	fmt.Println("SQL.DataSource", c.Get("SQL.DataSource")) //normal
	fmt.Println("Server.Host", c.Get("ListenOn.Host")) //normal
	fmt.Println("Server.Port", c.Get("ListenOn.Port")) //normal

	fmt.Println(cfg.SQL.DataSource)   //return nil
	fmt.Println(cfg.ListenOn.Host, cfg.ListenOn.Port)  //return nil

**Comment by sagikazarmark** [comment]
@xian9Yu please follow the issue template and provide a working example along with formatted code examples and a description of the issue. It's really hard to guess what your issue is. Thank you!

**Comment by sagikazarmark** [comment]
@xian9Yu please open a new issue with more details, following the issue template if this is still an issue for you.
