### ISSUE TITLE
Default value of a composed name field with mapstructure tag does not get set

### ISSUE THREAD

**Issue by WesleyBatista** [spf13/viper#1057]
**Expected behavior (what you expected to happen)**:
Setting a default value for a struct field with a tag like `mapstructure:"site_url"` should bring me that value after `v.Unmarshal(&config)`

**Actual behavior (what actually happened)**:
The default value for `Nested.SiteURL` is not set and instead I get an empty string after `v.Unmarshal(&config)`.

**Repl.it link**: https://repl.it/@WesleyBatista3/Viper-example#main.go

**Code reproducing the issue**:

```go
type Config struct {
  Nested struct {
    SiteURL string `mapstructure:"site_url"`
    RedisDB string `mapstructure:"redisdb"`
  }
}

// ...

        v.SetDefault("Nested.SiteURL", "WILL NOT PARSE")
	v.SetDefault("Nested.RedisDB", "THIS WORKS")

```

_output from repl.it:_
```
 ./main
Config struct: main.Config{Nested:struct { SiteUrl string "mapstructure:\"site_url\""; RedisDB string "mapstructure:\"redisdb\"" }{SiteUrl:"", RedisDB:"THIS WORKS"}}
All configuration: map[favorites:map[fruit:orange vegetable:tomato] hobby:traveling my-hobby:reading nested:map[redisdb:THIS WORKS siteurl:WILL NOT PARSE]]
```

**Environment**:
- Viper version: 1.7.1
- Config source: file
- File format: YAML

**Anything else we should know?**:

As it is shown on the example, the problem can be circumvented by removing the `_` between the words (`site_url` -> `siteurl`, as with _`redisdb`_). But this is sub-optimal since it becomes less readable on the config file side.

The bug seems to be related to the underlying library [@mitchellh/mapstructure](https://github.com/mitchellh/mapstructure/), but since I found the problem using this library I opened the issue here.

**Comment by sagikazarmark** [comment]
The problem is actually this line:

```go
v.SetDefault("Nested.SiteURL", "WILL NOT PARSE")
```

Under the hood, mapstructure matches Viper keys to the struct, not the other way around. So mapstructure will look fow a key named `site_url` while the key is `SiteURL` (or `siteurl` since it's case insensitive).

Setting the key to `Nested.Site_URL` works as expected.
```go
v.SetDefault("Nested.Site_URL", "WILL NOT PARSE")
```

**Comment by sagikazarmark** [comment]
_Hint: if you want to use nested structs without adding an additional level of config for them, you can. Check the docs for embedded struct usage._

**Comment by WesleyBatista** [comment]
Wow, that was fast! 🤩 Thanks a lot for the heads up!
