### ISSUE TITLE
Can't get values inside a for cycle using i variable

### ISSUE THREAD

**Issue by steph9009** [spf13/viper#1058]
**Expected behavior**:
Getting (and printing or anything else) value from a JSON, inside a for cycle, using "i" variable in the key string expression.

**Actual behavior**:
Gets nothing (and prints only new line). Instead, it works if i manually write the 10+ lines (without for cycle and i variable).

**Code reproducing the issue**:
With nested values (like: `"person0": {"name": "aaa"}`):
```	
for i := 0; i < 10; i++ {
		fmt.Println(viper.GetString("person"+string(i)+".name"))
	}
```
and doesn't work even without nested values (like: `"person0": "aaa"`)
```
for i := 0; i < 10; i++ {
		fmt.Println(viper.GetString("person"+string(i)))
	}
```
also tried (both for nested and not, here the "not" example):
```
for i := 0; i < 10; i++ {
		someone := "person"+string(i)
		fmt.Println(viper.GetString(someone))
	}
```
**Environment**:
- Viper version: 1.7.1
- Config source: file
- File format: JSON

**Comment by sagikazarmark** [comment]
@steph9009 please provide a repl link that reproduces the issue.

**Comment by sagikazarmark** [comment]
Never mind, I can already tell you what's wrong: https://play.golang.org/p/_-y4z6QGhcF

That's not the way to convert a number to string. Either use:

- `strconv.Itoa`
- `fmt.Sprintf`

And next time, please include a repl link, so someone who looks at your issue doesn't have to write code reproducing it from scratch. Thanks!
