### ISSUE TITLE
My opinion

### ISSUE THREAD

**Issue by yqcs** [spf13/viper#1059]
Why change capital letters to lowercase letters without permission? Comments are also automatically cleared. I think these should be set manually.

**Comment by sagikazarmark** [comment]
@yqcs case insensitivity is necessary for merging configuration from various sources (for example env vars are usually upper case). You can track #1014 for this issue.

As for comments: that's an unfortunate consequence of writing config. Actually, the config write feature is not supposed to be used for saving config state. It's useful for features like writing default config.

I'm closing the issue as it's not actually an enhancement or not new.
