### ISSUE TITLE
Improve variable expansion in AddConfigPath

### ISSUE THREAD

**Issue by sagikazarmark** [spf13/viper#1062]
**Is your feature request related to a problem? Please describe.**
Variable expansion used in `AddConfigPath` is a bit weird.

**Describe the solution you'd like to see**
Try to improve the variable expansion code. Eg. use `os.ExpandEnv`

**Comment by esammer** [comment]
Just bumped into this with an env var that didn't end in the path separator. I think @serazoli's PR fixes this, but for posterity, the following currently fails: `AddConfigPath("$SOMETHING")`. A temporary workaround is to append a trailing path separator: `AddConfigPath("$SOMETHING/")`.

**Comment by sagikazarmark** [comment]
@esammer for the record, the provided fix will continue failing if the env var value is empty, hence you might still need the trailing separator.
