### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by dpanic** [spf13/viper#1071]
**Expected behavior (what you expected to happen)**:
Hi expected is to have working build.
`GOOS=js GOARCH=wasm go build -o contact.wasm`

**Actual behavior (what actually happened)**:
```
# github.com/spf13/viper
../../../../go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:344:19: undefined: fsnotify.NewWatcher
../../../../go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:366:20: select case must be receive, send or assign recv
../../../../go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:393:18: select case must be receive, send or assign recv
```

**Code reproducing the issue**:
```GOOS=js GOARCH=wasm go build -o contact.wasm```

**Environment**:
- Viper version: 1.7.1

**Comment by sagikazarmark** [comment]
@michael-db @kaidesu @alephnull you've upvoted this issue: can you please give #1121 a try?

**Comment by michael-db** [comment]
Thank you, @sagikazarmark. Unfortunately, after this I abandoned Viper and took another path. But maybe it is still needed by the original reporter @dpanic.

**Comment by dpanic** [comment]
I will give it a try shortly. Cheers, and thanks for taking care of this

**Comment by dpanic** [comment]
I confirm #1121 works
