### ISSUE TITLE
Can't parse TOML that includes quoted key

### ISSUE THREAD

**Issue by macrat** [spf13/viper#1074]
**Expected behavior (what you expected to happen)**:

I want to parse the TOML file that includes quoted key like below.

``` toml
"ab\"cd" = "ef"

"abc.def" = "ghi"

[foo."bar.baz"]
hello = "world"
```

This TOML should means same as below json.

``` json
{
  "ab\"cd": "ef",
  "abc.def": "ghi",
  "foo": {
    "bar.baz": {
      "hello": "world"
    }
  }
}
```

**Actual behavior (what actually happened)**:

`"ab\"cd" = "ef"` will causes an error that `While parsing config: (2, 2): invalid table array key: mismatched quotes` when reading config.

Other cases don't report the error but parse as an incorrect key like `abc.def` to `abc`.

**Repl.it link**:
https://repl.it/@macrat/viper-toml-quotedkey

**Code reproducing the issue**:

```go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/spf13/viper"
)

func main() {
	viper.SetConfigType("TOML")

	config := []byte(`
[foo."bar\"baz"]
hello = "world"
`)

	err := viper.ReadConfig(bytes.NewBuffer(config))
	fmt.Println("expected:", nil)
	fmt.Println("but got: ", err)

	fmt.Println()

	config = []byte(`
"str.test" = "abc"

[foo."bar.baz"]
hello = "world"
`)
	viper.ReadConfig(bytes.NewBuffer(config))

	var target struct {
		Str string `mapstructure:"str.test"`
		Foo map[string]struct {
			Hello string
		}
	}
	viper.Unmarshal(&target)

	j, _ := json.Marshal(target)
	fmt.Println(`expected: {"Str":"abc","Foo":{"bar.baz":{"Hello":"world"}}}`)
	fmt.Println("but got: ", string(j))
}
```

**Environment**:
- Viper version: v1.7.1
- Config source: file
- File format: TOML

**Anything else we should know?**:

This problem is seems to already [reported](https://github.com/pelletier/go-toml/issues/399) in pelletier/go-toml, and solved by [v1.8.0](https://github.com/pelletier/go-toml/releases/tag/v1.8.0).
So, maybe can fix by just upgrade go-toml.

**Comment by sagikazarmark** [comment]
@macrat Viper uses TOML v2 for a while now. Can you please confirm if this is still an issue?

Thanks!

**Comment by macrat** [comment]
@sagikazarmark 
Thank you for checking my issue!

I tried again and confirmed a part of this issue was solved.
Keys that include `\"` is correctly parsed now.

But, I still could not unmarshal a config that includes key contains `.` like `abc."def.ghi".jkl`.
So I think this is still an issue.

<details><summary>Another code reproducing this issue:</summary>

``` go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/pelletier/go-toml/v2"
	"github.com/spf13/viper"
)

func main() {
	viper.SetConfigType("TOML")

	config := []byte(`
"abc.def" = "ghi"

[foo."bar.baz"]
hello = "world"
`)
	viper.ReadConfig(bytes.NewBuffer(config))

	type T struct {
		AbcDef string `mapstructure:"abc.def" toml:"abc.def"`
		Foo    map[string]struct {
			Hello string
		}
	}

	target := T{}
	viper.Unmarshal(&target)
	j, _ := json.Marshal(target)
	fmt.Println("viper:  ", string(j))

	target = T{}
	toml.Unmarshal(config, &target)
	j, _ = json.Marshal(target)
	fmt.Println("go-toml:", string(j))

	// OUTPUT:
	// viper:   {"AbcDef":"","Foo":{"bar":{"Hello":""}}}
	// go-toml: {"AbcDef":"ghi","Foo":{"bar.baz":{"Hello":"world"}}}
}
```

```
go 1.19

require (
	github.com/pelletier/go-toml/v2 v2.0.5
	github.com/spf13/viper v1.13.0
)

require (
	github.com/fsnotify/fsnotify v1.6.0 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/magiconair/properties v1.8.6 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/pelletier/go-toml v1.9.5 // indirect
	github.com/spf13/afero v1.9.2 // indirect
	github.com/spf13/cast v1.5.0 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.4.1 // indirect
	golang.org/x/sys v0.1.0 // indirect
	golang.org/x/text v0.4.0 // indirect
	gopkg.in/ini.v1 v1.67.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

</details>

Addicionaly, I tried the same thing using JSON instead of TOML, and I found the same problem.
Sorry for my first reporting was not correct, the problem about keys that include `.` was not just for TOML.

Thank you.

**Comment by sagikazarmark** [comment]
That part is not going to work unless you set a custom key delimiter. Viper use dot as a default delimiter.

**Comment by macrat** [comment]
I'm so sorry. I didn't notice that.
Thank you very much! My issue is solved.
