### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by monolighter** [spf13/viper#1077]
$ go get github.com/spf13/viper
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer"

**Comment by Quantum12k** [comment]
same problem

**Comment by sagikazarmark** [comment]
@monolighter @Quantum12k do you have Go modules enabled? Viper requires go modules, otherwise it doesn't work.

**Comment by sagikazarmark** [comment]
Duplicate of #1076
