### ISSUE TITLE
cannot find package "github.com/hashicorp/hcl/hcl/printer" 

### ISSUE THREAD

**Issue by shipa988** [spf13/viper#1082]
"Pos": "..\\..\\..\\..\\..\\github.com\\spf13\\viper\\viper.go:39:2",
                        "Err": "cannot find package \"github.com/hashicorp/hcl/hcl/printer\"

**Comment by sagikazarmark** [comment]
https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#cannot-find-package
