### ISSUE TITLE
[README] Cannot find package errors

### ISSUE THREAD

**Issue by sagikazarmark** [spf13/viper#1083]
There has been an increase in "cannot find package" errors, especially related to the "hcl" package.

**Please do not open an issue for that!**

Read the troubleshooting guide instead: https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#cannot-find-package

**Comment by phpiscute** [comment]
@sagikazarmark hi sagika

https://github.com/hashicorp/hcl/hcl/printer  is 404 


> https://github.com/spf13/viper/blob/master/internal/encoding/hcl/codec.go

**Comment by sagikazarmark** [comment]
Please see the troubleshooting guide. Viper uses HCL v1.0.0.
