### ISSUE TITLE
Unmarshal function cannot parse (String)Slices

### ISSUE THREAD

**Issue by ck-schmidi** [spf13/viper#1105]
**Expected behavior (what you expected to happen)**:
My (Test) Config struct looks like this:
```go
type config struct {
	String      string
	StringSlice []string
}
```
Content of the file is:
```go
string: hello world
string_slice: 
  - a 
  - b 
  - c 
```
When executing Unmarshal:
```go
var config c
if err := viper.Unmarshal(&c); err != nil {
     return fmt.Errorf("failed to unmarshal into config: %v", err)
}
```
I expect to have both the `string` and the `string_slice` parsed into the Config struct.   
The `string` works perfectly, but `string_slice` doesn't:

```go
fmt.Printf("String: %s\n", c.String)`
fmt.Printf("StringSlice: %v\n", c.StringSlice)
```

Expected output:
```
String: hello world
StringSlice: [a b c]
```

**Actual behavior (what actually happened)**:
But the actual output is:
```
String: hello world
StringSlice: []
```

**BUT** if I call `viper.GetStringSlice("string_slice")` this gives me the correct result.

**So the main question is**: Why does parsing of (String)Slices does not work with the `viper.Unmarshal` function?  
Is there any chance to get that working?

Thank you in advance, have a nice day,
Markus

**Comment by kchugalinskiy** [comment]
`GetStringSlice` returns value by key using parsed config file. It is definitely mapstructure library but, call goes into `github.com/spf13/viper/viper.go:1062`, where input is correct for this case, whereas result isn't

**Comment by sagikazarmark** [comment]
Mapstructure expects your data under a key named `stringslice`, not `string_slice`. If you want to use a different key, use a struct tag:

```go
type config struct {
	String      string
	StringSlice []string `mapstructure:"string_slice"`
}
```
