### ISSUE TITLE
Is viper support to write back to config file?

### ISSUE THREAD

**Issue by wgwi** [spf13/viper#113]
as Title.

**Comment by didenko** [comment]
Currently does not seem to. Also, crude searches come back without meaningful hits:

https://github.com/spf13/viper/search?utf8=%E2%9C%93&type=Code&q=Write
https://github.com/spf13/viper/search?utf8=%E2%9C%93&type=Code&q=Marshall
https://github.com/spf13/viper/search?utf8=%E2%9C%93&type=Code&q=Serialize

**Comment by promisedlandt** [comment]
Seems like a duplicate of #33 ?

I would love to see that functionality too.

**Comment by didenko** [comment]
It is indeed a duplicate of #33
