### ISSUE TITLE
Values not serialized into struct when the tags have a different name

### ISSUE THREAD

**Issue by prateeknischal** [spf13/viper#1136]
**Expected behavior (what you expected to happen)**:
Viper should load the duration attribute from the file and Unmarshal it into the struct according to the json, toml or yaml tags which are specified in the struct.

**Actual behavior (what actually happened)**:
Viper is only assigning the duration value if the name of the tag is the exact same as the field except the first char is dropped in case. Example 

```go
type Foo struct {
        Bar    time.Duration `json:"bar" toml:"bar"` // works 
        BazQux time.Duration `json:"baz_qux" toml:"baz_qux"` // does not work
        FooBar time.Duration `json:"fooBar" toml:"fooBar"` // works
}

/**
[foo]
bar = "5s"
baz_qux = "5s"
fooBar = "5s"
*/
```

**Code reproducing the issue**:

```go
type config struct {
        Foo Foo `json:"foo" toml:"foo"`
}
type Foo struct {
        Bar    time.Duration `json:"bar" toml:"bar"`
        BazQux time.Duration `json:"baz_qux" toml:"baz_qux"`
        FooBar time.Duration `json:"fooBar" toml:"fooBar"`
}

func main() {
        s := bytes.NewBufferString(`
[foo]
bar = "5s"
baz_qux = "5s"
fooBar = "5s"
        `)
        v := config{}

        viper.SetConfigType("toml")
        viper.ReadConfig(s)
        viper.Unmarshal(&v)

        viper.Debug()
        json.NewEncoder(os.Stdout).Encode(v)
}
```

**Environment**:
- Viper version: 1.7.1
- Config source: file and buffer 
- File format: TOML

**Anything else we should know?**:
Since the fields are loaded in the `viper.AllSettings()` map, it can be worked around as 
```go
v, _ := json.Marshal(viper.AllSettings())
json.NewDecoder(bytes.NewBuffer(v)).Decode(&v)
```

**Comment by ning1875** [comment]
save issue ,keep watching.....

**Comment by sagikazarmark** [comment]
Please see the troubleshooting guide: https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unmarshaling-doesnt-work
