### ISSUE TITLE
`viper.SetConfigFile()` does not interpret `$HOME` as path variable

### ISSUE THREAD

**Issue by kvherro** [spf13/viper#1138]
**Expected behavior (what you expected to happen)**:
I expect Viper to [read in the config](https://github.com/spf13/viper#reading-config-files) specified by `$HOME/.aws/config`, interpreting `$HOME` as the `$HOME` path variable.

**Actual behavior (what actually happened)**:
Viper reports `panic: Fatal error config file: open $HOME/.aws/config: no such file or directory`

**Repl.it link**:

N/A

**Code reproducing the issue**:

```go
viper.SetConfigType("ini")
viper.SetConfigFile("$HOME/.aws/config")
err := viper.ReadInConfig()
	if err != nil {
		panic(fmt.Errorf("Fatal error config file: %s\n", err))
	}
v := viper.GetViper()
fmt.Println(v.Get("default.region"))
```

**Environment**:
- Viper version: `v1.7.0`
- Config source: file
- File format: INI

**Anything else we should know?**:
Explicitly using the absolute path works:
```go
viper.SetConfigFile("/Users/kherro/.aws/config")
```

**Comment by sagikazarmark** [comment]
Try wrapping the path with [os.ExpandEnv](https://golang.org/pkg/os/#ExpandEnv). Viper doesn't support env vars in direct paths, only in search paths.

**Comment by kvherro** [comment]
Wrapping the path with [os.ExpandEnv](https://golang.org/pkg/os/#ExpandEnv) produces the expected behavior. Specifically:
```go
viper.SetConfigFile(os.ExpandEnv("$HOME/.aws/config"))
```
