### ISSUE TITLE
Why did I get different results by "viper.Unmarshal" or "json.Unmarshal"

### ISSUE THREAD

**Issue by studyzhanglei** [spf13/viper#1150]
`var config struct{
		Dbname string `mapstructure:"db-name" json:"dbname" yaml:"db-name"`
		Name string `mapstructure:"name" json:"name" yaml:"name"`
	}

	v := viper.New()

	//先走consul 没有再走本地
	v.AddRemoteProvider("consul", "127.0.0.1:8500", "test")
	v.SetConfigType("json") // Need to explicitly set this to json
	if err := v.ReadRemoteConfig(); err == nil {
		fmt.Println(v.AllSettings())

		if err := v.Unmarshal(&config); err == nil {
			fmt.Println(config)
		}

		if str, err := json.Marshal(v.AllSettings()); err == nil {
			if err = json.Unmarshal([]byte(string(str)), &config); err == nil {
				fmt.Println(config)
			}
		}
	}`

![image](https://user-images.githubusercontent.com/43992249/121301245-7a253400-c92a-11eb-833d-8d648c1b05b3.png)

**Comment by studyzhanglei** [comment]
Maybe my usage is wrong。Could you tell me how to solve this problem? thank you😊

**Comment by sagikazarmark** [comment]
`db-name != dbname`

Next time please try to follow the issue template and format your code. Thanks!

**Comment by studyzhanglei** [comment]
> `db-name != dbname`
> 
> Next time please try to follow the issue template and format your code. Thanks!

I am very sorry ,  I know `db-name != dbname` ,  but why "json.Unmarshal" can get my desired result, "viper.Unmarshal" can't？

**Comment by sagikazarmark** [comment]
Your json struct tag is 'dbname', whereas mapstructure tag is 'db-name'.

**Comment by studyzhanglei** [comment]
How to compatible json and yaml？I want use the config file when use consul failed。

json like this`{"dbname":"test","name":"tony"}`

yaml config file like this `name: tony
db-name: test`

**Comment by sagikazarmark** [comment]
You can try registering an alias, but I think it's usually better to use the same keys across different formats.

**Comment by studyzhanglei** [comment]
> You can try registering an alias, but I think it's usually better to use the same keys across different formats.

Thank you， i will change my code with your suggestion。
