### ISSUE TITLE
io/fs: package io/fs is not in GOROOT

### ISSUE THREAD

**Issue by arriqaaq** [spf13/viper#1161]
**Expected behavior (what you expected to happen)**:

`go mod tidy` to work when viper 1.8.0 is imported

**Actual behavior (what actually happened)**:

Fails with the error:
```
gitlab.eng.com/xxx/zzz/cmd imports
	github.com/spf13/viper imports
	github.com/spf13/afero imports
	io/fs: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
gitlab.eng.com/xxx/zzz/cmd imports
	github.com/spf13/viper imports
	github.com/spf13/afero tested by
	github.com/spf13/afero.test imports
	testing/fstest: package testing/fstest is not in GOROOT (/usr/local/go/src/testing/fstest)
```

**Environment**:
- Viper version: 1.8.0
- go version: go1.15 darwin/amd64

**Comment by sagikazarmark** [comment]
The CI runs against Go 1.15. I can't reproduce it locally either:

```
[nix-shell:~/test]$ go version
go version go1.15.13 darwin/amd64

[nix-shell:~/test]$ go mod init test
go: creating new go.mod: module test

[nix-shell:~/test]$ go get github.com/spf13/viper
go: github.com/spf13/viper upgrade => v1.8.0
```

**Comment by arriqaaq** [comment]
Hey @sagikazarmark 

This does not happen on a `go mod init`

It just fails on `go mod tidy`

**Comment by kotyara85** [comment]
Same issue. Going to rollback to 1.7.1

**Comment by sagikazarmark** [comment]
@arriqaaq I can't reproduce it with `go mod tidy` either. Please provide steps to reproduce in a clean environment (clean GOPATH, clean module cache, `go.mod` that results in an error).

**Comment by tmac33** [comment]
Same issue here. But just infects `go mod tidy`. there is no other infects with `go run`.

**Comment by rengas** [comment]
Same issue here with v 1.8.0 and goland version 1.15

**Comment by moreandres** [comment]
Same here, to reproduce create a new module as above and then add a main.go file importing and using viper. Run the example and then try to tidy/why to see the issue happening.

```
package main

import (
        "github.com/spf13/viper"
)

func main() {
        viper.SetDefault("test", 0)
}
```
```
$ go version
go version go1.15.5 linux/amd64
```

```
$ cat go.mod 
module test

go 1.15

require github.com/spf13/viper v1.8.1
```

**Comment by sagikazarmark** [comment]
I'm able to reproduce this issue on Go 1.15.5, but I can no longer reproduce it after Go 1.15.10, so upgrading to that (or later) version should fix the problem.

References:
- https://golang.org/doc/devel/release#go1.15.minor
- https://github.com/golang/go/issues/44792

**Comment by sagikazarmark** [comment]
@arriqaaq @kotyara85 @tmac33 @rengas @moreandres Can someone confirm that upgrading to 1.15.10 resolves the issue?

**Comment by tmac33** [comment]
> @arriqaaq @kotyara85 @tmac33 @rengas @moreandres Can someone confirm that upgrading to 1.15.10 resolves the issue?

yes, upgrading can resolve this.
Thank you, @sagikazarmark

**Comment by sagikazarmark** [comment]
Cool! Please upgrade to a newer version then.

**Comment by DarthPestilane** [comment]
Upgrade to go1.15.10 to solve this? 
I'm using go1.14.14, ran into this issue, and I cannot upgrade the golang version.
How to resolve this? 
Now I have to use logrus@v1.7.1 instead, a downgrade... :(

**Comment by sagikazarmark** [comment]
@DarthPestilane you could try replacing the afero version. I don't think we use anything from the new 1.6.0 release:

```
$ cat go.mod 
module test

go 1.15

require github.com/spf13/viper v1.8.1

replace github.com/spf13/afero => github.com/spf13/afero v1.5.1
```

Keep in mind that Viper (similarly to Go itself) supports the two latest minor Go versions. (Yes, the readme is incorrect and needs updating)

**Comment by roygbip** [comment]
upgrade to go version go1.16.6  solve the problem.

**Comment by mgyong** [comment]
Having the same error with go1.16.7

go get github.com/spf13/viper@v1.8.1

github.com/spf13/viper imports
        github.com/spf13/afero imports
        io/fs: package io/fs is not in GOROOT (/home/mgyong/.go/src/io/fs)
