### ISSUE TITLE
Failed to install viper because of undefined: fs.SubFS

### ISSUE THREAD

**Issue by unchartedworks** [spf13/viper#1172]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Version

1.8.1

### Config Source

Defaults

### Expected Behavior

It should install viper without any errors.

### Actual Behavior

go: downloading golang.org/x/sys v0.0.0-20210510120138-977fb7262007
go: downloading golang.org/x/text v0.3.5
# github.com/spf13/afero
../../pkg/mod/github.com/spf13/afero@v1.6.0/iofs.go:28:4: undefined: fs.SubFS

### Steps To Reproduce

go get github.com/spf13/viper       

### Additional Information

OS: macOS

**Comment by sagikazarmark** [comment]
Please check if  #1161 solves your problem.

**Comment by unchartedworks** [comment]
Thanks! I have updated to the latest Go. This issue is gone.
