### ISSUE TITLE
InConfig() doesn't work as expected

### ISSUE THREAD

**Issue by ashep** [spf13/viper#1190]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.8.1

### Go Version

1.16

### Config Source

Manual set

### Format

Other (specify below)

### Repl.it link

https://replit.com/@ashep/ViperInConfigError#main.go

### Code reproducing the issue

```go
package main

import (
	"fmt"
	"github.com/spf13/viper"
)

func main() {
	cfg := viper.New()
	fmt.Printf("before set: %v\n", cfg.InConfig("foo"))
	cfg.Set("foo", "bar")
	fmt.Printf("after set: %v\n", cfg.InConfig("foo"))
}
```

### Expected Behavior

before set: false
after set: true

### Actual Behavior

before set: false
after set: false

**Comment by sagikazarmark** [comment]
Quoting the documentation:

> InConfig checks to see if the given key (or an alias) is in the config file. 

It only checks the config file that's being read (if any). You might want to use `IsSet` to check for all config sources. It's somewhat inconvenient, but we can't fix that in V1.
