### ISSUE TITLE
failed to Unmarshal object array in yaml

### ISSUE THREAD

**Issue by lzw5399** [spf13/viper#1202]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.8.1

### Go Version

1.16

### Config Source

Files

### Format

YAML

### Repl.it link

https://replit.com/@LinZhiwen/vipertest

### Code reproducing the issue

```go
https://replit.com/@LinZhiwen/vipertest
```

### Expected Behavior

`ObjArr` should not be empty

### Actual Behavior

`ObjArr` is empty

### Steps To Reproduce

see the repl.lt for detail
> https://replit.com/@LinZhiwen/vipertest

### Additional Information

.

**Comment by sagikazarmark** [comment]
https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unmarshaling-doesnt-work

If that doesn't help, please try to simplify your example and open a new issue.
