### ISSUE TITLE
compilation fails 

### ISSUE THREAD

**Issue by sumangithub123** [spf13/viper#1231]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

latest

### Go Version

1.17

### Config Source

Flags

### Repl.it link

 vendor/github.com/spf13/viper/viper_go1_16.go:22:27: undefined: afero.NewIOFS

### Code reproducing the issue

```go
vendor/github.com/spf13/viper/viper_go1_16.go:22:27: undefined: afero.NewIOFS
```

### Expected Behavior

 vendor/github.com/spf13/viper/viper_go1_16.go:22:27: undefined: afero.NewIOFS

### Actual Behavior

no issue

### Steps To Reproduce

 vendor/github.com/spf13/viper/viper_go1_16.go:22:27: undefined: afero.NewIOFS

### Additional Information

 vendor/github.com/spf13/viper/viper_go1_16.go:22:27: undefined: afero.NewIOFS

**Comment by sagikazarmark** [comment]
Can you please check which afero version is installed?

**Comment by sagikazarmark** [comment]
Disabled the new finder for now.

**Comment by sumangithub123** [comment]
> Disabled the new finder for now.

Hi , i did not understood what is the fix ?

**Comment by sagikazarmark** [comment]
Should be fixed on master now, but I think the problem is probably an old afero version.

**Comment by sumangithub123** [comment]
> Should be fixed on master now, but I think the problem is probably an old afero version.

Untill the fix is pushed to master , the problem remains ?
