### ISSUE TITLE
Default ignored on invalid environment value

### ISSUE THREAD

**Issue by frncmx-form3** [spf13/viper#1243]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.9.0

### Go Version

1.17

### Config Source

Environment variables

### Code reproducing the issue

```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/viper"
)

func main() {
	const key = "FOO"

	//must(os.Setenv(key, "1"))
	must(os.Setenv(key, "invalid"))
	viper.AutomaticEnv()
	viper.SetDefault(key, 2)

	fmt.Println("fromEnv:", os.Getenv(key))
	fmt.Println("fromViper:", viper.GetInt(key))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
```

### Expected Behavior

I would expect the `SetDefault` to be returned. Not returning the default on invalid environment setting introduces some risk, e.g., zero often means unlimited while the actual default could be a sensible limit.

### Actual Behavior

Viper returned 0.

### Steps To Reproduce

Just run the provided example, and observe the result.

### Additional Information

The root cause for this is that `viper.GetInt()` uses `cast.ToInt()` which just ignores error. This pattern applies to other getters, e.g., to `viper.GetDuration()`, too.

**Comment by sagikazarmark** [comment]
This is an unfortunate side-effect of the oversimplified API. Viper does not have a concept of invalid value at the moment. In fact, if anything is valid, it's the value that takes precedence as the rest are completely ignored.

I agree that it's not optimal, but I don't think returning the default would be better (ie. it would equally be a constant source of confusion).

Viper 2 will allow you to build your own solution for these kinds of situations, but the best I can imagine is to expose another method that returns an error in addition to retaining the current solution.

A couple solutions I can imagine:

Use the cast library directly:
```go
val, err := cast.ToIntE(viper.Get(key))
if err != nil {
    // it's not an int
}
```

Write a custom type/decoder and use `Unmarshal` or `UnmarshalKey`:

```go
type MyInt int

// implement TextUnmarshaler or a decoder hook
```

Details in this post: https://sagikazarmark.hu/blog/decoding-custom-formats-with-viper/

Happy to consider other alternative solutions, but I don't think falling back to the default is the right one (and it would be a massive BC break).

**Comment by frncmx-form3** [comment]
Thanks for the super quick and helpful response! I understand the backward compatibility concern. Even though, I would be a bit surprised if someone would depend on the zero (and not the set default) value returned in case of an invalid value present in the environment.

We agree that - in case of an invalid value set - both the current implementation and the suggested fall-back to default would be confusing to debug. On the other hand, we do set - when possible - production safe defaults. So if the environment ever gets misconfigured, most likely we wouldn't face an incident. That's cannot be said for zero values.

Maybe a `viper.Validate()` method would be the nicest thing to have, as that:
- could be explicitly called and a decision could be made by the user,
- could be customized when needed,
- as a bare minimum it could check if the set value can be parsed without error.

Just I don't see a way that could work without knowing the type of each key from the begging. Maybe `Validate()` could only verify keys which have a default value set.

I went with a helper method similar to your suggestion. As `cast.ToIntE(nil)` returns 0 without error, so I had to add a call to `viper.IsSet()` before casting. (A bit later, I realized Viper is such an over-kill for this project. As we just read from the environment. So I have plans to completely remove Viper from the project in the future.)

Feel free to close the issue from my side, I just wanted to raise awareness of this.

**Comment by sagikazarmark** [comment]
Personally, I don't like using `viper.Get*` functions. I prefer unmarshaling configuration onto structs, where I write a `Validate` function to validate the values in the struct.

Unfortunately, that won't solve the invalid value problem (they still fallback to zero values).

As I said, Viper can't really enforce a type for values, because it doesn't know what values should be (and I believe it shouldn't). The problem gets even more interesting when you have three values (env, file, default) all of them having different types. What then?

This is an incredibly deep rabbit hole.

Closing as it's not really something we can address now. Maybe in Viper 2. Personally, I'd love to play with Cue for Viper 2.
