### ISSUE TITLE
Marshal from struct

### ISSUE THREAD

**Issue by Airblader** [spf13/viper#1251]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

`viper.Unmarshal` allows us to decode the key-value configuration into our own struct. However, the reverse doesn't seem to exist, i.e. a way to decode our own struct back into the config.

This is necessary if we want to support modifying the config at runtime and writing it back, think some `my-cli config set foo bar` command in a CLI. Currently the only way to achieve this is to manually use `mapstructure` to convert the struct into a `map[string]interface{}`, and then ranging over that calling `viper.set` before finally writing the config. This is particularly not nice because we cannot access the Decoder config from viper.

### Proposed Solution

Add a new method

```
# Marshal marshals the struct into the config.
func Marshal(rawVal interface{}, opts... DecoderConfigOption) error
```

**Comment by Airblader** [comment]
I'd be happy to submit a PR if this is accepted and stands a chance of being merged & released – I'm not sure as to the status of the project.

**Comment by sagikazarmark** [comment]
> This is necessary if we want to support modifying the config at runtime and writing it back

This is currently not a high priority for the project, especially because configuration can be read from a wide range of sources, but writing is only supported by some of them.

**Comment by Airblader** [comment]
Maybe to clarify, "we" here referred to our project, not the viper project. It's still good to know, though, thanks for the update! We are no longer actively interested in this as we dropped viper due to the lack of being able to write the configuration back (for this, mapstructure tags alone don't suffice, so we need both mapstructure and json tags, at which point it was easier for us to just (un-)marshal ourselves).

**Comment by kalensk** [comment]
I have this same feature request and issue. I am assuming no further movement has been made on this?
