### ISSUE TITLE
nested keys in array?

### ISSUE THREAD

**Issue by meirwah** [spf13/viper#126]
How can I fetch a key from an array?
for instance: 

``` json
"stuff": {
        "onetype": [
            {"id":1,"name":"John Doe"},
            {"id":2,"name":"Don Joeh"}
        ],
        "othertype": {"id":3,"company":"ACME"}
      }
```

how can i get the first "id" field ? 
because nor "stuff.onetype.0.id" or "stuff.onetype.[0].id" are working...

**Comment by nithinmohan** [comment]
Have you got the solution? I am also facing the same issue

**Comment by bep** [comment]
I doubt that you can define an item in an array as a "nested key", so I doubt we're going to support this.

Why not do a `Get("onetype")` and then cast that to whatever slice type that is and then pick your item.

**Comment by meirwah** [comment]
This is what I did in the end...

**Comment by nithinmohan** [comment]
Thanks guys. This worked for me too

**Comment by laxmanvallandas** [comment]
type Temp struct{
        One OneType `yaml:"onetype,flow"`       
}
type OneType struct{
        id int `yaml:"id"`
        name string `yaml:"name"`        
}
temp := Get("onetype") 
returns []interface{}. how to cast intorder to get the value of onetype.id?
t1 := temp.(Temp)
throws: panic: interface conversion: interface {} is []interface {}, not main.Temp
