### ISSUE TITLE
Can't unmashal yaml

### ISSUE THREAD

**Issue by 89trillion-feiyang** [spf13/viper#1262]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.10.0

### Go Version

1.16.5

### Config Source

Files

### Format

YAML

### Code reproducing the issue

```go
package main

import (
	"fmt"

	"github.com/spf13/viper"
)

var Config config

type config struct {
	Mysql struct {
		DBAddress      []string `yaml:"dbMysqlAddress"`
		DBUserName     string   `yaml:"dbMysqlUserName"`
		DBPassword     string   `yaml:"dbMysqlPassword"`
	} `yaml:"mysql"`
}

func main() {
	viper.AutomaticEnv()
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath("./viper_test")
	err := viper.ReadInConfig()
	if err != nil {
		panic(fmt.Errorf("Fatal error config file: %w \n", err))
	}
	if err = viper.Unmarshal(&Config); err != nil {
		panic(fmt.Errorf("Fatal error config file: %w \n", err))
	}
	fmt.Println(Config.Mysql.DBAddress)
	fmt.Println(Config.Mysql.DBUserName)
	fmt.Println(Config.Mysql.DBPassword)
}

// ==============================================================
// yaml file is 
mysql:
  dbMysqlAddress: [ 127.0.0.1:3306 ]
  dbMysqlUserName: xxxx
  dbMysqlPassword: xxxx
```

### Expected Behavior

- Config.Mysql.DBAddress length is not 0
- Config.Mysql.DBUserName is not ""
- Config.Mysql.DBPassword is not ""

### Actual Behavior

- Config.Mysql.DBAddress length is 0
- Config.Mysql.DBUserName is ""
- Config.Mysql.DBPassword is ""

After I modified the yaml file and struct tag, it returned to normal
```yaml
mysql:
  dbAddress: [ 127.0.0.1:3306 ]
  dbUserName: xxxx
  dbPassword: xxxx
```

**Comment by sagikazarmark** [comment]
https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unmarshaling-doesnt-work
