### ISSUE TITLE
No mechanism to override logger

### ISSUE THREAD

**Issue by idcmp** [spf13/viper#1268]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

v.logger is now an interface, which is great, but there's no mechanism to override the default `jwwLogger{}` for the global Viper (`GetViper()`).

### Proposed Solution

introduce a `GetViper().UseLogger(newLogger Logger)` ?

**Comment by sagikazarmark** [comment]
Thanks for opening this issue @idcmp !

I opened another issue to track this as well: #1270

**Comment by sagikazarmark** [comment]
#1275 adds an experimental `WithLogger` function that allows overriding the builtin logger. Please note that it is not covered by the backwards compatibility promise.
