### ISSUE TITLE
Reading a .env file doesn't work properly with `SetEnvPrefix`

### ISSUE THREAD

**Issue by fredericbirke** [spf13/viper#1280]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.10.1

### Go Version

1.16

### Config Source

Environment variables, Files

### Format

Dotenv

### Repl.it link

https://github.com/fredericbirke/viper-bug

### Expected Behavior

It doesn't matter if I read my environment variables using a .env / dotenv file or if I really source them as environment variables, the effect on my application should always be the same.

### Actual Behavior

Prefixes don't work if a .env / dotenv file is read by viper as a config file (pleas see `viper.SetEnvPrefix("TEST_PREFIX")` of the repo). Please have a look at the linked reproduction repo. If you check it out and do `docker-compose up` the same program will start twice:
 - one time with the .env sourced as environment variables and 
 - one time with the .env read as a config file by viper

You can see that the `viper.GetString("foo")` will one time get the value of my environment variable (if they are sourced as real environment variables) and one time it won't find it (if the .env file is read as a config file).

This is especially troublesome, if the same .env file is used by both the application (in local development) and the docker-compose.

### Steps To Reproduce

Simply do docker-compose up in the repro, have a look at the outputs and the docker-compose file.

**Comment by sagikazarmark** [comment]
Unfortunately, this is the expected behavior at the moment. File reading and env var sourcing are two completely different implementations.

I'd suggest using a dotenv solution (that actually makes vars in a file env vars) for now. Viper 2 will allow more flexibility for us to make this work as you described.
