### ISSUE TITLE
Cannot import viper without -compat=1.17

### ISSUE THREAD

**Issue by Arsen6331** [spf13/viper#1283]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.10.1

### Go Version

1.17

### Config Source

Files

### Format

TOML

### Expected Behavior

`go mod tidy` runs without any errors

### Actual Behavior

`go mod tidy` outputs the following:

```
trident2 imports
        github.com/spf13/viper imports
        github.com/spf13/viper/internal/encoding/yaml imports
        gopkg.in/yaml.v2 tested by
        gopkg.in/yaml.v2.test imports
        gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127,
        but go 1.16 would select v1.0.0-20190902080502-41f04d3bba15
trident2 imports
        github.com/spf13/viper imports
        github.com/spf13/viper/internal/encoding/yaml imports
        gopkg.in/yaml.v2 tested by
        gopkg.in/yaml.v2.test imports
        gopkg.in/check.v1 imports
        github.com/kr/pretty loaded from github.com/kr/pretty@v0.1.0,
        but go 1.16 would select v0.2.0

To upgrade to the versions selected by go 1.16:
        go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
```

### Steps To Reproduce

1. Import `github.com/spf13/viper`
2. run `go mod tidy`

**Comment by sagikazarmark** [comment]
This is most probably caused by some downstream dependency. Just follow the instructions on screen and you should be good to go.
