### ISSUE TITLE
viper resolve properties bug

### ISSUE THREAD

**Issue by zhoudehua** [spf13/viper#1285]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.

### Viper Version

1.10.1

### Go Version

1.17

### Config Source

Files

### Format

Java properties

### Code reproducing the issue

```go
package main

import (
	"fmt"
	"github.com/spf13/viper"
)

func main() {

	viper.SetConfigName("web_configmap") // name of config file (without extension)
	viper.SetConfigType("properties")    // REQUIRED if the config file does not have the extension in the name
	viper.AddConfigPath("./config/")     // path to look for the config file in
	err := viper.ReadInConfig()          // Find and read the config file
	if err != nil {                      // Handle errors reading the config file
		panic(fmt.Errorf("Fatal error config file: %w \n", err))
	}

	fmt.Println(viper.Get("a.b"))
	fmt.Println(viper.Get("a.b.c"))

}
```

### Expected Behavior

> go run .\main.go
bug
found

### Actual Behavior

> go run .\main.go
bug
<nil>

### Steps To Reproduce

cat ./config/web_configmap.properties
a.b.c=found
a.b=bug

### Additional Information

when key exist like:

a.b=aaa
a.b.c=ccc

it will can not get the right value.

**Comment by sagikazarmark** [comment]
This is the expected behavior. Under the hood Viper is not a key-value store, but stores (most) data as a tree. So in your case `a.b` is either a leaf and has a value or a node that has other descendents. I can't even say it depends on the order in your config, because it's parsed as a map and the access of elements of a map in Go is random.
