### ISSUE TITLE
GetString on a yml prop with zeroes gets parsed as "0"

### ISSUE THREAD

**Issue by raulvc** [spf13/viper#1289]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

v1.10.1

### Go Version

1.17

### Config Source

Files

### Format

YAML

### Expected Behavior

when parsing this yml:
```
aws:
  account-id: 000000000
```

through viper config's 
```
GetString("aws.account-id")
```

I expected to receive a string `"000000000"`

### Actual Behavior

I'm getting `"0"` instead.

### Steps To Reproduce

```
# config.yml
aws:
  account-id: 000000000
```

```
config := viper.New()
config.AddConfigPath(".")
config.SetConfigName("config")
config.SetConfigType("yaml")

if err := config.ReadInConfig(); err != nil {
 [...]
}

accountId := config.GetString("aws.account-id") // should be "000000000" but is "0" instead
```

### Additional Information

Just a sidenote, if I declare `aws.account-id` with double quotes it gets parsed correctly (though either way is intuitive imo).

**Comment by sagikazarmark** [comment]
Unfortunately, YAML parses that literal as int by default: https://go.dev/play/p/TTcf7QvRyqb

I'd suggest quoting it. Closing as this isn't a bug per se.
