### ISSUE TITLE
Updation of vendor packages

### ISSUE THREAD

**Issue by tbankar** [spf13/viper#1298]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.8.1

### Go Version

1.15

### Config Source

Defaults

### Expected Behavior

As existing version of following packages has been EOLed and newest version are already available. Our internal Blakckduck scan detected those components as EOLed.

1. https://github.com/BurntSushi/toml
2. github.com/kr/text
3.  github.com/pmezard/go-difflib is no longer maintained (EOLed), kindly find an alternative.

### Actual Behavior

Old versions as per go.sum are:
https://github.com/BurntSushi/toml: v0.3.1
github.com/kr/text v0.1.0

**Comment by sagikazarmark** [comment]
@tbankar the packages you mentioned are transitive dependencies. As such, it's up to the upstream packages to update them. Alternatively, you can update them yourself in your own application.

go.sum doesn't tell you which version of these packages will be compiled in the final binary, so relying on go.sum for dependency scans will not yield reliable results.
