### ISSUE TITLE
build error in heroku, syntax error: unexpected o644, expecting comma 

### ISSUE THREAD

**Issue by 5arif** [spf13/viper#1306]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.10.0

### Go Version

1.17 

### Config Source

Manual set, Defaults

### Format

Dotenv

### Code reproducing the issue

```go
viper.SetConfigFile("database.env")
	viper.AddConfigPath(".")
	viper.AutomaticEnv()
	viper.SetConfigType("env")

	if err := viper.ReadInConfig(); err != nil {
		fmt.Printf("Error reading config file, %s", err)
	}
```

### Expected Behavior

build success in heroku

### Actual Behavior

```
remote: github.com/spf13/viper/internal/encoding/toml        
remote: github.com/spf13/viper        
remote: # github.com/spf13/viper        
remote: ../codon/tmp/cache/go-path/pkg/mod/github.com/spf13/viper@v1.10.0/viper.go:271:37: syntax error: unexpected o644, expecting comma or )        
remote: note: module requires Go 1.17  
```

### Steps To Reproduce

try to publish to heroku  with viper@v1.10.0 | viper@v1.10.1

### Additional Information

work localy with windows operating system

**Comment by sagikazarmark** [comment]
Are you sure your heroku environment runs Go 1.17?

The last line in your logs suggests otherwise:

```
remote: note: module requires Go 1.17 
```

**Comment by 5arif** [comment]
hi @sagikazarmark , im sorry, it's working now after i run `heroku config:set GOVERSION=go1.17` command, somehow my configuration is not readed propery in heroku
