### ISSUE TITLE
Nested keys are case sensitive ?

### ISSUE THREAD

**Issue by meirwah** [spf13/viper#131]
Seems that when I use for the next Json file:
```json
"Bot":{
    "Name":"watson"
  }
```

the path "Bot.name" it does not work ...
but path "Bot.Name" works...

Should it be case insensitive on all levels??

**Comment by ishidawataru** [comment]
Hi, I'm also hitting the same problem.

I think this can fix the issue. 
https://github.com/ishidawataru/viper/commit/79a5e3bd5bab855ce86e241556af9af9b445a34b

**Comment by AkihiroSuda** [comment]
I'm also hitting the problem.

+1 @ishidawataru

**Comment by ishidawataru** [comment]
This fixed the issue.

https://github.com/spf13/viper/commit/110492b3001269a0777997fcbe68a60828fac4cb

**Comment by meirwah** [comment]
:+1:

**Comment by sagikazarmark** [comment]
See #1014
