### ISSUE TITLE
Can't handle multiple yaml documents within one file

### ISSUE THREAD

**Issue by hahahaheihei** [spf13/viper#1318]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Given the following Kubernetes CNI YAML configuration file:

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system

---

# This manifest creates a Pod Disruption Budget for Controller to allow K8s Cluster Autoscaler to evict

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers

---
if i want to get some value ,i can use "[0].kind

### Proposed Solution

maybe viper could return a  yaml list

**Comment by sagikazarmark** [comment]
That's not really how Viper works. It could try to merge the two documents at best, but that would probably lead to more confusion.

I don't think this is something that Viper can support.
