### ISSUE TITLE
github.com/gogo/protobuf v1.1.1 indirect vulnerable

### ISSUE THREAD

**Issue by RohitPSPH** [spf13/viper#1324]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.10.1

### Go Version

1.16

### Config Source

Files

### Format

YAML, TOML

### Expected Behavior

We have found that this version of github.com/gogo/protobuf is vulnerable during our code scan.
![image](https://user-images.githubusercontent.com/97076861/163155710-e971f26f-7630-46b9-ab42-4ff843364ca8.png)

### Actual Behavior

Vulnerable due to indirect dependency in go mod

### Additional Information

**Dependency graph:**

[github.com/spf13/viper@v1.10.1](http://github.com/spf13/viper@v1.10.1) → [github.com/sagikazarmark/crypt@v0.4.0](http://github.com/sagikazarmark/crypt@v0.4.0)→ [github.com/armon/go-metrics@v0.3.10](http://github.com/armon/go-metrics@v0.3.10) → [github.com/prometheus/client_golang@v1.4.0](http://github.com/prometheus/client_golang@v1.4.0) → [github.com/prometheus/common@v0.9.1](http://github.com/prometheus/common@v0.9.1) → [github.com/prometheus/client_golang@v1.0.0](http://github.com/prometheus/client_golang@v1.0.0) → [github.com/prometheus/common@v0.4.1](http://github.com/prometheus/common@v0.4.1)→  [github.com/gogo/protobuf@v1.1.1](http://github.com/gogo/protobuf@v1.1.1)

**Comment by sagikazarmark** [comment]
It seems to be a false positive to me:

```shell
❯ go list -m all | grep gogo
github.com/gogo/protobuf v1.3.2
```

Although v1.1.1 shows up in `go.sum`, Go will never chose it. Unfortunately, most vulnerability scanners make the mistake of using go.sum to determine dependency versions, but `go.sum` is not a lock file.
