### ISSUE TITLE
dep reports go-toml/v2 is missing

### ISSUE THREAD

**Issue by danws2020** [spf13/viper#1340]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

v1.11.0

### Go Version

1.18.1

### Config Source

Defaults

### Expected Behavior

dep files to find go-toml/v2

### Actual Behavior

dep init on a clean project reports:

init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/pelletier/go-toml met constraints:
	v2.0.0: Could not introduce github.com/pelletier/go-toml@v2.0.0, as its subpackage github.com/pelletier/go-toml/v2 is missing.

**Comment by sagikazarmark** [comment]
Viper doesn't support dep. It requires Go modules.

**Comment by danws2020** [comment]
Ah, ok, we were using viper 1.4.0 in our Gopkg.toml file previously.
