### ISSUE TITLE
Cannot use Viper with any package that uses the flag package

### ISSUE THREAD

**Issue by ziffusion** [spf13/viper#136]
Viper has a dependency on pflag. Which makes it impossible to use Viper with any other package that uses the flag package.

This is because if you mix packages that use pflag with those that use flag, it requires you to call both flag.Parse() anf pflag.Parse() - one or both of which will fail.

This seems to be a crippling requirement because if I choose to use Viper, I am precluded from using any other third party package that uses flag.

**Comment by ziffusion** [comment]
I got a response from a maintainer for pflag.

The solution is to "import" all flags defined for flag into pflag, and then make a call to pflag.Parse() alone.

pflag provides a convenience function called AddGoFlagSet() to accomplish this.

**Comment by anthonyfok** [comment]
For reference:

@eparis's response suggesting the use of  [AddGoFlagSet](https://github.com/spf13/pflag/blob/master/golangflag.go#L90) is at https://github.com/spf13/pflag/issues/63
