### ISSUE TITLE
Viper does not unmarshal values passed from env or pflag

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [spf13/viper#1365]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.11.0

### Go Version

1.17

### Config Source

Flags, Environment variables

### Code reproducing the issue

```go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

type Config struct {
	AFlag string `mapstructure:"A_FLAG"`
}

// rootCmd is the root cobra command of ormos-web
var rootCmd = &cobra.Command{
	Use:   "myapp",
	Short: "My app",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("running")
	},
}

func InitConfig(cmd *cobra.Command) {
	var conf Config
	v := viper.New()
	v.AddConfigPath(".")
	v.SetConfigName(".env")
	v.SetConfigType("env")
	v.SetEnvPrefix("FOO")
	v.AllowEmptyEnv(true)
	v.AutomaticEnv()
	v.BindPFlags(cmd.Flags())
	v.Unmarshal(&conf)
	fmt.Printf("%+v\n", conf)
}

func main() {
	rootCmd.PersistentFlags().StringP("a-flag", "", "", "a flag")
	InitConfig(rootCmd)
	rootCmd.Execute()
}
```

### Expected Behavior

after 

```
export FOO_A_FLAG=test
```

or either running as

```
go run main.go --a-flag=test
```

the program should be printing

```
{AFlag:test}
running
```

### Actual Behavior

the program just prints

```
{AFlag:}
running
```

**Comment by gucki** [comment]
@pantelis-karamolegkos I think I hit the same bug. `AutomaticEnv` only really seems to work for me when the key has already a value, for example, from another source (ex. YAML) or a default. Otherwise, it's just ignored. So my solution/ workaround is to use define a default for all keys.

**Comment by ezdac** [comment]
I also encountered this issue, and there are several more open issues related to this.

`AutomaticEnv` is using `viper.AllSettings()` which then gets passed to a custom wrapper of `mapstructure` for unmarshaling all *known* keys into a struct, if those keys are present in the struct.
If you do an explicit `viper.Get()` or `viper.IsSet()` then the environment variables will be checked and recognized for the option, but `AllSettings` only iterates over keys viper already knows about (e.g. via `viper.SetDefault()`).

This can be made more explicit if the `ErrorUnset` mapstructure decoder config is active:

```go
// pass this function to the viper.Unmarshal() call 
func DecoderErrorUnset(c *mapstructure.DecoderConfig) {
	c.ErrorUnset = true
}
func InitConfig(cmd *cobra.Command) {
	var conf Config
	v := viper.New()
         // ... other setup, see original post
	v.Unmarshal(&conf, DecoderErrorUnset)
}
```

In my opinion when unmarshaling into well defined structs, the struct should be introspected, and then viper should be queried if it knows about the configuration options. Currently it is the other way around - if viper doesn't know about a field in the first place, it will be simply ignored during unmarshaling.
