### ISSUE TITLE
Cannot pass the go-lint check

### ISSUE THREAD

**Issue by anotherGoogleFan** [spf13/viper#1380]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.12.0

### Go Version

1.18.3

### Config Source

Files

### Format

YAML

### Code reproducing the issue

```go
// Not caused by code but I'd like to put code here
package config

import (
	"os"

	"github.com/anotherGoogleFan/log"
	"github.com/spf13/viper"
)

type AppConfig struct {
  // some codes here
}

// 应用配置文件
var Conf AppConfig

const (
	APPLICATION_CONF_PATH = "./configs"
)

func init() {
	log.SetFormatter(log.FORMAT_JSON)
	log.SetOutput(os.Stdout)

	vipConfig := viper.New()
	vipConfig.SetConfigName("application")
	vipConfig.AddConfigPath(APPLICATION_CONF_PATH)
	vipConfig.SetConfigType("yaml")
	err := vipConfig.ReadInConfig()
	if err != nil {
		log.Fields{
			"err": err.Error(),
		}.Panic("fail to read config")
	}
	mode := vipConfig.GetString("application.mode")
	log.Fields{
		"application_mode": mode,
	}.Info("GET MODE SUCCESS")

	if err := vipConfig.Unmarshal(&Conf); err != nil {
		log.Fields{
			"err": err.Error(),
		}.Panic("fail to unmarshal config")
	}

	log.Fields{
		"config": Conf,
	}.Info("CONFIG LOAD SUCCESS")
}
```

### Expected Behavior

Pass the go-lint tool test

### Actual Behavior

level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"gopkg.in/yaml.v3\"\n\n"

### Steps To Reproduce

I use docker to build, and before build I use the lint tool:
  golangci/golangci-lint:latest-alpine
command: golangci-lint run -v ./... > golangci_lnt_report.log

**Comment by anotherGoogleFan** [comment]
I tried ```github.com/spf13/viper v1.11.0``` and the problem disappeared. 
So it's likely something unexpected happend in ```github.com/spf13/viper v1.12.0```

**Comment by sagikazarmark** [comment]
Viper 1.12 uses YAML v3 for encoding/decoding yaml. It's highly unlikely though that this is an issue with Viper itself.

Please make sure that you use the latest:

- Go version
- Viper version
- Golangci-lint version

Make sure that your other dependencies are up-to-date (eg. yaml v3 is installed properly along with the rest of the dependencies)

Before doing all that, try running `go mod tidy`.
