### ISSUE TITLE
Support custom config key generator

### ISSUE THREAD

**Issue by cxy1cxy2cxy3** [spf13/viper#1392]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

viper always assumes a lower-cased key given.
acutally
users need upper-cased or more complex format of key to store/load

### Proposed Solution

type Viper struct {
    keyGenerator KeyGenerator
}

type KeyGenerator interface{
  GetKey(key string) string
}

func (v *Viper) CustomKeyGenerator(kg KeyGenerator) {
  v.keyGenerator = kg
}

func (v *Viper) GetKey(key string) {
 if v.keyGenerator != nil {
  return v.keyGenerator.GetKey(key)
 }
 return strings.ToLower(key)
}

**Comment by sagikazarmark** [comment]
Viper is lower case for a reason and that's not going to change anytime soon.

See #1014 for more details.
