### ISSUE TITLE
GetStringMap reversed order

### ISSUE THREAD

**Issue by Ran-Xing** [spf13/viper#1398]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

v1.12.0

### Go Version

1.18

### Config Source

Files

### Format

YAML

### Repl.it link

none

### Code reproducing the issue

```go
/*

messageText="abc"


Group:
	abc: 123
	def: 456

*/

if strings.Contains(fmt.Sprintf("%v", viper.GetStringMap("Group")), messageText) {
	for i, v := range viper.GetStringMap("Group") {
		if strings.Contains(messageText, i) && v != "" {
			fmt.Println(v)
		}
	}
}
```

### Expected Behavior

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/73819467/178088549-c26235f2-05e9-4ebd-86dd-e620d4bf281a.png">

### Actual Behavior

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/73819467/178088538-d4717bdc-d572-4122-8957-d86951109061.png">

### Steps To Reproduce

If you need anything, please let me know

### Additional Information

https://github.com/spf13/viper/issues/708
I don't think the issue is fully fixed

**Comment by sagikazarmark** [comment]
Please provide a fully functioning code example (preferrably a repl.it link) and a detailed description of the bug.
