### ISSUE TITLE
Unmarshal doesn't check environment variables with AutomaticEnv

### ISSUE THREAD

**Issue by backerman** [spf13/viper#140]
viper.Unmarshal will not unmarshal from environment variables.

This problem was resolved in issue #41 but appears to have returned.

Example code: https://gist.github.com/backerman/347c4b0da5447d6f1faa

**Comment by backerman** [comment]
Example has an error in it and doesn't demonstrate the behavior - will resubmit when I've got a good test case.

**Comment by sagikazarmark** [comment]
Please see and follow the issue above. ☝️

**Comment by 89z** [comment]
https://github.com/spf13/viper/issues/140
https://github.com/spf13/viper/issues/507
https://github.com/spf13/viper/issues/522
https://github.com/spf13/viper/issues/576
https://github.com/spf13/viper/issues/911

**Comment by 89z** [comment]
https://github.com/spf13/viper/issues/140
https://github.com/spf13/viper/issues/188
https://github.com/spf13/viper/issues/212
https://github.com/spf13/viper/issues/522
https://github.com/spf13/viper/issues/576
https://github.com/spf13/viper/issues/761
https://github.com/spf13/viper/issues/911
