### ISSUE TITLE
viper.SetConfigType("ini")  <-- not effective if toml file exists. not reading devop.ini, devop.toml read instead

### ISSUE THREAD

**Issue by jingkang99** [spf13/viper#1408]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.12.0

### Go Version

1.8.3

### Config Source

Files

### Format

INI

### Repl.it link

no

### Code reproducing the issue

```go
// root.go

package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var configFile string

var rootCmd = &cobra.Command{
	Use:   "devop",
	Short: "check project status",
	Long:  ``,

	// Uncomment the following line if your bare application
	// has an action associated with it:
	// Run: func(cmd *cobra.Command, args []string) { },
}

func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	cobra.OnInitialize(initConfig)

	rootCmd.PersistentFlags().StringVarP(&configFile, "config", "c", "", "config file (default is devop.cnf)")
	
	// Cobra also supports local flags, which will only run when this action is called directly.
	//rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}

func initConfig() {

	if configFile != "" {
		viper.SetConfigFile(configFile) // Use config file from the flag.
	} else {
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")

		viper.SetConfigType("ini")	// not effective if toml exists
		viper.SetConfigName("devop")
	}

	viper.AutomaticEnv()

	if err := viper.ReadInConfig(); err != nil {		
		fmt.Println("Error: " + viper.ConfigFileUsed(), err)
	}

	fmt.Println("host: ", viper.GetString("db_mysql.host"))

	fmt.Fprintln(os.Stderr, "\nconf:", viper.ConfigFileUsed())
	viper.Debug()
}
```

### Expected Behavior

viper.SetConfigName("devop")

if viper.SetConfigType("ini") set to ini, I expect viper to read devop.ini, not devop.toml

### Actual Behavior

if both files, devop.ini and devop.toml exist, viper reads devop.toml

### Steps To Reproduce

use cobra-cli create a skeleton project, and create both devop.ini and devop.toml

### Additional Information

no

**Comment by sagikazarmark** [comment]
You can use [SetConfigFile](https://pkg.go.dev/github.com/spf13/viper#SetConfigFile) to use a specific file.

**Comment by jingkang99** [comment]
yes, [SetConfigFile](https://pkg.go.dev/github.com/spf13/viper#SetConfigFile) works
Thanks
