### ISSUE TITLE
fsnotify does not provide watcher.Events for aix

### ISSUE THREAD

**Issue by szydell** [spf13/viper#1416]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

It is not possible to compile viper for the aix/ppc64. Fsnotify is not fully supporting aix.

### Proposed Solution

Since 1.5.2 fsnotify is compiling on AIX. Unfortunately Viper is still not.
For this platform fsnotify does not provide watcher.Events
```watcher.Events undefined (type *fsnotify.Watcher has no field or method Events)```
Details: https://github.com/fsnotify/fsnotify/commit/bfa0135e7e7333f9552eac2ddd8771f31e818610

Could you please disable filewatching for this platform? i.e. using //go:build !aix for that part?

### Alternatives Considered

There is a PR in fsnotify that theoritically should add file watching for AIX too, but the code is not optimized yet, so it for sure will take a lot of time till released.
https://github.com/fsnotify/fsnotify/pull/326

It took 2y to release a workaround mentioned as a 'Proposed Solution': https://github.com/fsnotify/fsnotify/issues/353

### Additional Information

Result can be repreduced using: GOOS='aix' GOARCH='ppc64' go build

Logs:

```$ ./buildAix.sh 
# github.com/spf13/viper
...\go\pkg\mod\github.com\spf13\viper@v1.12.0\viper.go:457:33: watcher.Events undefined (type *fsnotify.Watcher has no field or method Events)
...\go\pkg\mod\github.com\spf13\viper@v1.12.0\viper.go:484:31: watcher.Errors undefined (type *fsnotify.Watcher has no field or method Errors)

$ go version
go version go1.19 windows/amd64```

**Comment by sagikazarmark** [comment]
@szydell @achuchev can you please test the [disable-watcher-aix](https://github.com/spf13/viper/tree/disable-watcher-aix) branch?

**Comment by sagikazarmark** [comment]
Excellent, thanks for the feedback!
