### ISSUE TITLE
WatchConfig() does not work reliably with certain text editors

### ISSUE THREAD

**Issue by anthonyfok** [spf13/viper#142]
This new feature "Add dynamic reading of config file support" (Issue #116, commit e37b56e) is a welcomed addition, especially it enables Hugo to reload its config.toml automatically!  Yay!

Unfortunately, due to different ways how text editors save changes to the config file (e.g., `config.toml`) and the filesystem event the underlying OS generates, the WatchConfig() may fail to detect changes, and may even quit watching altogether.

The current WatchConfig() closely follows the upstream example https://github.com/go-fsnotify/fsnotify/blob/master/example_test.go in checking for only the **fsnotify.Write** event (Compare https://github.com/spf13/viper/blob/master/viper.go#L245 with https://github.com/go-fsnotify/fsnotify/blob/master/example_test.go#L28), but it appears that quite a few popular editors instead do a "**Save** to another temporary file, then **move** the temporary file to overwrite the original".

Examples (as tested on Linux):

* **GNU nano**: "config.toml": WRITE
* **Vim**: "config.toml": CHMOD, then "config.toml": REMOVE, then the watcher stops working.
* **gedit** (GNOME): Same as Vim.
* Manually create config.toml.tmp, then `mv config.toml.tmp config.toml`: Same as Vim.
* Manually create config.toml.tmp, then `cp config.toml.tmp config.toml`: Same as GNU nano.

I started writing this issue report intending to suggest that WatchConfig() watches for other fsnotify events too like RENAME and CREATE, but now I begin to suspect an issue with the upstream fsnotify itself, as Mac user @wangjild reported in go-fsnotify/fsnotify#80: "Miss events when use mv to overwrite the file".

Perhaps what @nathany said, "When a REMOVE event happens, it stops watching that file, but I haven't yet looked into this scenario where the file is overwritten", that is the root cause of the problem.

**Comment by anthonyfok** [comment]
I am beginning to think that the inability to watch a deleted file is not due to fsnotify's deficiency, but rather, due to how the underlying OS works.  See go-fsnotify/fsnotify#49

If that is the case, perhaps we should be watching the directory containing the config file instead on watching the config file itself?

**Comment by fgrosse** [comment]
I also ran into this issue when trying out the feature locally when using vim.

I aggree with @akutz that we should watch the directory instead.
The following patch worked for me but I am not sure about the ` event.Name == v.configFile` part:

```diff
➤ git diff
diff --git a/viper.go b/viper.go
index 4a5b1eb..7e3fe52 100644
--- a/viper.go
+++ b/viper.go
@@ -242,7 +242,8 @@ func (v *Viper) WatchConfig() {
                        for {
                                select {
                                case event := <-watcher.Events:
-                                       if event.Op&fsnotify.Write == fsnotify.Write {
+                                       if event.Name == v.configFile &&
+                                               event.Op&fsnotify.Write == fsnotify.Write {
                                                err := v.ReadInConfig()
                                                if err != nil {
                                                        log.Println("error:", err)
@@ -256,10 +257,10 @@ func (v *Viper) WatchConfig() {
                }()
 
                if v.configFile != "" {
-                       watcher.Add(v.configFile)
+                       watcher.Add(filepath.Dir(v.configFile))
                } else {
                        for _, x := range v.configPaths {
-                               err = watcher.Add(x)
+                               err = watcher.Add(filepath.Dir(x))
                                if err != nil {
                                        log.Fatal(err)
                                }
```

I will probably submit a PR next year :fireworks:

See also https://github.com/guard/guard/wiki/Analysis-of-inotify-events-for-different-editors

**Comment by bep** [comment]
See https://github.com/go-fsnotify/fsnotify/pull/111

**Comment by bep** [comment]
>If that is the case, perhaps we should be watching the directory containing the config file instead on watching the config file itself?

Yes, that is my conclusion. In all the rename cases I have tested on Linux, the file will eventually come back with a CREATE event, so I have added a check for the filename in the event handler. This should fix this issue for "all" once go-fsnotify/fsnotify#111 for OS X is closed.

**Comment by anthonyfok** [comment]
:heart:

**Comment by nathany** [comment]
fsnotify v1.2.9 includes @bep's fix. thanks

**Comment by anthonyfok** [comment]
Thank you @nathany!  You are awesome!  :-)

**Comment by bep** [comment]
Closing this now -- I'm pretty confident that this should work cross-editor/platform now.
