### ISSUE TITLE
TOML: incomplete number

### ISSUE THREAD

**Issue by muuvmuuv** [spf13/viper#1434]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.13.0

### Go Version

1.19.1

### Config Source

Files

### Format

TOML

### Repl.it link

https://replit.com/@muuvmuuv/Viper-TOML-error#main.go

### Expected Behavior

Should read TOML sections as User map

### Actual Behavior

Undefined error

**Comment by sagikazarmark** [comment]
I believe you have to put values in quotes in TOML

The error could be more informative though. See https://github.com/pelletier/go-toml/issues/413

**Comment by muuvmuuv** [comment]
Perfect, thanks!
