### ISSUE TITLE
Flag does not take precedence over config

### ISSUE THREAD

**Issue by andig** [spf13/viper#1444]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.13.0

### Go Version

1.19

### Config Source

Flags

### Format

YAML

### Code reproducing the issue

```go
package main

import (
	"path/filepath"
	"testing"

	"github.com/spf13/afero"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// AbsFilePath calls filepath.Abs on path.
func AbsFilePath(t *testing.T, path string) string {
	t.Helper()

	s, err := filepath.Abs(path)
	if err != nil {
		t.Fatal(err)
	}

	return s
}

func TestReadInConfig(t *testing.T) {
	fs := afero.NewMemMapFs()

	err := fs.Mkdir("/etc/viper", 0o777)
	require.NoError(t, err)

	file, err := fs.Create(AbsFilePath(t, "/etc/viper/config.yaml"))
	require.NoError(t, err)

	_, err = file.Write([]byte(`key: value`))
	require.NoError(t, err)

	file.Close()

	v := viper.New()

	v.SetFs(fs)
	v.SetConfigFile(AbsFilePath(t, "/etc/viper/config.yaml"))

	err = v.ReadInConfig()
	require.NoError(t, err)

	assert.Equal(t, "value", v.Get("key"))

	cmd := &cobra.Command{}

	cmd.PersistentFlags().String("key", "precedence-value", "")
	flag := cmd.PersistentFlags().Lookup("key")
	assert.NotNil(t, flag)

	assert.Nil(t, v.BindPFlag("key", flag))

	assert.Equal(t, "precedence-value", v.Get("key"))
}
```

### Expected Behavior

According to README, a flag should take precedence over config.

### Actual Behavior

Config file wins, even when flag is specified on the cobra command line. Test case reproduces this by checking against the default value.

### Steps To Reproduce

See test case above. it is copied from the standard viper tests plus binding cobra command added.

**Comment by sagikazarmark** [comment]
The documentation doesn't articulate this well enough, but flags take precedence when they are actually passed to your program. Flag defaults don't take precedence over....well, basically anything, but manual defaults (ie. `SetDefault`).

That being said, flag default values _are_ considered which is why the test passes if you remove the file part.

I realize this may be confusing (and undocumented), however, with the explanation above it should actually make a lot of sense: the alternative would mean that if you bind a flag to a value, it would basically always take the flag default value instead of anything else you pass to your program. That wouldn't make much sense IMO.

I'm curious though what your use case is that requires flag defaults taking precedence over other config sources.

**Comment by andig** [comment]
> I'm curious though what your use case is that requires flag defaults taking precedence over other config sources.

@sagikazarmark thanks for the reply. Indeed I don't care for the default value to take precedence.

> Config file wins, even when flag is specified on the cobra command line. 

This is my actual issue. Command line comes second to config file.

> Test case reproduces this by checking against the default value.

This was my attempt for a reproducer. If you could give a hint for how to write a testcase that simulates the command line I'd be happy to update the issue with a better test.

**Comment by andig** [comment]
I have a very ugly workaround for my issue but I'd rather fix the root cause:

```go
// setLogLevel sets log level from config overwritten by command line
// https://github.com/spf13/viper/issues/1444
func setLogLevel(cmd *cobra.Command) {
	if flag := cmd.Flags().Lookup("log"); viper.GetString("log") == "" || flag.Changed {
		viper.Set("log", flag.Value.String())
	}
	util.LogLevel(viper.GetString("log"))
}
```

When I `viper.Set()` the value it can be retrieved, just having the flag set does not return the flag's value.

**Comment by andig** [comment]
Here's an updated test that should imho show the expected behaviour but fails, too:

```go
cmd := &cobra.Command{}

cmd.PersistentFlags().String("key", "", "") // no default
flag := cmd.PersistentFlags().Lookup("key")
assert.NotNil(t, flag)

assert.Nil(t, v.BindPFlag("key", flag))
assert.Nil(t, flag.Value.Set("precedence-value")) // explicitly set the flag

assert.Equal(t, "precedence-value", v.Get("key"))
```

Result:

    Diff:
    --- Expected
    +++ Actual
    @@ -1 +1 @@
    -precedence-value
    +value

**Comment by sagikazarmark** [comment]
You never call parse on the FlagSet. Internally, Viper registers a hook in the FlagSet that gets called when you call Parse and sets the values.

**Comment by sagikazarmark** [comment]
Here is a test that passes:

```go
package main

import (
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestReadInConfig(t *testing.T) {
	v := viper.New()

	v.SetDefault("key", "value")

	assert.Equal(t, "value", v.Get("key"))

	cmd := &cobra.Command{}

	cmd.PersistentFlags().String("key", "", "") // no default
	flag := cmd.PersistentFlags().Lookup("key")
	assert.NotNil(t, flag)

	require.NoError(t, v.BindPFlag("key", flag))

	err := cmd.PersistentFlags().Parse([]string{"--key", "precedence-value"})
	require.NoError(t, err)

	assert.Equal(t, "precedence-value", v.Get("key"))
}
```

**Comment by andig** [comment]
Thank you. Turns out to be error in my code. The call to `Parse()` made it obvious, much appreciated!
