### ISSUE TITLE
Can't get value when key contain "."

### ISSUE THREAD

**Issue by shadow1ng** [spf13/viper#1450]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

v1.13.0

### Go Version

1.19

### Config Source

Files

### Format

YAML

### Code reproducing the issue

```go
type HostPaths struct {
	HostPath
}
type HostPath map[string][]string

func TestViper(t *testing.T) {
	var c = make(map[string][]string)
	c["github.com"] = []string{"/api", "/test"}
	var b HostPaths
	b.HostPath = c
	bs, err := yaml.Marshal(b)
	if err != nil {
		log.Fatalf("unable to marshal config to YAML: %v", err)
	}
	fmt.Println(string(bs))
}

func TestViper2(t *testing.T) {
	v := viper.New()
	v.SetConfigFile("test.yaml")
	if err := v.ReadInConfig(); err != nil {
		panic(err)
	}
	var seq HostPaths
	if err := v.Unmarshal(&seq); err != nil {
		panic(err)
	}
	fmt.Println(seq)
}
```

### Expected Behavior

ok

### Actual Behavior

if key contain ".",viper will error
```

panic: 1 error(s) decoding:

* 'HostPath[github][0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[com:[/api /test]]' [recovered]
	panic: 1 error(s) decoding:

* 'HostPath[github][0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[com:[/api /test]]'
* 
```

### Steps To Reproduce

test.yaml
```
hostpaths:
  baidu.com:
    - /
    - /test
  github.com:
    - /
    - /test
  ```

![image](https://user-images.githubusercontent.com/39651966/196207398-bbc4c7e9-9d9a-4b2e-882e-265e90a18eb8.png)

**Comment by PatrickChagastavares** [comment]
@shadow1ng
[this issue closed](https://github.com/spf13/viper/issues/977) soluction this problema.

The solution is to use

```
v := viper.NewWithOptions(viper.KeyDelimiter("::"))
```
