### ISSUE TITLE
Cannot parse `netip.Addr`

### ISSUE THREAD

**Issue by milkpirate** [spf13/viper#1472]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.14.0

### Go Version

1.18

### Config Source

Manual set

### Format

YAML

### Code reproducing the issue

```go
package main

import (
	"bytes"
	"fmt"
	"github.com/spf13/viper"
	"net/netip"
)

type Config struct {
	Records []Record `yaml:"records,omitempty"`
}

type Record struct {
	IP netip.Addr `yaml:"ip,omitempty"`
}

var yamlExample = []byte(`
records:
  - ip: "192.168.1.48"
  - ip: 192.168.1.230
`)

func main() {
	viper.SetConfigType("yaml")
	err := viper.ReadConfig(bytes.NewBuffer(yamlExample))
	if err != nil {
		fmt.Println(err)
	}
	err = viper.Unmarshal(new(Config))
	if err != nil {
		fmt.Println(err)
	}
}
```

### Expected Behavior

Terminate successfully.

### Actual Behavior

```bash
2 error(s) decoding:

* 'Records[0].IP' expected a map, got 'string'
* 'Records[1].IP' expected a map, got 'string'
```

### Steps To Reproduce

```
$ go run main.go 
```

### Additional Information

`netip.Addr` does implement the `UmarshalYAML` interface, and with `yaml.v3` its working fine.

_No response_

**Comment by sagikazarmark** [comment]
Unmarshal doesn't use YAML at that point. I doubt it works with any of the serialization formats.

This will have to be supported by mapstructure.

**Comment by sagikazarmark** [comment]
Submitted a PR to mapstructure: mitchellh/mapstructure#315

While it's being reviewed, you can easily take the code from the PR and use it.

You need to pass a custom [decode hook](https://github.com/spf13/viper/blob/master/viper.go#L139) to `Unmarshal`. You might want to combine that with the [default](https://github.com/spf13/viper/blob/master/viper.go#L1104).

**Comment by milkpirate** [comment]
Thanks a lot! :smiling_face_with_three_hearts:
