### ISSUE TITLE
AutomaticEnv function failing to read environment variables in Go code

### ISSUE THREAD

**Issue by pejeio** [spf13/viper#1522]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.15.0

### Go Version

1.20.1

### Config Source

Environment variables

### Format

Other (specify below)

### Code reproducing the issue

```go
package main

import (
	"fmt"
	"log"

	"github.com/spf13/viper"
)

type Config struct {
	FbClientId string `mapstructure:"FB_CLIENT_ID"`
}

func LoadConfig() (config Config, err error) {
	viper.AutomaticEnv()

	err = viper.Unmarshal(&config)
	if err != nil {
		return
	}
	return
}

func main() {
	type Config struct {
		FbClientId string `mapstructure:"FB_CLIENT_ID"`
	}

	cfg, err := LoadConfig()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Print(cfg.FbClientId)
}
```

### Expected Behavior

After running this command, I expect `fmt.Print(cfg.FbClientId)` to log `123`:
```sh
export FB_CLIENT_ID="123" && go run main.go
```

### Actual Behavior

There is no output in the console.

**Comment by PrimaryCY** [comment]
I have the same problem
