### ISSUE TITLE
Config File "config" Not Found in "[]" 

### ISSUE THREAD

**Issue by infoBrainSys** [spf13/viper#1531]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

v1.15.0

### Go Version

go version go1.20.2 darwin/amd64

### Config Source

Environment variables, Files

### Format

YAML

### Code reproducing the issue

```go
func Config() (*viper.Viper, error) {
	v := viper.New()
	v.SetConfigType("yaml")
	v.SetConfigFile("data/robot_config.yaml")
	if err := viper.ReadInConfig(); err != nil {
		fmt.Println(err)
		return nil, err
	}
	return v, nil
}
```

```go
func TestViper(t *testing.T) {
	v, err := io.Config()
	if err != nil {
		return
	}
	a := v.GetString("UIServerAddr")
	fmt.Println(a)
}
```

### Expected Behavior

=== RUN   TestViper
Config File "config" Not Found in "[]"
--- PASS: TestViper (2.73s)
PASS

### Actual Behavior

just wanna gei a value in config.yaml

### Additional Information

<img width="829" alt="err" src="https://user-images.githubusercontent.com/40877623/229408561-af3e6844-be9a-4490-a93b-43fd9915b93d.png">

**Comment by unique0lai** [comment]
```golang
func Config() (*viper.Viper, error) {
	v := viper.New()
	v.SetConfigType("yaml")
	v.SetConfigFile("data/robot_config.yaml")
	if err := v.ReadInConfig(); err != nil {
		fmt.Println(err)
		return nil, err
	}
	return v, nil
}
```

You create a new config, so you should use `v.ReadInConfig`.

**Comment by infoBrainSys** [comment]
> ```go
> func Config() (*viper.Viper, error) {
> 	v := viper.New()
> 	v.SetConfigType("yaml")
> 	v.SetConfigFile("data/robot_config.yaml")
> 	if err := v.ReadInConfig(); err != nil {
> 		fmt.Println(err)
> 		return nil, err
> 	}
> 	return v, nil
> }
> ```
> 
> You create a new config `v`, so you should use `v.ReadInConfig`.

I was careless，thanks～
