### ISSUE TITLE
The env attribute cannot be specified as an attribute of a struct

### ISSUE THREAD

**Issue by PrimaryCY** [spf13/viper#1545]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.15.0

### Go Version

1.17.8

### Config Source

Environment variables

### Format

Other (specify below)

### Code reproducing the issue

```go
func main(){
        type C struct {
		HOME string `mapstructure:"HOME"`
	}

	c := C{}

	viper.AutomaticEnv()
	err := viper.Unmarshal(&c)
	if err != nil {
		panic(err)
	}
	fmt.Println(c.HOME)
	fmt.Println(viper.Get("HOME"))

}
```

### Expected Behavior

I want to get the value of home from the structure
output:
/Users/cy
/Users/cy

### Actual Behavior

output:

/Users/cy

### Steps To Reproduce

computer:
macOS Catalina version: 10.15.7(19h15)
MacBook Pro (15-inch, 2018)

**Comment by twgcode** [comment]
I've also encountered this issue, and I've currently resolved it by using `viper.BindEnv("HOME")`. However, this doesn't seem very user-friendly. Could you please confirm if this bug has been fixed? I'm currently using Go 1.20.3 and Viper v1.17.0.
