### ISSUE TITLE
How to read JSON file from bindata file generated by 'go-bindata'

### ISSUE THREAD

**Issue by hachi8833** [spf13/viper#159]
I've been trying to read a config JSON file from [go-bindata](https://github.com/jteeuwen/go-bindata), but still unsure how to do this.

Example: https://gist.github.com/hachi8833/e95073a2a4b41e5092ea

I'd be very glad if I can specify the config path to the go-bindata asset like `viper.ReadConfig(<path-to-asset-dir-in-bindata-file>)`.

Best regards,

**Comment by jnsone11** [comment]
I'm a bit late to the party but in case anyone comes across this problem...

viper.SetConfigFile("config.json")
	viper.AddConfigPath(".")

	memoryFileSystem := afero.NewMemMapFs()
	file,err := memoryFileSystem.Create("config.json")
	if err != nil {
		panic(err)
	}

	_,err = file.Write(config)
	if err != nil {
		panic(err)
	}

	viper.SetFs(memoryFileSystem)

	if err := viper.ReadInConfig(); err != nil {
		panic(err)
	}

**Comment by nileshpawar1** [comment]
I am getting undefined: config error for line   file.Write(config),  Do I miss anything? any idea?
