### ISSUE TITLE
Generate Man Page Content

### ISSUE THREAD

**Issue by uvulpos** [spf13/viper#1662]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

As a classic system administrator, I want to be able to see all commands given in a nice searchable way. There is already a charming help command, but I cannot search really through it easily and occasionally when I'm directly connected to a machine I cannot scroll that easily. Therefore, I really like man pages. 

### Proposed Solution

To generate man page content for linux machines and a function that can insert + update the current man page entry

**Comment by sagikazarmark** [comment]
I believe you meant to open this in cobra: https://github.com/spf13/cobra
