### ISSUE TITLE
Rewrite tests to use a local Viper instance

### ISSUE THREAD

**Issue by sagikazarmark** [spf13/viper#1700]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Most tests currently use the global Viper instance which causes all kinds of trouble between tests.

### Proposed Solution

Rewrite tests to initialize a new, local Viper instance.

**Comment by smukk9** [comment]
Hi @sagikazarmark ,

Thanks for your work. i have used viper recently and  would like to help with this. 

Are you referring to test like these https://github.com/spf13/viper/blob/5870123c5f385c8d88b7087d15d2e1b7fa67a7fa/viper_test.go#L677 .

any additional hints or pointers you can provide would be immensely helpful.

Thanks
