### ISSUE TITLE
Do a repository release

### ISSUE THREAD

**Issue by apremalal** [spf13/viper#173]
Go dependency management tools like Gom use a particular commitid/ tag to checkout the dependencies. Since this repo doesn't have a tag users have to stick to commitids, which is not clean and hard to track.

**Comment by onlyjob** [comment]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Versioning provides safety margin for situations like "ops, we've made a mistake but reverted problematic commit in master". Presumably tagged version/release is better tested/reviewed than random snapshot of "master" branch.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by YvanDaSilva** [comment]
Same goes for other tools like "GB" https://getgb.io
Without a proper tag (release), it is not possible to use the auto fetch property of gb and we have to vendor the entire Viper, which shouldn't be required.

https://getgb.io/docs/depfile/

Most other tools out there are already producing semver release, I don't see why this library shouldn't follow those footsteps.
Versioning also allows for build reproducibly.

**Comment by rv-rsouza** [comment]
This is a mandatory "feature" to allow version locking with dependency managers.
Please consider adding this, as it is easy to do and can be done with git command line or directly on GitHub.

Don't let this idea die!
Thanks for this awesome work. It just deserves a bit more attention.

**Comment by sulliwane** [comment]
With ```go dep``` arriving soon in every gopher's toolbox, a semver versioning for viper (git tag -a v1.0.0 -m 'v1.0.0') would be awsome!

**Comment by rv-rsouza** [comment]
Thank you VERY MUCH!!!! @bep
