### ISSUE TITLE
Deserialization exceptions

### ISSUE THREAD

**Issue by bystart** [spf13/viper#1745]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.16

### Go Version

1.21.1

### Config Source

Defaults

### Code reproducing the issue

```go
type ApplicationConfig struct {
	appName string `yaml:"appName"`
	Version string `yaml:"version"`
}
type DBConfig struct {
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	Username string `yaml:"username"`
	Password string `yaml:"password"`
}

type RedisConfig struct {
	Host string `yaml:"host"`
	Port int    `yaml:"port"`
}

type AppConfig struct {
	ApplicationConfig ApplicationConfig `yaml:"application"`
	DB                DBConfig          `yaml:"db"`
	Redis             RedisConfig       `yaml:"redis"`
}
--------------
```

### Expected Behavior

The ApplicationConfig field property cannot be serialized

### Actual Behavior

The ApplicationConfig field property cannot be serialized

### Additional Information

![image](https://github.com/spf13/viper/assets/38885210/2a013766-2321-4e7d-83af-205d2e7bb11b)

**Comment by bystart** [comment]
type ApplicationConfig struct {
	AppName string `yaml:"appName"`
	Version string `yaml:"version"`
}
type DBConfig struct {
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	Username string `yaml:"username"`
	Password string `yaml:"password"`
}

type RedisConfig struct {
	Host string `yaml:"host"`
	Port int    `yaml:"port"`
}

type AppConfig struct {
	ApplicationConfig ApplicationConfig `yaml:"application"`
	DB                DBConfig          `yaml:"db"`
	Redis             RedisConfig       `yaml:"redis"`
}

**Comment by sagikazarmark** [comment]
No idea how your other values get set, but my guess is they come from some defaults.

https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unmarshaling-doesnt-work

https://github.com/spf13/viper#unmarshaling
