### ISSUE TITLE
Improve usage instructions

### ISSUE THREAD

**Issue by ShanthkumarS079** [spf13/viper#176]
Tired installing viper with the below command
" **go get github.com/spf13/viper**"
It's not able to download all it's dependencies and it's child dependencies.

**Comment by on99** [comment]
@spf13 dependency management is needed for viper.

**Comment by bep** [comment]
@on99 no, a better README is needed for Viper.

**Comment by sagikazarmark** [comment]
There is both an extensive readme and go mod support now. Please open a new issue or discussion if you have ideas for improvements.
