### ISSUE TITLE
viper go.mod has dependency issues from 1.17.0

### ISSUE THREAD

**Issue by andy12593** [spf13/viper#1772]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [x] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.17.0

### Go Version

1.18

### Config Source

Files

### Format

TOML

### Expected Behavior

go run main.go success without error

### Actual Behavior

go run main.go error:   
The reason is that github.com/spf13/viper@v1.17.0 only requires go 1.18, but the dependency github.com/sagikazarmark/slog-shim v0.1.0 requires go 1.20
```
# golang.org/x/exp/slog
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/level.go:159:13: undefined: atomic.Int64
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/attr.go:20:19: undefined: StringValue
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/attr.go:68:19: undefined: GroupValue
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/handler.go:446:15: undefined: StringValue
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/json_handler.go:109:20: v.str undefined (type Value has no field or method str)
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/record.go:192:9: undefined: GroupValue
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/text_handler.go:99:20: v.str undefined (type Value has no field or method str)
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/value.go:87:7: undefined: stringptr
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/value.go:91:7: undefined: groupptr
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/value.go:173:10: undefined: StringValue
/home/oppo/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/slog/value.go:173:10: too many errors
note: module requires Go 1.20
```

### Steps To Reproduce

1. go get github.com/spf13/viper@v1.17.0
2. go mod tidy
3. go run main.go

**Comment by sagikazarmark** [comment]
As per the Go version support policy we support the last two Go versions. We may have forgotten to update the go.mod file.

**Comment by andy12593** [comment]
> As per the Go version support policy we support the last two Go versions. We may have forgotten to update the go.mod file.

Yes, the mod file after tag 1.7.0 should be updated from go 1.18 to 1.20. It is recommended to add tag 1.7.1 1.8.3 for this purpose.

**Comment by sagikazarmark** [comment]
Not sure how that would change anything. If a transitive dependency requires a higher Go version, that's virtually the same as Viper requiring it as well. I doubt Go would behave differently.

**Comment by sagikazarmark** [comment]
This should be fixed on the latest version.
