### ISSUE TITLE
Switch to more compliant TOML parser

### ISSUE THREAD

**Issue by spf13** [spf13/viper#179]
https://github.com/pelletier/go-toml

**Comment by bgrant0607** [comment]
@spf13 Is this something you're working on? Or would you be happy for someone else to pick it up?

Did you investigate any other TOML libraries, or are you happy with pelletier/go-toml?

cc @eparis @pwittrock

**Comment by spf13** [comment]
Please pick it up if you are inclined. I didn't investigate others yet, but
we totally should before switching.

**Comment by bgrant0607** [comment]
Ok, thanks. Here's another to check out:
https://github.com/naoina/toml

**Comment by bgrant0607** [comment]
https://github.com/naoina/toml was recommended to me

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by bep** [comment]
There are some breaking issues with Pelletier and Hugo. I haven't looked closely.

```
ERROR: 2016/08/05 11:19:23 site.go:1208: unable to process menus in site config
ERROR: 2016/08/05 11:19:23 site.go:1209: Unable to Cast map[string]interface {}{"pre":"<i class='fa fa-space-shuttle'></i>", "weight":-20, "url":"/commands/", "name":"Hugo Cmd Reference", "identifier":"commands"} of type map[string]interface {} to []interface{}
```
