### ISSUE TITLE
Extremely un-useful error message

### ISSUE THREAD

**Issue by greenenergy** [spf13/viper#180]
Apparently I have a problem in a config file. Viper allows you to specify a search path, and it will try various extensions.

The error I'm getting is this: Unsupported Config Type ""

This is a pretty frustrating error, since I don't know anything about the problem. What file was it trying to read? What sequence of search path entries did it go through? Did it find a file and not like it? Did it not find a file at all? I definitely have a config file (myconfig.toml), and it's in the path I specify, so what is the problem exactly?

If an error message doesn't give you any information allowing you to fix the problem, it's really not helpful.

**Comment by awishformore** [comment]
This has been fixed as part of #161
