### ISSUE TITLE
Viper go.mod have scan security violations for dependencies go.etcd.io/etcd/*

### ISSUE THREAD

**Issue by wangyongtao** [spf13/viper#1810]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Security-Low : 
go.etcd.io/etcd/api/v3 v3.5.10 
go.etcd.io/etcd/client/pkg/v3 v3.5.10 
go.etcd.io/etcd/client/v2 v2.305.10 
go.etcd.io/etcd/client/v3 v3.5.10 

### Proposed Solution

go.etcd.io/etcd/api/v3 v3.5.10             ---> Upgrade to v3.5.11
go.etcd.io/etcd/client/pkg/v3 v3.5.10  ---> Upgrade to v3.5.11
go.etcd.io/etcd/client/v2 v2.305.10     ---> Upgrade to v2.305.13
go.etcd.io/etcd/client/v3 v3.5.10         ---> Upgrade to v3.5.11

### Additional Information

no

**Comment by sagikazarmark** [comment]
I'll tag a new version in the next couple weeks

**Comment by sagikazarmark** [comment]
This should be fixed by v1.19.0
