### ISSUE TITLE
slog-shim has very low popularity

### ISSUE THREAD

**Issue by ns-jisorce** [spf13/viper#1896]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

https://github.com/sagikazarmark/slog-shim has very low popularity

### Proposed Solution

Consider removing the dependency on slog-shim

### Alternatives Considered

None

**Comment by ns-jisorce** [comment]
Hi gentle ping, thx!

**Comment by sagikazarmark** [comment]
Not sure why popularity matters over functionality. In any case, it's been removed from the latest alpha version, so it will be gone in the next release.
