### ISSUE TITLE
Is viper thread safe?

### ISSUE THREAD

**Issue by chmac** [spf13/viper#19]
I've been reading about how database layers and so on are bound to request contexts, and are thread safe. For example, gorilla/context uses sync mutex to ensure that only one thread can read / write to the context for a single request at any given time. I couldn't see anything like that on first glance at viper.

Is it safe to use viper with many simultaneous threads?

**Comment by kzvezdarov** [comment]
I'd strongly suggest to pass application configuration by value and use it as read only. Use some signalling mechanism when your config updates at runtime and propagate the changes the same way (basically sending copies of the config down to all consumers).
It saves you a lot of headaches - if you need mutable shared state, maybe that state should not be in the application configuration.
