### ISSUE TITLE
INI support through gcfg

### ISSUE THREAD

**Issue by tzz** [spf13/viper#194]
I'm interested in using https://godoc.org/gopkg.in/gcfg.v1 to support INI files in viper, eventually to resolve https://github.com/s3git/s3git/issues/15 and possibly others. It reads the key-value pairs into a two-level struct: https://godoc.org/gopkg.in/gcfg.v1#ex-ReadStringInto--Subsections

Could you guide me through the steps necessary to implement that new configuration file backend for Viper? I want to make sure I implement it in a way that's acceptable.

**Comment by sagikazarmark** [comment]
I've just merged a PR that adds INI support to Viper.
