### ISSUE TITLE
配置文件更新

### ISSUE THREAD

**Issue by lizt666888** [spf13/viper#1962]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.19

### Go Version

1.21

### Config Source

Files

### Format

YAML, TOML

### Code reproducing the issue

```go
v := viper.New()
	v.SetConfigFile(config)
	v.SetConfigType("yaml")
	err := v.ReadInConfig()
	if err != nil {
		panic(fmt.Errorf("Fatal error config file: %s \n", err))
	}
	v.WatchConfig()

	v.OnConfigChange(func(e fsnotify.Event) {
		fmt.Println("config file changed:", e.Name)
		if err = v.Unmarshal(&global.VUA_CONFIG); err != nil {
			fmt.Println(err)
		}
	})
	if err = v.Unmarshal(&global.VUA_CONFIG); err != nil {
		fmt.Println(err)
	}
```

### Expected Behavior

share_disk:
  - area: 4061
    addr: 10.74.67.4
  - area: 4062
    addr: 10.74.67.5

将 数组配置删除一项  不会更新

### Actual Behavior

share_disk:
  - area: 4061
    addr: 10.74.67.4

去掉一个 但是程序里不会减少该数组item

### Steps To Reproduce

删其中一个数组的元素

**Comment by sagikazarmark** [comment]
Please submit bug reports in English with a way to reproduce it (complete snippet, config file)

**Comment by lizt666888** [comment]
> Please submit bug reports in English with a way to reproduce it (complete snippet, config file)

func Viper(path ...string) *viper.Viper {
	var config string

	if len(path) == 0 {
		flag.StringVar(&config, "c", "", "choose config file.")
		flag.Parse()
		if config == "" { // 判断命令行参数是否为空
			if configEnv := os.Getenv(internal.ConfigEnv); configEnv == "" { // 判断 internal.ConfigEnv 常量存储的环境变量是否为空
				switch gin.Mode() {
				case gin.DebugMode:
					config = internal.ConfigDefaultFile
					fmt.Printf("您正在使用gin模式的%s环境名称,config的路径为%s\n", gin.EnvGinMode, internal.ConfigDefaultFile)
				case gin.ReleaseMode:
					config = internal.ConfigReleaseFile
					fmt.Printf("您正在使用gin模式的%s环境名称,config的路径为%s\n", gin.EnvGinMode, internal.ConfigReleaseFile)
				case gin.TestMode:
					config = internal.ConfigTestFile
					fmt.Printf("您正在使用gin模式的%s环境名称,config的路径为%s\n", gin.EnvGinMode, internal.ConfigTestFile)
				}
			} else { // internal.ConfigEnv 常量存储的环境变量不为空 将值赋值于config
				config = configEnv
				fmt.Printf("您正在使用%s环境变量,config的路径为%s\n", internal.ConfigEnv, config)
			}
		} else { // 命令行参数不为空 将值赋值于config
			fmt.Printf("您正在使用命令行的-c参数传递的值,config的路径为%s\n", config)
		}
	} else { // 函数传递的可变参数的第一个值赋值于config
		config = path[0]
		fmt.Printf("您正在使用func Viper()传递的值,config的路径为%s\n", config)
	}

	v := viper.New()
	v.SetConfigFile(config)
	v.SetConfigType("yaml")
	err := v.ReadInConfig()
	if err != nil {
		panic(fmt.Errorf("Fatal error config file: %s \n", err))
	}
	v.WatchConfig()

	v.OnConfigChange(func(e fsnotify.Event) {
		fmt.Println("config file changed:", e.Name)
		if err = v.Unmarshal(&global.VUA_CONFIG); err != nil {
			fmt.Println(err)
		}
	})
	if err = v.Unmarshal(&global.VUA_CONFIG); err != nil {
		fmt.Println(err)
	}
     return v
}

step：
1、config.yaml
share_disk:
  - area: 4061
    addr: 10.74.67.4
  - area: 4062
    addr: 10.74.67.5

2、The configuration read out is ：
share_disk:
  - area: 4061
    addr: 10.74.67.4
  - area: 4062
    addr: 10.74.67.5

3、Then modify the configuration file to
config.yaml
share_disk:
  - area: 4061
    addr: 10.74.67.4

4、The configuration read out is ： Still the result of the second step

final result：The configuration has reduced one element but there is no hot update configuration
