### ISSUE TITLE
etcd/crypt not working

### ISSUE THREAD

**Issue by jdoklovic** [spf13/viper#197]
I'm trying to use an encrypted config from etcd but it always fails with the error: "Remote Configurations Error: No Files Found"

I'm doing :

``` go
viper.AddSecureRemoteProvider("etcd",etcdHost,etcdPath,"/etc/secrets/crypt.gpg")
viper.SetConfigType("json")
err = viper.ReadRemoteConfig()
```

FYI, etcdPath = /mypath/myconfig.json

I've also tested that the etcdhost is reachable and if i call http://<etcdHost>/v2/keys<etcdPath> via the net/http client, I get back the proper json entry for the config.

I've also tested that my code can read the gpg key.

Finally, I tried taking the filename out of the etcdPath and setting it using viper.SetConfigName("myconfig.json")

Am I missing something??

**Comment by rbastic** [comment]
Hi,

Did you ever figure this out?

Thanks,

**Comment by noprom** [comment]
same problem here.

**Comment by yury-kozlov** [comment]
I got the same error but with another api: 
```viper.AddRemoteProvider("consul", "localhost:8500", "my-key")```
The problem solved after I manually defined an empty json string "{}" under this consul key: 
```localhost:8500/ui/dc1/kv/my-key```

**Comment by sagikazarmark** [comment]
Please open a new issue with more details if this is still a problem.
