### ISSUE TITLE
Can I tell `viper.Unmarshal` to take environment variables into account?

### ISSUE THREAD

**Issue by arekkas** [spf13/viper#212]
This is my viper config:

```go
	if cfgFile != "" {
		// enable ability to specify config file via flag
		viper.SetConfigFile(cfgFile)
	}

	path := absPathify("$HOME")
	if _, err := os.Stat(filepath.Join(path, ".hydra.yml")); err != nil {
		_, _ = os.Create(filepath.Join(path, ".hydra.yml"))
	}

	viper.SetConfigType("yaml")
	viper.SetConfigName(".hydra") // name of config file (without extension)
	viper.AddConfigPath("$HOME")  // adding home directory as first search path
	viper.AutomaticEnv()          // read in environment variables that match

	// If a config file is found, read it in.
	if err := viper.ReadInConfig(); err != nil {
		fmt.Printf(`Config file not found because "%s"`, err)
		fmt.Println("")
	}
```

I also have a bunch of environment varibales, like `CLIENT_ID` or `DATABASE_URL`. Right now I'm setting those via:

```go
	if databaseURL, ok := viper.Get("DATABASE_URL").(string); ok {
		c.DatabaseURL = databaseURL
	}
```

Is it possible to tell `viper.Unmarshal` to use the environment variables in addition to the config file?

**Comment by arekkas** [comment]
yes, i need to use `BindEnv` and write the keys upper case in `mapstructure:...`

**Comment by postcert** [comment]
I was able to get it working without `BindEnv` or setting the mapstructure tags uppercase.
Though I am calling `ReadInConfig` prior to `AutomaticEnv`. Then after unmarshaling into the config struct of course.

**Comment by arekkas** [comment]
That worked for me too!

**Comment by Ehekatl** [comment]
@postcert did't get it work here, can u give some sample code ? many thx

**Comment by Ehekatl** [comment]
I found that unmarshal env variable only work when the key is also in config file...not sure if this is bug

**Comment by postcert** [comment]
Yes, it only works when present in the config file.

**Comment by astoliarov** [comment]
Hi! Is it working?

**Comment by sagikazarmark** [comment]
Please see and follow the issue above. ☝️

**Comment by 89z** [comment]
https://github.com/spf13/viper/issues/140
https://github.com/spf13/viper/issues/188

https://github.com/spf13/viper/issues/212
https://github.com/spf13/viper/issues/522
https://github.com/spf13/viper/issues/576
https://github.com/spf13/viper/issues/761
https://github.com/spf13/viper/issues/911
