### ISSUE TITLE
Fix TOML vs Hugo

### ISSUE THREAD

**Issue by bep** [spf13/viper#225]
See:

https://github.com/spf13/viper/pull/217

Better to keep the discussion in an open issue.

**Comment by vladimirvivien** [comment]
@bep thanks.

**Comment by vladimirvivien** [comment]
@bep I have submitted PR https://github.com/pelletier/go-toml/pull/84 to go-toml to fix the issue with toml and Hugo.  I have tested locally with my hugo branch and it works.  Can you tell me what exact `hugo` command you did so I can retest that as well.  Thank you.

**Comment by akutz** [comment]
Thanks @vladimirvivien. The Hugo validation (#222) has been submitted as a PR in #229.
