### ISSUE TITLE
viper doesn't set the value of bound pflag

### ISSUE THREAD

**Issue by vikstrous** [spf13/viper#236]
Example:
```
package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

func main() {
	fval := 0
	pflag.IntVar(&fval, "port", 0, "")
	viper.BindPFlag("port", pflag.Lookup("port"))
	viper.AutomaticEnv()
	os.Setenv("PORT", "13")
	port := viper.Get("port")
	fmt.Println(port)
	fmt.Println(fval)
}
```

Actual output:
```
13
0
```

Expected output:
```
13
13
```

Is there some method I can call on Viper to set the underlying flags? It seems like if you want to use viper, you are forced to wrap all variable accesses in functions if you want to do them in a type safe way. I'm trying to use pflag/Cobra's ability to bind to typed variables, but it seems like that doesn't work with viper.

**Comment by vikstrous** [comment]
It looks like I misunderstood how viper/cobra are supposed to interact. Cobra is just another way to set configs in viper, not the over way around.

**Comment by wxf4150** [comment]
when pflag is defualtValue, we can change  the value from viper(if it  exists in viper).
```
	pflag.VisitAll(func(flg *pflag.Flag){
		if flg.Changed{return}
		viperValue:=viper.Get(flg.Name)
		if viperValue!=nil{
			//github.com/spf13/cast
			strValue,err1:=cast.ToStringE(viperValue)
			if err1==nil{
				err1=pflag.Set(flg.Name,strValue)
				if err1==nil{
					log.Printf("set pflag %s from viper",flg.Name)
				}else{
					log.Printf("err set pflag %s from viper err: %s",flg.Name,err1)
				}
				//flg.Value.Set(viperValue.(string))
			}else{
				log.Printf("%s cast.ToStringE err %s",flg.Name,err1)
			}
		}
	})

	viper.BindPFlags(pflag.CommandLine)
```
