### ISSUE TITLE
error on handle corba StringArray flag

### ISSUE THREAD

**Issue by vvhh2002** [spf13/viper#246]
I got an error while handle cobra StringArray flag. I think this may be a BUG

``` go
flags.StringArrayP("URLS", "U", []string{"http://github.com", "http://github.com"}, "test URLS")
viper.BindPFlag("URLS", flags.Lookup("URLS"))
Result:=viper.GetStringSlice("URLS")
```

Result is only one element=> 

`Result=[[http://github.com,http://github.com]]`
It should be `[http://github.com http://github.com]`

**Comment by praveenkumar** [comment]
@vvhh2002  I am also facing same, Are you able to find workaround or solution for this?

**Comment by databus23** [comment]
I think https://github.com/spf13/viper/pull/398 should fix this.
