### ISSUE TITLE
Unmarshal into iterable map and preserve order

### ISSUE THREAD

**Issue by VoR0220** [spf13/viper#274]
I currently want to do something but am not sure if it's possible, but would like to know if it is possible to do in this instance. Suppose I have a map to a struct such as:

```
Foo map[string]someStruct `mapstructure:"foo"`

type someStruct struct {
     myInt int `mapstructure:"bar"`
}
```

Is it possible to unmarshal in such a way that I can preserve a FIFO order for my map and then iterate through the map? I figure I may as well ask, and if it's not possible, is this feature possible?

**Comment by skipor** [comment]
It's impossible. 
Quote from [Go maps in action](https://blog.golang.org/go-maps-in-action)
> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since Go 1 the runtime randomizes map iteration order, as programmers relied on the stable iteration order of the previous implementation. If you require a stable iteration order you must maintain a separate data structure that specifies that order. 

If order is important, use array of key-value pairs instead of map.

**Comment by VoR0220** [comment]
thanks
