### ISSUE TITLE
viper is a unexported struct. Use New().

### ISSUE THREAD

**Issue by kgv** [spf13/viper#29]
```
// A viper is a unexported struct. Use New() to create a new instance of viper
// or use the functions for a "global instance"
```
OK, i use New() for create a new instance of viper, but then how can I send created viper to another my package (viper is not export)? I can create an interface, that is equal to viper interface. But i think would be better if viper provide exported Viper interface or exported Viper struct for use it interface.

**Comment by zyndiecate** [comment]
Stumbled upon the same problem. +1 for exporting `viper` or a related interface.

**Comment by spf13** [comment]
@zyndiecate, @micahwedemeyer Do either of you want to send a PR with the public interface?

**Comment by zyndiecate** [comment]
Would the changes of https://github.com/giantswarm/viper/pull/1 be sufficient?

**Comment by Eloff** [comment]
Can we get this merged? I just bumped my head on this one too.

**Comment by Eloff** [comment]
I think just exporting viper as Viper, per zyndiecate's fix is ok, because I can't imagine having another implementation of a "Viperer"

**Comment by kzvezdarov** [comment]
#45 resolves this, closing as fixed.
