### ISSUE TITLE
Add support for exporting the viper struct in JSON/ YAML/ etc.

### ISSUE THREAD

**Issue by goarchit** [spf13/viper#297]
Please consider adding an export function that takes the final structure, after flags, environment, etc. are processed, and places it into a file that could later be read back in as a configure file the next time the program is executed.

I am NOT asking to overwrite the passed config file, simply allow me to export into something that is compatible.

For reasons that are not obvious to me, this code snippet doesn't do what I expected it to do (e.g. return a nicely formatted JSON string):

func PrintJSON()  {
        b, err := json.MarshalIndent(viper.GetViper(),"","    ")
        if err != nil {
                fmt.Println(err)
        }
        fmt.Println("Viper: :",viper.GetViper())
        fmt.Println("JSON: ",b)
        return
}

Running a test case of the above gives:

Viper: : &{. [/etc/archit /home/kevinc/.archit /home/kevinc/src/github.com/goarchit/archit] 0x9d2e60 [] config  json ArchIt true <nil> map[] map[] map[port:1958 publicip:localhost logfile:Archit.log loglevel:3] map[] map[port:{0xc420011680} publicip:{0xc420011720} logfile:{0xc4200117c0} loglevel:{0xc420011860}] map[] map[] false <nil>}
JSON:  [123 125]

If I'm doing something stupid (quite likely), please just tell me what and close this request.

Thanks in advance

**Comment by bep** [comment]
https://github.com/spf13/viper/pull/287
