### ISSUE TITLE
Configuration precedence.

### ISSUE THREAD

**Issue by amosbird** [spf13/viper#298]
I'd like to achieve this priority,
`manually passed flag value` `>` `config file's value` `>` `default flag value`.
Is it possible in current `viper`?

**Comment by orian** [comment]
Read "precedence order" at https://github.com/spf13/viper#why-viper

**Comment by amosbird** [comment]
@orian Ok. Do you mean there is no way to apply such precedence order above in `viper`?

**Comment by orian** [comment]
@amosbird you cannot modify the way viper gets value (precedence order). The `default` described in the doc I've mentioned above is actually a default value of unchanged flag.

The code:
https://github.com/orian/viper/blob/61c45d73da9eb53ed6be3b3eacf00d1bdf8d8f76/viper.go#L846

**Comment by amosbird** [comment]
cool, thanks.

**Comment by gzq0616** [comment]
How to make remote key/value store take precedence over config file's value？
