### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by facundomedica** [spf13/viper#311]
I've been reading a bit through the code and found that Viper searches in several places for each time that Get() is called. Can this be an issue if I call it many times? I'm building an API and I call a lot `viper.GetString("database")` and a couple other from different parts of my code (It gets called like 4 times per request). Could this create a performance issue? 

How I initialize Viper:
```go
func initConfig() {
	viper.SetConfigType("json")
	viper.SetConfigName("config") 
	viper.AddConfigPath(".")      
	err := viper.ReadInConfig() 
	if err != nil {               
		panic(fmt.Errorf("Fatal error config file: %s \n", err))
	}
}
```

**Comment by bep** [comment]
> Could this create a performance issue?

Yes.

I had some surprises doing some profiling/benchmarks on this in Hugo some times ago -- we used viper.Get in some "hot paths" in the build code. I fixed some obvious issues in Viper, but I would still recommend that you read the configuration "once at startup" (or something) and read from local fields, if possible.

**Comment by facundomedica** [comment]
@bep thanks for your answer, I will look for an alternative (but if you have something to share it would be really nice).

**Comment by bep** [comment]
> I will look for an alternative 

You don't need an alternative to Viper, you just need to read the config into a `Config` struct of some kind -- then read from that whenever you need it.

**Comment by meetsubhojit** [comment]
> You don't need an alternative to Viper, you just need to read the config into a `Config` struct of some kind -- then read from that whenever you need it.

but that defeats the purpose of using viper. Viper.Get("some_config") would give us the latest config. If we do it via a struct, it would mean we need to handle config `on change` events in the code which gets ugly.
