### ISSUE TITLE
Memory Leak Remote-Watch Consul?

### ISSUE THREAD

**Issue by wofr** [spf13/viper#312]
I'm using Viper to watch some values on Consul (like it is described in your sample see blow)

```
// open a goroutine to watch remote changes forever`
go func(){
    for {
        time.Sleep(time.Second * 5) // delay after each request

        // currently, only tested with etcd support
        err := runtime_viper.WatchRemoteConfig()
        if err != nil {
            log.Errorf("unable to read remote config: %v", err)
            continue
        }

       // unmarshal new config into our runtime config struct. you can also use channel
        // to implement a signal to notify the system of the changes
        runtime_viper.Unmarshal(&runtime_conf)
    }
}()
```

While doing this I observed that amount of go-function increases very fast.  The problem seems to be in the _Watch_ function in the _RemoteProvider_ (see below).  cm.Watch(rp.Path(), nil) creates a go function but without providing (and calling) the cancel channel. Thats why the created go function never stops! 
Thats why with every `runtime_viper.WatchRemoteConfig()` call a new function is created which is not stopped

```
func (rc remoteConfigProvider) Watch(rp viper.RemoteProvider) (io.Reader, error) {
	cm, err := getConfigManager(rp)
	if err != nil {
	    return nil, err
	}`
	resp := <-cm.Watch(rp.Path(), nil)
	err = resp.Error
	if err != nil {
		return nil, err
	}

	return bytes.NewReader(resp.Value), nil
}
```

Regards

Wolfgang

**Comment by wofr** [comment]
Moreover the used lib to access consul (https://github.com/xordataexchange/crypt) is used in a way that also with every call a new go-function is called which never quits, due to the quite-channel is not even observed there.

**Comment by wofr** [comment]
I guess the issue could also be solved by calling runtime_viper.WatchRemoteConfig only once outside the for loop in the go function. 
This should do the trick, but I need to verify this first.

```
go func(){
   err := runtime_viper.WatchRemoteConfig()
   if err != nil {
         log.Errorf("unable to read remote config: %v", err)
         return
    }
    for {
        time.Sleep(time.Second * 5) // delay after each request
        // currently, only tested with etcd support
     
        // unmarshal new config into our runtime config struct. you can also use channel
        // to implement a signal to notify the system of the changes
        runtime_viper.Unmarshal(&runtime_conf)
    }
}()
```

**Comment by wofr** [comment]
Locally I've fixed the issue now.
I changed the implementaiton of the Watch function in the RemoteConfig Providerr. I now call Get rather then Watch on the ConfigManager. This woul prevent that not used go-routines are started.
```
func (rc remoteConfigProvider) Watch(rp viper.RemoteProvider) (io.Reader, error) {
	cm, err := getConfigManager(rp)
	if err != nil {
		return nil, err
	}
	resp,err := cm.Get(rp.Path())
	if err != nil {
		return nil, err
	}

	return bytes.NewReader(resp), nil
}
```
With this fix nothing else needed to be changed.

**Comment by wofr** [comment]
Additionally I also implemented a more sophisticated remote-watch, but I guess with this solution the thread-safety of the v.keyvalue map could not be guaranteed without taking further action.  

With this solution you only must call the WatchRemoteConfigOnChannel  function once outside the for loop.  Inside the loop only the valued needed to be validated.   The WatchRemoteConfigOnChannel function internally starts a go function which is waiting for changes.  The solution can be found here (https://github.com/wofr/viper).  I’ve not created a push-request due to thread-safety I could not ensure

```
go func(){
   err := runtime_viper.WatchRemoteConfigOnChannel ()
   if err != nil {
         log.Errorf("unable to read remote config: %v", err)
         return
    }
    for {
        time.Sleep(time.Second * 5) // delay after each request
        
     
        // unmarshal new config into our runtime config struct. you can also use channel
        // to implement a signal to notify the system of the changes
        runtime_viper.Unmarshal(&runtime_conf)
    }
}()
```

**Comment by bep** [comment]
@wofr is this solved?

**Comment by wofr** [comment]
yes with the merge of the PR #321 it is.

**Comment by lucifercha** [comment]
@wofr how to use channel to implement a signal to notify the system of the changes，the RemoteResponse channel is not public for user.
