### ISSUE TITLE
Allow EmptyStrings to read from Environmental Variables

### ISSUE THREAD

**Issue by plamenGo** [spf13/viper#317]
The code below inside the find(key string) function in viper.go, makes it so that if an env var is set to "", the default value is used instead. I have a use case where I need the default to be overridden with empty string from the environment. Any chance this will get implemented in this way?

 envkey, exists := v.env[key]
  if exists {
    jww.TRACE.Println(key, "registered as env var", envkey)
    if val = v.getEnv(envkey); val != "" {
      jww.TRACE.Println(envkey, "found in environment with val:", val)
      return val

**Comment by sagikazarmark** [comment]
See #429 for a solution

**Comment by b1v1r** [comment]
Can we get #440 reviewed and merged to resolve this?
