### ISSUE TITLE
undefined: mapstructure.StringToTimeDurationHookFunc

### ISSUE THREAD

**Issue by Maniacal** [spf13/viper#322]
Couldn't figure out which repo to create this on.  Hopefully I got it right:
```
± go get github.com/spf13/cobra/cobra
# github.com/spf13/viper
../../../../spf13/viper/viper.go:747: undefined: mapstructure.StringToTimeDurationHookFunc
```
go version go1.8 darwin/amd64

**Comment by bep** [comment]
You have a "stale Go path", i.e. something old or missing.

You may try 

```
go get -u -v -f github.com/spf13/cobra/cobra
```

... or something.

**Comment by Maniacal** [comment]
I had an old mapstructure that wasn't updating.  Thanks.
