### ISSUE TITLE
toml and sections

### ISSUE THREAD

**Issue by krzysztofantczak** [spf13/viper#34]
Hi,

Let say, we have TOML file like:
```
[foo]
bar = "baz"

[bam]
bip = "bop"
```

Is there any way to get foo.bar value directly like viper.Get("foo.bar")? And another question, how can i set defaults for this kind of vars (from toml with sections) so they can be overrided later?

**Comment by shilov** [comment]
I have to admit that was one of the first things I tried as well, then realized I might have to go read the documentation after all :)

Kidding aside, since the syntax is supported by some of the other Go toml implementations, I'd be curious to know if viper doesn't allow it due to non-trivial reasons.

**Comment by tonyhb** [comment]
Yeah, that would be awesome. It would be good to perhaps use underscores so that we could mix env variable overrides:

```toml
[db]
host = ""
user = "user"
```

Then:

```go
viper.AutomaticEnv()
os.SetEnv("db_host", "localhost")

viper.GetString("db_host") // returns ENV override
viper.GetString("db_user") // returns TOML configuration
```

**Comment by shilov** [comment]
I've switched to using [confer](github.com/jacobstr/confer) which is a fork of viper. It does exactly what is described above.

**Comment by pravj** [comment]
@shilov, You have written a wrong URL there(^) my friend. You meant [jacobstr/confer](https://github.com/jacobstr/confer), probably.

**Comment by shilov** [comment]
Thanks @pravj, fixed it

**Comment by kzvezdarov** [comment]
Mind of I close the issue? `Viper` is getting support for this in #54, implementation discussion would be more useful there.

**Comment by shilov** [comment]
I have no objections, looking forward to seeing this implemented. Thanks @kzvezdarov
