### ISSUE TITLE
Unmarshal vs. Marshal

### ISSUE THREAD

**Issue by bradobro** [spf13/viper#36]
Hey spf13, we love your package.

Seems to me you use "Marshal" to mean what most libraries I've used call "Unmarshal".  (Compare with the [Go JSON package](https://golang.org/pkg/encoding/json/#Marshal).

What's your thinking on this?

**Comment by spf13** [comment]
I probably got it wrong. Whatever the Go JSON does is right. It's probably best to fix this now, even though it's a breaking change.

**Comment by spf13** [comment]
@bradobro Care to make a PR?

**Comment by bradobro** [comment]
Thanks for asking @spf13. I've got a heavy couple weeks here with my head in a different language. I'm very interested, but not sure if I'll get to it soon. @trenton42 might be interested too.

**Comment by trenton42** [comment]
I can certainly write a PR, I just want to make sure that we don't confuse anyone that is already using this.

**Comment by bradobro** [comment]
Yeah, tough call.

**Comment by SunSparc** [comment]
Perhaps make a duplicate function and call it Unmarshal. Then deprecate the Marshal function. Thus they will both be available, but going forward, people can use the one that is named correctly.
