### ISSUE TITLE
Why not make pflagValueSet and pflagValue public?

### ISSUE THREAD

**Issue by dopey** [spf13/viper#366]
I am a novice to using viper so please take with a grain of salt.

My first project required me to create a FlagSet in which not all of the flags would be bound to a viper instance. I found that I could use `.VisitAll` to iterate over my flags and selectively bind only those that I required. However, the `BindFlagValue` method requires a `viper.FlagValue` meaning that I had to convert my `pflag.Flag(s)` to `viper.FlagValue(s)`.  The viper code base already contains structs that allow the code to make this conversion internally. Why not make them accessible outside the package? I copy-pasted  `flags.go` into my own package to get my implementation working.

This is probably not that common of a use case, but it seems to me like it could be useful.

p.s. I could also have solved this by having different FlagSet(s) but this presented its own slew of problems which I will not go into here :)

**Comment by sagikazarmark** [comment]
They are not part of the public API, but internal implementations of the FlagValue interface.
