### ISSUE TITLE
Setting environment variable for header in toml overwrites all the values under that block.

### ISSUE THREAD

**Issue by skyrocknroll** [spf13/viper#367]
config file `app.toml`
```
[COMPANY_PROFILE_SERVICE]
SERVER_PORT=10004
```
If i have set an environment variable with COMPANY_PROFILE_SERVICE=1234 then 
The value i get for  COMPANY_PROFILE_SERVICE_SERVER_PORT is empty (This is the bug). 
if i unset COMPANY_PROFILE_SERVICE in the environment then i get value correct value from app.toml file i.e 10004

**Comment by Amirutha** [comment]
There is a method called isPathShadowedInAutoEnv in viper.go, which necessarily makes this check
#
`// isPathShadowedInAutoEnv makes sure the given path is not shadowed somewhere
// in the environment, when automatic env is on.
// e.g., if "foo.bar" has a value in the environment, it “shadows”
//       "foo.bar.baz" in a lower-priority map
func (v *Viper) isPathShadowedInAutoEnv(path []string) string {....}`
