### ISSUE TITLE
Flag does not have higher priority than default.

### ISSUE THREAD

**Issue by docktermj** [spf13/viper#369]
According to https://github.com/spf13/viper/blob/c1de95864d73a5465492829d7cb2dd422b19ac96/viper.go#L104, a flag should have higher priority than the default.   

However, as illustrated in https://play.golang.org/p/9md7nG2lBl  (which doesn't actually run in the Go playground, so you'll have to run locally),  the default value has higher priority than a flag.

**Comment by docktermj** [comment]
Improved example of the issue:

```go
package main

import (
	"fmt"
	"github.com/spf13/viper"
)

// ----------------------------------------------------------------------------
// Interface object for viper.BindFlagValue(...)
// ----------------------------------------------------------------------------

type myFlag struct {
	MyName string
	Value  string
	Type   string
}

func (f myFlag) HasChanged() bool    { return false }
func (f myFlag) Name() string        { return f.MyName }
func (f myFlag) ValueString() string { return f.Value }
func (f myFlag) ValueType() string   { return f.Type }

// ----------------------------------------------------------------------------
// Example of issue.
// ----------------------------------------------------------------------------

func main() {

	// Works
	key1 := "Key-1"	
	viper.BindFlagValue(key1, myFlag{MyName: key1, Value: "From BindFlagValue()", Type: "string"})
	fmt.Println(viper.GetString(key1))

	// Fails:  The flag should have precedence over the default.
	key2 := "Key-2"	
	viper.SetDefault(key2, "From SetDefault()")
	viper.BindFlagValue(key2, myFlag{MyName: key2, Value: "From BindFlagValue()", Type: "string"})
	fmt.Println(viper.GetString(key2))
}
```

**Comment by docktermj** [comment]
Been a couple of years.  Any news?

**Comment by peter-mogensen** [comment]
As I understand it the intended behavior is to only have flags override anything if their value has changed* from the flag-default.

And you have explicitly implemented your flag to say that's never the case.

*: More specifically I think the "changed" is supposed to mean whether the flag was explicitly given.  - so giving the flag with the default value would also make it override.

**Comment by sagikazarmark** [comment]
That is correct. The changed parameter is used to decide whether the flag value should be used, so it works as intended.
