### ISSUE TITLE
struct yaml tags are not respected

### ISSUE THREAD

**Issue by deltaskelta** [spf13/viper#385]
`gopkg.in` will treat yaml tags properly, but something is happening in `viper` that ignores them. Given the following main and config file, it will fail to read in the proper yaml keys...

main.go
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/pkg/errors"
	"github.com/spf13/viper"
)

type Config struct {
	Foo string `yaml:"foo-thing"`
	Bar string `yaml:"bar-thing"`
}

var Conf Config

func main() {
	initConfig()
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	viper.SetConfigName(".conf") // name of config file (without extension)
	// add working dir path above the home dir for the config file
	path, _ := os.Getwd()
	viper.AddConfigPath(path)
	viper.AutomaticEnv() // read in environment variables that match

	// If a config file is found, read it in.
	err := viper.ReadInConfig()
	switch {
	case err != nil:
		log.Println(err)
	default:
		fmt.Println("Using config file:", viper.ConfigFileUsed())
	}

	err = viper.Unmarshal(&Conf)
	if err != nil {
		log.Println(errors.Wrap(err, "unmarshal config file"))
	}

	log.Println(Conf)
}
```

.conf
```yaml
---
foo-thing: why
bar-thing: nowork?
```

**Comment by nikhotine** [comment]
Incase you are still stuck with this:

`viper` uses [mapstructure](https://github.com/mitchellh/mapstructure) package for unmarshalling config maps to structs. It doesn't support `yaml` tags used by the `yaml` package.

So, changing all your `yaml:` tags in your struct to `mapstructure:` should fix this.

**Comment by deltaskelta** [comment]
Oh cool thanks I will try it in the future

**Comment by octalmage** [comment]
This worked for me!

**Comment by hxzhao527** [comment]
Why not dynamicly according to `config.SetConfigType("yaml")`?

**Comment by HammerMax** [comment]
worked for me too!!!!

**Comment by cyberbeast** [comment]
The inverse is still broken though. Even after using `microstructure:...`, when using `viper.WriteConfig()`, the struct tags are not being respected and the output file contains the key and not the `tag` from which it is reading the properties from.

**Comment by zoulux** [comment]
```go
func (c *config) Scan(v interface{}) error {
	return c.viper.Unmarshal(&v, viper.DecoderConfigOption(func(decoderConfig *mapstructure.DecoderConfig) {
		decoderConfig.TagName = "yaml"
	}))
}
```

**Comment by arcosx** [comment]
> ```go
> func (c *config) Scan(v interface{}) error {
> 	return c.viper.Unmarshal(&v, viper.DecoderConfigOption(func(decoderConfig *mapstructure.DecoderConfig) {
> 		decoderConfig.TagName = "yaml"
> 	}))
> }
> ```

it works for me.
