### ISSUE TITLE
Query: Regarding config change

### ISSUE THREAD

**Issue by vishal24tuniki** [spf13/viper#392]
Is there any function that would tell me that value of specific key has changed ?
Right now i am clear that viper can tell if a config file has changed by using WatchConfig method

Use case:
I would like to reload my connections to databases (redis/ mongo/ kafka etc) when i know the values of those keys have changed.

**Comment by vishal24tuniki** [comment]
@bep pls help

**Comment by sagikazarmark** [comment]
See WatchConfig
