### ISSUE TITLE
toml unmarshal does not work

### ISSUE THREAD

**Issue by stephencheng** [spf13/viper#394]
not sure if it's just me, it does not work for me to unmarshal a toml file or part of it.

for example:

The toml file:
> [np]
base ="abc.com.au"
password="abc434"

>[pr]
base = "abc.com"
password = "abcd9876"

use the code:
	
```
type Config struct {
	base     string
	password string
}


        viper.AddConfigPath("./") // set the path of your config file
	viper.SetConfigType("toml")
	viper.SetConfigName("config")
	err := viper.ReadInConfig()

	if err != nil {
		fmt.Println("Config file not found...%s", err)
	} else {
         	p := fmt.Println
		var cfg Config
		prod := viper.Sub("pr")
		err := prod.Unmarshal(&cfg)  # not work
		// err := viper.UnmarshalKey("pr", &cfg) #not work
	
		if err != nil {
			p("unable to decode into struct, %v", err)
		}

		p(cfg.base)
		p(cfg.password)

	}


```
Note, none of Unmarshal or UnmarshalKey worked.

However if it's a yml file, it will work.

I have spent a day on this but can't quite figure it out. Any one could share your idea?

**Comment by barum** [comment]
you can try this code also

func main() {

	fmt.Printf("version is [%s]\n", version)
	fmt.Printf("config file name is [%s]\n", configfilename)
	viper.SetConfigName("app1config")
	viper.AddConfigPath(".")

       // Read the config file
	if err := viper.ReadInConfig(); err != nil {
		log.Fatalf("Error reading config file, %s", err)
	}
 // set the subsection
	section := viper.Sub("personal")

	var ConfigStruct app1config.Config
// give it the stuct 
	err := section.Unmarshal(&ConfigStruct)
	if err != nil {
		log.Fatalf("unable to decode into struct, %v", err)
	}
	fmt.Printf("host [%s]\n", ConfigStruct.Host)
	fmt.Printf("Port [%d]\n", ConfigStruct.Port)
	fmt.Printf("Enabled [%t]", ConfigStruct.Enabled)
}

**Comment by stephencheng** [comment]
Thanks, all sorted out.

**Comment by vishnutm** [comment]
could you plz share the code.  bcz I am stuck it
