### ISSUE TITLE
Multiple OnConfigChange registration

### ISSUE THREAD

**Issue by cemremengu** [spf13/viper#408]
OnConfigChange registers multiple times. Here is the way I use configuration:

```
var Config &Configuration{}

func readLocal(fileName string) {
	viper.AddConfigPath(".")
	viper.SetConfigName(fileName)
	err := viper.ReadInConfig()

	if err != nil {
		log.Fatalf("Cannot find the config file!")
	}
	if viper.Unmarshal(Config) != nil {
		log.Fatalf("Unable to read the config file!")
	}

	log.Printf("Using config %+v\n", Config)

	viper.WatchConfig()
	viper.OnConfigChange(func(e fsnotify.Event) {
		log.Printf("Updated config %+v\n", e.Name) // this gets printed multiple times
	})
}

func main() {
	readLocal("config")
}

```

When I change the config file I get multiple (two to be exact) logs in stdout? I dont remember this happening before. This began after I switched to master branch from version 1.0,0.

Is this a bug, feature or a mistake on my side?

**Comment by cemremengu** [comment]
Also happens on `1.0.0` as well. Not sure what I am missing :(

**Comment by halturin** [comment]
confirm this behavior. got double call on file change.  
revision = "2c12c60302a5a0e62ee102ca9bc996277c2f64f5"

**Comment by insomniacslk** [comment]
@spf13 any chance to work on this bug? It seems to be still a thing. If you don't have time to investigate yourself, would you have time to review a PR instead?

**Comment by reefbarman** [comment]
I can confirm I am still seeing this as well on v1.3.1. While it is not the end of the world it does mean I am reloading the application multiple times in quick succession

**Comment by sagikazarmark** [comment]
Any chance this may be related?

https://github.com/spf13/viper/issues/609#issuecomment-451576230
