### ISSUE TITLE
Marshal() and env

### ISSUE THREAD

**Issue by cgt** [spf13/viper#41]
Why doesn't the Marshal func use environment variables?

**Comment by biztos** [comment]
It also doesn't use flags, apparently.  This seems like a bug.

Is there any reason for Marshal to ignore the env/flag overrides that affect GetString and friends?

**Comment by kzvezdarov** [comment]
Disclaimer: I spent ~10 minutes reading the code, might be wrong.

Seems like the [Marshal](https://github.com/spf13/viper/blob/master/viper.go#L314) function is missing the stages that marshal the env. variables and the flags. Furthermore, the order of precedence seems to be wrong: the function sets it as `defaults<config<overrides<k/v store`, while the documentation states that it should be `defaults<k/v store<config<env<flags<overrides`.

**Comment by kzvezdarov** [comment]
#44 fixes this, closing as fixed.
