### ISSUE TITLE
viper interactive

### ISSUE THREAD

**Issue by genofire** [spf13/viper#412]
I really like viper, is there a way to use it interactive? For a chatbot or so?

Here a example:
```go
package main

import (
	"bufio"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var RootCmd = &cobra.Command{
	Use: "bot",
}

var echoCmd = &cobra.Command{
	Use: "echo <message>",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println(args)
	},
}

func init() {
	RootCmd.AddCommand(echoCmd)
}

func main() {
	reader := bufio.NewReader(os.Stdin)
	fmt.Print("Enter a command: ")
	cmd, _ := reader.ReadString('\n')
	fmt.Println(cmd)
	// ??? RootCmd....(cmd)
}

```
beside the `cmd` is it possible to pass a [context](https://blog.golang.org/context) into the Run.

**Comment by sagikazarmark** [comment]
Not sure I completely understand your problem or if it is related to viper or cobra, but here is an example using cobra (but not viper) for an SSH interface:

https://github.com/deshboard/boilerplate-ssh-service/blob/master/pkg/app/commands.go

Don't really see how context is related, but you can definitely set arguments on both cobra and pflags (the flag library used by viper).

**Comment by genofire** [comment]
ups, u are right, i mixed viper and cobra.
Your boilerplate-ssh-service is nice (do you know a way how to handle pflags on this way, too?
