### ISSUE TITLE
Declare required dependencies with `go dep`

### ISSUE THREAD

**Issue by xcoulon** [spf13/viper#413]
The goal is to have a pair of `Gopkg.toml` and `Gopkg.lock` files to declare the dependencies in the project (but not commit the content of the `vendor` folder in the repo, as already discussed in https://github.com/spf13/viper/issues/223)

This would hopefully solve 2 cases:
- as a new contributor, I would just need to execute `dep ensure` to install all the project dependencies and `go build` or `go test` would run successfully
- as a consumer of the library, I would not have to explicitly included the project dependencies in my own project setup (dep, glide, etc.)

**Comment by sagikazarmark** [comment]
Viper uses go modules now.
