### ISSUE TITLE
unrecognized import path "golang.org/x/sys/unix"

### ISSUE THREAD

**Issue by Giri4joyz** [spf13/viper#432]
When I am trying to run the below command, in Ubuntu 16.04 LTS, 

go get github.com/spf13/viper

I am getting below error, 
girish@girish-VirtualBox:~$ go get github.com/spf13/viper
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 172.217.26.209:443: i/o timeout)
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 172.217.26.209:443: i/o timeout)
package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 172.217.26.209:443: i/o timeout)

My go env entires are as follows,

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/girish/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build644128295=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by jingyan** [comment]
I got the same issue, any clue?

**Comment by nkev** [comment]
For the benefit of others, `git clone https://github.com/golang/sys.git` did not work for me, I had to do `git clone https://go.googlesource.com/sys`

**Comment by isabella0428** [comment]
For me, the above solutions don't work. If it is the proxy problem, try to use the following setting for golang.
export GO111MODULE=on
export GOPROXY=https://goproxy.io

**Comment by sagikazarmark** [comment]
Viper uses go modules.

**Comment by mh-daneshvar** [comment]
> For me, the above solutions don't work. If it is the proxy problem, try to use the following setting for golang. export GO111MODULE=on export GOPROXY=https://goproxy.io

thanks, you saved my night
