### ISSUE TITLE
proposal: On reading multiple config files

### ISSUE THREAD

**Issue by ntakouris** [spf13/viper#442]
I would like to propose reading multiple config files specified in the manner stated by the docs: 
`viper.SetConfigName("config") // name of config file (without extension)
viper.AddConfigPath("/etc/appname/")   // path to look for the config file in
viper.AddConfigPath("$HOME/.appname")  // call multiple times to add many search paths
viper.AddConfigPath(".")   `

The config paths would be read 1-1 (if they exist) and replace already-read key/values as the flow continues.

For example, you could have a base configuration file that sits down at `.` and then a development one sitting under `./dev/` , along with a production one sitting under `./prod/`. This would allow the production and development ones to be "loaded ontop" of the base config file, overwriting values if values with already read keys exist.

Something similar is done in spring-boot where based on the profile being selected a secondary configuration file is loaded ontop of the base one.

_One could also propose adding multiple config names (or prefixes or suffixes), but I think that would be unnecessary_

I would like some feedback on this.

**Comment by 1138-4EB** [comment]
@Zarkopafilis, did you receive any feedback on this?

**Comment by shousper** [comment]
Keen on this proposal. We'd like to make use of a layered configuration system, where 1 file comes from a "shared" configuration file for the system, a second layer on top of this might come from the environment, and a 3rd layer for app-environment specific config values.

Being able to load, in order, multiple config files AND watch them (also requested here: https://github.com/spf13/viper/issues/631) would be quite useful for this.

For now, we're having to create multiple separate `Viper` instances, each with a watcher that uses the same callback which calls `Unmarshal` in the correct sequence to merge the layers. It doesn't concatenate arrays, but that's okay in our case.

**Comment by paul-rogers** [comment]
Looking for the same feature. In [Apache Drill](http://drill.apache.org/) (Java), we use a layered system based on the [TypeSafe/LightBend config system](https://github.com/lightbend/config):

* Out-of-the-box defaults in a set of "base" config files; one per module. (Values are disjoint.)
* "Distro-specific" values set by a distribution or vendor that override the defaults. For, say, differences between HDFS, S3, etc.
* User/site specific values that override the above.

This in addition to the command-line flag and Java property values which can override the above. Drill has hundreds of properties and the above layering system (with hierarchical naming) has worked pretty well. Layering of files seems the one missing part of the puzzle in Viper.

**Comment by Zarkopafilis** [comment]
Please don't limit this to a arbitrary number of layers (ex 3). At least
for the application level, let the user load as many files as he wants with
the configuration keys being rewritten/appended in the file loading order.
For most people the 3 layered system would be more than enough.

**Comment by sagikazarmark** [comment]
SOunds like a great addition to the Viper 2 plan. I would imagine different config sources as an abstraction that can be combined in any arbitrary way. With such an abstraction it's easy to implement any kind of custom configuration.

**Comment by Zarkopafilis** [comment]
Maybe something like this can be added:

Special kind of properties declared in an array-like fashion and if new
entries on this array are detected, they are concatenated to form the final
configuration.

These are all the recommendations I have thought of.

**Comment by alecb-stripe** [comment]
@spf13 Any thoughts on this? Would you be open to seeing a reference implementation, or do you have concerns on this being implemented at all?

**Comment by sagikazarmark** [comment]
I don't think this should go into Viper v1. The Viper v2 structure will make features like this possible.

**Comment by gildas** [comment]
FWIW, here is an easy way to achieve this with Viper v1, it honors the XDG Base Directory, falls back to the home directory and uses the current folder (even with a .env):
```go
// initConfig reads in config file and ENV variables if set.
func initConfig() {
	home, err := homedir.Dir()
	cobra.CheckErr(err)

	if len(cfgFile) > 0 { // Use config file from the flag.
		viper.SetConfigFile(cfgFile)
	} else if xdg := core.GetEnvAsString("XDG_CONFIG_HOME", ""); len(xdg) > 0 {
		viper.AddConfigPath(path.Join(xdg, "myapp"))
		viper.SetConfigName("config")
	} else {
		viper.AddConfigPath(path.Join(home, ".config", "myapp"))
		viper.SetConfigName("config")
	}
	viper.SetConfigType("yaml")

	viper.AutomaticEnv() // read in environment variables that match
	err = viper.ReadInConfig()
	if _, ok := err.(viper.ConfigFileNotFoundError); ok {
		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigName(".myapp")
		err = viper.ReadInConfig()
		if _, ok := err.(viper.ConfigFileNotFoundError); ok {
			viper.SetConfigType("envfile")
			viper.SetConfigName(".env")
			err = viper.ReadInConfig()
			if _, ok := err.(viper.ConfigFileNotFoundError); ok {
				err = nil // It's ok if the config file does not exist
			}
		}
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s", err)
		os.Exit(1)
	}
}
```

**Comment by eine** [comment]
@gildas, it seems that your snippet loads a single file. It can be different depending on the environment, but I'd say it cannot load two files and combine them. Am I missing something?

**Comment by gildas** [comment]
> @gildas, it seems that your snippet loads a single file. It can be different depending on the environment, but I'd say it cannot load two files and combine them. Am I missing something?

Correct. It's simple.
It does not cover config files that override each other depending on where they are, nor multiple config files in the XDG folders.

That could be easily doable though, by concatenating the files in order a you go (so a more recent definition in a file would overwrite a previous one) and loading them in Viper at the end.

**Comment by eine** [comment]
The purpose of this issue is precisely reading multiple config files and overriding each other... See the first comment above.

**Comment by ajpauwels** [comment]
Hey everyone, I made a thread-safe, thin synchronization layer on top of viper to support sourcing from an infinite number of config files (viper instances), and deterministically merging them on each change of one of the files. It's called pit-of-vipers and is available here:

https://github.com/ajpauwels/pit-of-vipers

**Comment by ntakouris** [comment]
stale

**Comment by andreymal** [comment]
@ntakouris wat

**Comment by githoober** [comment]
Any news?

**Comment by jiajun-c** [comment]
any news?
