### ISSUE TITLE
support envvar binding of map[string]string type as it is done for []string

### ISSUE THREAD

**Issue by xvello** [spf13/viper#451]
Hello,

We are extensively using envvar bindings to configure our dockerized software. We already leverage the `[]string` automatic parsing [for some envvars](https://github.com/DataDog/datadog-agent/blob/3de810e2daf1e0cd7616879ece94642477cacfa2/pkg/config/config.go#L114), and will get requests to bind [some of our map[string]string options](https://github.com/DataDog/datadog-agent/blob/3de810e2daf1e0cd7616879ece94642477cacfa2/pkg/config/config.go#L138) too.

From my investigation, []string parsing from string is [provided by cast.ToStringSliceE](https://github.com/spf13/cast/blob/master/caste.go#L1038), but [cast.ToStringMapStringE does not handle string input](https://github.com/spf13/cast/blob/acbeb36b902d72a7a4c18e8f3241075e7ab763e4/caste.go#L854).

Would you be open to a PR adding support for string -> map[string]string casting? What format would be OK with you?

I'm opening my issue on this repo as the functionnal need is in viper and might be addressed differently. What do you think?

**Comment by xvello** [comment]
@spf13 @bep Do you think that would be a legit addition to viper? Do you have any preference on how to approach this issue?

**Comment by bep** [comment]
This is a fairly common "Hugo support question" as well, so yes, this is welcome.

I have not thought about the format. Are there some format we can borrow in the wild?

* The ToStringSlice takes space separated strings, e.g. `a b c` => `[a, b, c]`

Maybe we can continue with something simple, like:

```
key1:value1 key2:value2
```

?

**Comment by xvello** [comment]
using spaces and colons as separators make it consistent with `ToStringSlice` and does not conflict with our use case. I'm a bit afraid other users of the lib would rather have different separators.

An alternative would be to allow inline json that we try to unmarshall in a map[string]string, then default to "k:v k:v" parsing if the unmarshalling fails.

In that case, both format could be supported:

- MYDICT='{"key": "value with spaces", "other_key": "value:with_a_colon"}'
- MYOTHERDICT = "simplekey:simplevalue otherkey:bar"

WDYT?

**Comment by bep** [comment]
Yes, that sounds good. The JSON syntax should be common enough for "maps".

**Comment by xvello** [comment]
Cool, I'll work on a PR and link it on this issue when opened!

**Comment by xvello** [comment]
I opened https://github.com/spf13/cast/pull/59 to address this issue.

To follow the least surprise principle, it would be great to also support JSON for the array types, although we'd need to discuss how to handle the current `[]string` casting based on spaces as separators. We could try unmarshalling and, if we have an error, fallback to the current `strings.Fields` logic. The downside is that we would drop the unmarshalling error. 

I could implement it in a follow-up PR if you find it useful.

**Comment by xvello** [comment]
https://github.com/spf13/cast/releases/tag/v1.2.0 includes this feature, thanks!
Closing the issue
