### ISSUE TITLE
Support for .env files?

### ISSUE THREAD

**Issue by cemremengu** [spf13/viper#455]
Is there support for a feature like provided by [this library](https://github.com/joho/godotenv)?

Basically if `.env` file exists it will read variables from there, otherwise from OS.

**Comment by bxcodec** [comment]
Someone already submits a PR here, #528 
Look forward to this support

**Comment by boskiv** [comment]
How I can get it? I see that it already merge but not in release.

**Comment by sagikazarmark** [comment]
Adding `master` to a `go.mod` file is not valid indeed.

You should use:

```
go get github.com/spf13/viper@master
```

**Comment by boskiv** [comment]
I can't 
```
➜  go-open-registry git:(git-registry) ✗ go get
go get: disabled by -mod=vendor

```

**Comment by Jyny** [comment]
#756 
add ability to search `.env` or other dotfiles

**Comment by Jyny** [comment]
> -

when will have new release?

**Comment by Jyny** [comment]
@sagikazarmark  @boskiv 
though PR is merged but not in latest release
when will have new release?

**Comment by axiaoxin** [comment]
What is the current situation here? Is there any conclusion or progress?

**Comment by CSRaghunandan** [comment]
+1

Would love to see this feature in viper

**Comment by sagikazarmark** [comment]
Unless I'm mistaken #528 added support for .env files and it's been released for quite some time now.

**Comment by CSRaghunandan** [comment]
> Unless I'm mistaken #528 added support for .env files and it's been released for quite some time now.

@sagikazarmark is there any documentation on how to use it?

I set the config type to `dotenv` and I get an error saying its not a supported type.

**Comment by sagikazarmark** [comment]
.env and .dotenv types are working similarly to any config types. Looking at the code, you'll have to set an explicit config file if you want to use `.env`. A file called `config.env` should automatically be discovered.

**Comment by CSRaghunandan** [comment]
> .env and .dotenv types are working similarly to any config types. Looking at the code, you'll have to set an explicit config file if you want to use `.env`. A file called `config.env` should automatically be discovered.

I see. I will test it out later today and will report if I was able to get it to work.

Thanks for the quick response.

**Comment by CSRaghunandan** [comment]
@sagikazarmark it worked! Now I'm able to read from a file called `config.env` which holds all the secret data.

Thank you :)

**Comment by abdennour** [comment]
what about .env filename ?

**Comment by abdennour** [comment]
is there any documentation on how to use it?

I set the config type to dotenv and I get an error saying its not a supported type.

**Comment by abdennour** [comment]
.env works ou-of-the-box

```go
func LoadConfig(path string) (config Config, err error) {
	viper.AddConfigPath(path)
	viper.SetConfigName("app")
	viper.SetConfigType("env")

	viper.AutomaticEnv()

	err = viper.ReadInConfig()
	if err != nil {
		return
	}

	err = viper.Unmarshal(&config)
	return
}
```

then
`LoadConfig(".")`

**Comment by MinSomai** [comment]
> what about .env filename ?
```go
viper.AddConfigPath(".")
viper.SetConfigFile(".env") // json, xml
```

use the `SetConfigFile()` method.
