### ISSUE TITLE
viper.Reset() can longer be called from test code

### ISSUE THREAD

**Issue by rosscooperman** [spf13/viper#46]
We have a number of tests that depend on `viper.Reset()` to restore viper's state between tests.  Since `Reset()` got moved to viper_test.go, though, we are no longer able to do that.  I thought I remembered some documentation somewhere even suggesting that `Reset()` could be used in tests but it's possible I'm imagining that.  Anyway, having access to that function in our tests would be super helpful.

**Comment by spf13** [comment]
Thanks @rosscooperman. It did say that, and when I wrote it I was only thinking of viper tests. Not app tests. 

A total oversight on my part. I'd love a PR that restores reset to the proper place (and makes sure all the tests still run). I can also make the fix, but it may be a bit before I can do it.

**Comment by rosscooperman** [comment]
No problem, I'll fire off a PR as soon as I can.
