### ISSUE TITLE
Viper cannot be a dependency of projects using vgo

### ISSUE THREAD

**Issue by SamWhited** [spf13/viper#466]
[vgo](https://research.swtch.com/vgo-intro) is picky about import casing when downloading deps using the GitHub API:

```
        import "github.com/spf13/viper" ->
        import "github.com/spf13/jwalterweatherman": module path of repo is github.com/spf13/jWalterWeatherman, not github.com/spf13/jwalterweatherman (wrong case)
```

I submitted #465 but do not want to sign a CLA. Since it is not copyrightable feel free to use it or just fix these two lines. Thanks.

**Comment by sagikazarmark** [comment]
@SamWhited is this still an issue for you?

**Comment by SamWhited** [comment]
Unsure, it appears that another PR was merged that fixes it but I don't use Viper personally and don't have the time to check right now. Closing and assuming its fine now that this is on modules.
