### ISSUE TITLE
Panic when checking if flag is set

### ISSUE THREAD

**Issue by combor** [spf13/viper#467]
## What

Viper panics in `IsSet` method when bound to a flag. 

## How to reproduce

Use `cobra init github.com/you/test` and change default `init()` method in `cmd/root.go` to:

```
func init() {
	var token string
	rootCmd.PersistentFlags().StringVar(&token, "github_token", "", "GitHub token")
	viper.BindPFlag("github_token", rootCmd.Flags().Lookup("github_token"))
	fmt.Println(viper.IsSet("github_token"))
}
```

## Expected behaviour 

Print `true`

## Stacktrace 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x13684b5]

goroutine 1 [running]:
github.com/spf13/viper.pflagValue.HasChanged(0x0, 0xc420089650)
	/Users/you/dev/src/github.com/spf13/viper/flags.go:41 +0x5
github.com/spf13/viper.(*Viper).find(0xc4200a20f0, 0x144c6e6, 0xc, 0xc, 0x136cb5b)
	/Users/you/dev/src/github.com/spf13/viper/viper.go:914 +0xd9c
github.com/spf13/viper.(*Viper).IsSet(0xc4200a20f0, 0x144c6e6, 0xc, 0x0)
	/Users/you/dev/src/github.com/spf13/viper/viper.go:1017 +0x57
github.com/spf13/viper.IsSet(0x144c6e6, 0xc, 0x0)
	/Users/you/dev/src/github.com/spf13/viper/viper.go:1014 +0x41
github.com/you/test/cmd.init.0()
	/Users/you/dev/src/github.com/you/test/cmd/root.go:56 +0x104
exit status 2

**Comment by combor** [comment]
I fund what was causing the problem. I used `rootCmd.Flags().Lookup("github_token")` instead of `rootCmd.PersistentFlags().Lookup("github_token")`. Closing.

**Comment by marcofranssen** [comment]
I'm having same issue when trying the following.

```
	serveCmd.Flags().StringVarP(&listenAddr, "listenAddr", "a", ":5000", "server listen address")
	viper.BindPFlag("server.listenAddr", rootCmd.Flags().Lookup("listenAddr"))
	viper.SetDefault("server.listenAddr", ":5000")

       viper.GetString("server.listenAddr")
```

**Comment by Tsuki** [comment]
> I'm having same issue when trying the following.
> 
> ```
> 	serveCmd.Flags().StringVarP(&listenAddr, "listenAddr", "a", ":5000", "server listen address")
> 	viper.BindPFlag("server.listenAddr", rootCmd.Flags().Lookup("listenAddr"))
> 	viper.SetDefault("server.listenAddr", ":5000")
> 
>        viper.GetString("server.listenAddr")
> ```
@marcofranssen 
serveCmd.Flags().StringVarP(&listenAddr...
rootCmd.Flags()
you setup the flag on serveCmd
but looking the flag from rootCmd
Therefore it throw invalid memory address or nil pointer dereference
