### ISSUE TITLE
Does this work with an appengine app?

### ISSUE THREAD

**Issue by chadkouse** [spf13/viper#50]
seems like maybe no.

**Comment by chadkouse** [comment]
I should clarify -- I tried to push my app to gae while utilizing viper and got this error:
```
github.com/xordataexchange/crypt/backend/etcd/etcd.go:8: can't find import: "github.com/coreos/go-etcd/etcd"
```

**Comment by spf13** [comment]
Most of the functionality would work. I'm not sure if there are issues specific to etcd.

**Comment by ecnahc515** [comment]
I think that error could be caused by the older version of Go that app engine uses.

**Comment by bep** [comment]
The remote features in Viper should now be optional after be5ff3e
