### ISSUE TITLE
WriteConfig does not close file after finishes writing

### ISSUE THREAD

**Issue by pankrator** [spf13/viper#505]
In my code I use this method `WriteConfig` : https://github.com/spf13/viper/blob/master/viper.go#L1210
Later on, I want to reuse the file, but I get the following error: 

>  The process cannot access the file because it is being used by another process.

It seems like `WriteConfig` does not close the file.

If I add the following [here](https://github.com/spf13/viper/blob/master/viper.go#L1265-L1268) `defer f.Close()` everything works:

```go
f, err := v.fs.OpenFile(filename, flags, os.FileMode(0644))
if err != nil {
	return err
}
defer f.Close()  // <--- This line
```

Is WriteConfig not closing the file the expected behaviour?

**Comment by anmyachev** [comment]
@sagikazarmark @pankrator the issue fixed by #543
