### ISSUE TITLE
Sub() ignores variables set with BindEnv/AutomaticEnv

### ISSUE THREAD

**Issue by lucasvo** [spf13/viper#507]
The following example fails because Sub() because variables overwritten in env are ignored.

```yaml,
grandParent:
    parent:
        child: bar
```

```go,
package main

import (
	"fmt"
	"github.com/spf13/viper"
	"os"
	"strings"
)

var v *viper.Viper

func main() {
	os.Setenv("GRANDPARENT_PARENT_CHILD", "foo")
	v = viper.New()
	v.SetConfigType("yaml")
	v.AutomaticEnv()
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	f, _ := os.Open("test.yaml")
	v.ReadConfig(f)
	sub := v.Sub("grandParent.parent")
	fmt.Println("Direct", v.GetString("grandParent.parent.child"))
	fmt.Println("Sub", sub.GetString("child"))
	if sub.GetString("child") != v.GetString("grandParent.parent.child") {
		panic("sub ignores os.environ")
	}
}
```

The output of the program is:

```
Direct foo
Sub bar
panic: sub ignores os.environ
[...]
```

**Comment by lucasvo** [comment]
Related to: #307

**Comment by vail130** [comment]
Ran into this issue, which took a couple hours of debugging to discover. I'd love to see some explicit documentation about this limitation, if not a fix.

**Comment by lucasvo** [comment]
@spf13 would be awesome to get #508 merged! I am sure @vail130 and I are not the only ones here...

**Comment by guyisra** [comment]
any updates on this?

**Comment by 89z** [comment]
https://github.com/spf13/viper/issues/140

https://github.com/spf13/viper/issues/507
https://github.com/spf13/viper/issues/522
https://github.com/spf13/viper/issues/576
https://github.com/spf13/viper/issues/911
