### ISSUE TITLE
Unmarshal doesn't work with AutomaticEnv

### ISSUE THREAD

**Issue by natefinch** [spf13/viper#522]
At the bottom is a test that I would expect to pass, it doesn't.  The crux seem to be that with AutomaticEnv, viper.Get does some magic to call into the environment, but that magic is not used during Unmarhsal, so unless you explicitly call BindEnv, the respective environment variables aren't queried.

```go
package config

import (
	"os"
	"strings"
	"testing"

	"github.com/spf13/viper"
)

func TestViperUnmarshalAutoEnv(t *testing.T) {
	type config struct {
		Name string
	}

	name := "foobar"
	if err := os.Setenv("VIPERTEST_NAME", name); err != nil {
		t.Fatal(err)
	}

	v := viper.New()
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.SetEnvPrefix("VIPERTEST")
	v.AutomaticEnv()

	// if you uncomment this line, the test will pass, otherwise it'll fail.
	// I would not expect to have to call bind if I'm using AutomaticEnv.
	// v.BindEnv("name")

	c := config{}
	if err := v.Unmarshal(&c); err != nil {
		t.Fatal(err)
	}

	if v.GetString("name") != c.Name {
		t.Fatalf("expected name to be %q but got %q", v.GetString("name"), c.Name)
	}
}
```

**Comment by natefinch** [comment]
This looks to be a duplicate of #188 

I think it's pretty clear that if someone calls viper.AutomaticEnv() and then calls Unmarshal, they expect everything in the target value to query the environment. That's what automatic means.

**Comment by YAOHAO9** [comment]
In my case:
+ It is working  for windows
```
// 读取环境变量
viper.AutomaticEnv()
viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
```
+ It is working for both windows and linux
```
for _, key := range viper.AllKeys() {
	viper.BindEnv(key, strings.ReplaceAll(key, ".", "_"))
}
```

**Comment by 89z** [comment]
https://github.com/spf13/viper/issues/140
https://github.com/spf13/viper/issues/507

https://github.com/spf13/viper/issues/522
https://github.com/spf13/viper/issues/576
https://github.com/spf13/viper/issues/911
