### ISSUE TITLE
GPL License in dependencies

### ISSUE THREAD

**Issue by jancajthaml** [spf13/viper#540]
Hi there,

This project (that is MIT Licensed) seems to use `http://github.com/hashicorp/hcl` that is GPL (MPL Licensed) that seems incompatible and quite problematic.

Would you kindly please remove HCL support from your awesome package and provide it as a separate package so that we do not have GPL LICENSE in code that uses viper and does not use/need HCL format.

Thank you very much

**Comment by moorereason** [comment]
License compatibility is complicated enough without you conflating different licenses. Please be precise.  `github.com/hashicorp/hcl` is not licensed under the GPL.  It's licensed under the MPL-2.0.

**Comment by jancajthaml** [comment]
Its still copyleft (Lesser Copyleft to be precise) that does have some constrains of usage. We love to use your library and are grateful that its licensed under MIT. Would it be possible to provide not necessary used formats as a separate package and import it accordingly?

I can imagine something like

```
import (
_ "github.com/spf13/viper/formats/hcl"
_ "github.com/spf13/viper/formats/yaml"
_ "github.com/spf13/viper/formats/json"
)
```

that would allow us to don't shit software that is copyleft while still using your awesome library and make anyone who wants to use any format in a transparent matter.

GPL, LGPL, MPL or any derivate are really really bad licenses for non-hobby, non-opensource software. I know thats why this license is written as is.

So please try to consider providing way to use your awesome library without copyleft in unused code  because someone somewhere may use terraform format for config.

Thank You
