### ISSUE TITLE
why does viper limit the file SupportedExts?

### ISSUE THREAD

**Issue by sanqingshan** [spf13/viper#562]
why does viper limit the file SupportedExts?
i just found it can not supported for zookeeper config file zoo.cfg

for use it ,i should update this code
var SupportedExts = []string{"json", "toml", "yaml", "yml", "properties", "props", "prop", "hcl","cfg"}

**Comment by sagikazarmark** [comment]
You can change the supported extensions, but Viper only supports a predefined set of formats at the moment. Viper v2 will add support for custom formats as well.
