### ISSUE TITLE
Require configs are present

### ISSUE THREAD

**Issue by caalberts** [spf13/viper#572]
In my projects at work, we have been wrapping viper to add checks to ensure required config values have been set, either through environment variables or config file.

The reason for this is to avoid runtime panics when a critical config is missing.

Something like:
```go
func Require(key string) (interface{}, error)
```

Has viper considered this functionality? If it's worth adding to viper, I can work on a PR.

**Comment by gabeduke** [comment]
@caalberts what is remaining to start a PR? This feature is quite useful since cobra `RequiredFlags` is not usable after binding the flag to viper.

**Comment by caalberts** [comment]
I have actually created a PR #573 for this.

**Comment by sagikazarmark** [comment]
Please see my comment: https://github.com/spf13/viper/pull/573#issuecomment-759630829
