### ISSUE TITLE
IsSet always returns true if the key is bound to a flag.

### ISSUE THREAD

**Issue by deinspanjer** [spf13/viper#580]
It is not possible to use spf13/pflag without specifying a default value, and it is not a pointer, so you cannot set it to nil.  pflag does have a method `Changed()` which can test whether something was set with the flag, as well as unexported functions to test if the value is currently the zero value.

However, if you use viper.BindPFlag, when you call IsSet, the unexported find() method will return the value of the pflag as the very last condition, and it does not check whether it is the zero value, so it will always return true.

**Comment by fastcat** [comment]
Looks to be the same as #323, #276, attempted fixed in #331
