### ISSUE TITLE
Does viper require a config file in order to use ENV variables?

### ISSUE THREAD

**Issue by jsirianni** [spf13/viper#584]
Hi, I have an application that can use both a config file and env variable.

My `initConfig()` method looks like this:
```
if err := viper.ReadInConfig(); err == nil {
	fmt.Println("Using config file:", viper.ConfigFileUsed())
} else {
	fmt.Println("Config file not found:", cfgFile)
}

viper.SetEnvPrefix("GC")
viper.AutomaticEnv()

err := viper.Unmarshal(&config)
if err != nil {
	fmt.Println(err.Error())
	os.Exit(1)
}
```

`unmarshal` drops the config into a struct, and it works well. 

I am facing an issue where if my config file does not exist (or is empty), viper seems to completely ignore any environment variables. I have verified that viper can see the env variables, by printing them to standard out. My workaround is to deploy the config file, with all the correct keys but no values. Viper then correctly overrides the config file with my environment variables. 

Am I wrong to assume that Viper should be able to use environment variables when no config file is found?

**Comment by matejkramny** [comment]
+1 just spent a lot of time finding why env variables don't bind to the config file. Simply adding the key to the yaml file made it work

**Comment by jsirianni** [comment]
Looking at `viper.go`, I find this comment:
```
// Viper is a prioritized configuration registry. It
// maintains a set of configuration sources, fetches
// values to populate those, and provides them according
// to the source's priority.
// The priority of the sources is the following:
// 1. overrides
// 2. flags
// 3. env. variables
// 4. config file
// 5. key/value store
// 6. defaults
//
// For example, if values from the following sources were loaded:
//
//  Defaults : {
//  	"secret": "",
//  	"user": "default",
//  	"endpoint": "https://localhost"
//  }
//  Config : {
//  	"user": "root"
//  	"secret": "defaultsecret"
//  }
//  Env : {
//  	"secret": "somesecretkey"
//  }
//
// The resulting config will have the following values:
//
//	{
//		"secret": "somesecretkey",
//		"user": "root",
//		"endpoint": "https://localhost"
//	}
```

The example shows `secret` being in all three configuration sources, and being overridden accordingly. What they do not seem to mention is that config is required. I find it hard to believe that it should be this way, considering values found in a config work just fine even if you have not specified defaults anywhere. 

It would be nice to know if this is desired behavior, so I can build my applications accordingly. My main driver for avoiding a configuration file is that I do not wish to have configurations baked into my docker containers. I can deploy empty configurations, however, that is an additional (and unnecessary) stop in my build process.

**Comment by renannprado** [comment]
@jsirianni totally agree with you. I was surprised actually that I'm forced to configure `AddConfigPath`, `SetConfigName`, `SetConfigType`, `AutomaticEnv` and set a default value like this (`viper.SetDefault("TEST", "")`) or via file.
IMO the `Unmarshal` should bind out of the box to the environment variables, i.e. running `AutomaticEnv` should be enough for `Unmarshal` to work properly. I'm not sure if easy or feasible (given the maintainers want to keep backwards compatibility probably), but I'd say this sounds like the logical behavior to me.

**Comment by sagikazarmark** [comment]
The problem is actually `Unmarshal` in this case. If you don't set a config and call `viper.Get*` you will receive the desired value. The AutomaticEnv feature (when turned on) will check the environment variable even if it isn't registered.

Unmarshal works a bit differently: it collects the registered keys and passes them with their values to the mapstructure package which binds the values to the appropriate keys of the structure. In this case there is no "request" nothing to compare against.

I agree that this is not optimal, but given Unmarshal was added later I can hardly categorize this as a regression.

Unfortunately it's not easy to fix as environment variables are transformed in various ways:
- a prefix is added
- env key replacer is applied

Even if the prefix can be transformed back, the env key replacer cannot be "reversed".

It would probably worth checking to see if somehow we can get the keys from mapstructure or hook into the process there somehow.

In the meantime, using BindEnv manually is the only way unfortunately (or manual unmarshaling).

**Comment by sagikazarmark** [comment]
Please see and follow the issue above. ☝️

**Comment by Niondir** [comment]
I'm modeling my whole config as struct. To make all environment variables work, even when the config file does not contain the key I first load my defaults from a struct like this:

```
func Init() {
	initDefaultValues()
	/* ... */
	viper.AutomaticEnv()
	/* ... */
	viper.ReadInConfig()
}


func initDefaultValues() {
	defaultConfig = &Config{}
	defaultConfig.Server.Port = 1272

	loadConfigFromStruct(defaultConfig)
}

func loadConfigFromStruct(cfg interface{}) {
	cfgMap := make(map[string]interface{})
	err := mapstructure.Decode(cfg, &cfgMap)
	if err != nil {
		logrus.WithError(err).Fatalf("failed to marshal default config")
		os.Exit(1)
	}

	cfgJsonBytes, err := json.Marshal(&cfgMap)
	if err != nil {
		logrus.WithError(err).Fatalf("failed to marshal default config")
		os.Exit(1)
	}

	viper.SetConfigType("json")
	err = viper.ReadConfig(bytes.NewReader(cfgJsonBytes))
	if err != nil {
		logrus.WithError(err).Fatalf("failed to load default config")
		os.Exit(1)
	}
}

```

**Comment by iurydias** [comment]
Facing the same issue... and it seems to have a not easy solution :(

**Comment by drakkan** [comment]
> Facing the same issue... and it seems to have a not easy solution :(

you can simply use `viper.SetDefault`. This way you can override from env even without a config file

**Comment by iurydias** [comment]
> > Facing the same issue... and it seems to have a not easy solution :(
> 
> you can simply use `viper.SetDefault`. This way you can override from env even without a config file

it works... thank you so much!

**Comment by nabeelsaabna** [comment]
I hope it's not a long answer to this problem (not tested with maps)

Below code will:
- go over the `Settings` struct that contains the configuration hierarchy of my project
- adds recursively all the fields under it to viper with default of empty value

which leads to all of these fields to get picked up from the environment 

the printed output from the `addKeysToViper` :
```
VITALS.PRODUCT.NAME
VITALS.PRODUCT.TOKEN
VITALS.PROJECT.NAME
VITALS.PROJECT.TOKEN
EXCLUDES
```
env vars used in this test:
```
ABC_VITALS_PRODUCT_NAME=a
ABC_VITALS_PRODUCT_TOKEN=b
ABC_EXCLUDES=c
```

the resulting value for `out.yaml` :
```
excludes: c
vitals:
  product:
    name: a
    token: b
  project:
    name: ""
    token: ""
```

```
package main

import (
	"fmt"
	"github.com/spf13/viper"
	"reflect"
	"strings"
)

type (
	Settings struct {
		Vitals   Vitals
		Excludes []string `yaml:"excludes,omitempty"`
	}

	Vitals struct {
		Product PIdentifier
		Project PIdentifier
	}

	PIdentifier struct {
		Name  string
		Token string
	}
)

func addKeysToViper(v *viper.Viper) {
	var reply interface{} = Settings{}
	t := reflect.TypeOf(reply)
	keys := getAllKeys(t)
	for _,key := range keys {
		fmt.Println(key)
		v.SetDefault(key, "")
	}
}

func getAllKeys(t reflect.Type) []string {
	var result []string

	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		n := strings.ToUpper(f.Name)
		if reflect.Struct == f.Type.Kind() {
			subKeys := getAllKeys(f.Type)
			for _, k := range subKeys {
				result = append(result, n+"."+k)
			}
		} else {
			result = append(result, n)
		}
	}

	return result
}

func main() {
	v := viper.New()
	addKeysToViper(v)
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.SetEnvPrefix("ABC")
	v.AutomaticEnv()

	fmt.Println(v.WriteConfigAs("out.yaml"))
}

```

**Comment by qwerty22121998** [comment]
my workaround, seem silly but it worked 
```go

func Parse(i interface{}) error {
	r := reflect.TypeOf(i)
	for r.Kind() == reflect.Ptr {
		r = r.Elem()
	}
	for i := 0; i < r.NumField(); i++ {
		env := r.Field(i).Tag.Get("mapstructure")
		if err := viper.BindEnv(env); err != nil {
			return err
		}
	}
	return viper.Unmarshal(i)
}
```

**Comment by mccallry** [comment]
The above example from @qwerty22121998 is a solid work around for flat structures; however, it struggles in that it doesn't deal with nested structures ([Go Playground Link](https://go.dev/play/p/vTmKhwiGhC5)).

```go
package main

import (
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/spf13/viper"
)

type Config struct {
	Foo string `mapstructure:"FOO"`
	Bar string `mapstructure:"BAR"`
	Baz FooBar `mapstructure:"BAZ"`
}

type FooBar struct {
	Foo string `mapstructure:"FOO"`
	Bar string `mapstructure:"BAR"`
}

func scaffold() {
	os.Setenv("FOO", "1")
	os.Setenv("BAR", "A")
	os.Setenv("BAZ.FOO", "2")
	os.Setenv("BAZ.BAR", "B")
}

func parseEnv(i interface{}) error {
	r := reflect.TypeOf(i)
	for r.Kind() == reflect.Ptr {
		r = r.Elem()
	}
	for i := 0; i < r.NumField(); i++ {
		env := r.Field(i).Tag.Get("mapstructure")
		if err := viper.BindEnv(env); err != nil {
			return err
		}
	}
	return viper.Unmarshal(i)
}

func main() {
	scaffold()

	var c Config
	if e := parseEnv(&c); e != nil {
		panic(e)
	}
	fmt.Println(fmt.Sprintf("%+v", c))
}
```

The above will output:

```sh
{Foo:1 Bar:A Baz:{Foo: Bar:}}

Program exited.
```

I would suggest making a few changes. In particular, we want to check if the current property is a struct and recursively try and build the environment variables. If you want to use this strategy, I would propose changes like the following ([Go Playground Link](https://go.dev/play/p/gn4nWKjgScb)):

```go
package main

import (
	"fmt"
	"os"
	"reflect"

	"github.com/spf13/viper"
)

type Config struct {
	Foo string `mapstructure:"FOO"`
	Bar string `mapstructure:"BAR"`
	Baz FooBar `mapstructure:"BAZ"`
}

type FooBar struct {
	Foo string    `mapstructure:"FOO"`
	Bar string    `mapstructure:"BAR"`
	Baz FooBarBaz `mapstructure:"BAZ"`
}

type FooBarBaz struct {
	Foo string `mapstructure:"FOO"`
	Bar string `mapstructure:"BAR"`
}

func scaffold() {
	os.Setenv("FOO", "1")
	os.Setenv("BAR", "A")
	os.Setenv("BAZ.FOO", "2")
	os.Setenv("BAZ.BAR", "B")
	os.Setenv("BAZ.BAZ.FOO", "2")
	os.Setenv("BAZ.BAZ.BAR", "B")
}

func parseEnv(i interface{}, parent, delim string) error {
	// Retrieve the underlying type of variable `i`.
	r := reflect.TypeOf(i)

	// If `i` is of type pointer, retrieve the referenced type.
	for r.Kind() == reflect.Ptr {
		r = r.Elem()
	}

	// Iterate over each field for the type. By default, there is a single field.
	for i := 0; i < r.NumField(); i++ {
		// Retrieve the current field and get the `mapstructure` tag.
		f := r.Field(i)
		env := f.Tag.Get("mapstructure")

		// By default, set the key to the current tag value. If a parent value was passed in
		//	prepend the parent and the delimiter.
		if parent != "" {
			env = parent + delim + env
		}

		fmt.Println(env)
		// If it's a struct, only bind properties.
		if f.Type.Kind() == reflect.Struct {
			t := reflect.New(f.Type).Elem().Interface()
			parseEnv(t, env, delim)
			continue
		}

		// Bind the environment variable.
		if e := viper.BindEnv(env); e != nil {
			return e
		}
	}
	return viper.Unmarshal(i)
}

func main() {
	scaffold()

	var c Config
	if e := parseEnv(&c, "", "."); e != nil {
		panic(e)
	}
	fmt.Println(fmt.Sprintf("%+v", c))
}
```

The above will output:

```sh
{Foo:1 Bar:A Baz:{Foo:2 Bar:B Baz:{Foo:2 Bar:B}}}

Program exited.
```

For anyone else who ends up searching up this issue and coming here, this is because Viper, at its core, is primarily meant to handle file-based environment configurations. In fact, the [`Unmarshal` method](https://github.com/spf13/viper/blob/5247643f02358b40d01385b0dbf743b659b0133f/viper.go#L1085) doesn't even interact with the `automaticEnvApplied ` flag in the `Viper` struct in any way. As per the [Working with Environment Variables](https://github.com/spf13/viper#working-with-environment-variables) section:
> `AutomaticEnv` is a powerful helper especially when combined with `SetEnvPrefix`. When called, Viper will check for an environment variable any time a `viper.Get` request is made. It will apply the following rules. It will check for an environment variable with a name matching the key uppercased and prefixed with the `EnvPrefix` if set.

Essentially, if you want to use environment variables by themselves you need to either:
1. Create a solution which adds the environment variables into the internal maps, such as leveraging the `BindEnv` method as above.
2. Retrieve the environment values using the `Get` method, which does interact with the `AutomaticEnv` flag.

I would probably recommend sticking to one of the above solutions which binds variables into one of the internal maps used by Viper instead of using some recursive method in which you uses the `reflection` package and `viper.Get` to build the struct. At that point, you may as well just not use Viper at all and grab the variables directly from `os.Getenv`.

**Comment by fclairamb** [comment]
For those who are tired of these issues (which essentially come from bad design), you should have a look at [koanf](https://github.com/knadh/koanf).
The number of ⭐ isn't always related with quality, in terms of design/code or even support.

**Comment by dskrypko** [comment]
In my case, with no structured flags, the solution that helped me was to remove `viper.SetEnvPrefix(...)`.

So, in the case of:
```
package config

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

const (
	defaultFlagValue = "my value"

	ConfigFile = "/myApp/configfile"
)

var (
	_ = pflag.String("my_app_my_flag", defaultFlagValue, "flag description")
)

func init() {
	viper.SetEnvPrefix(EnvPrefix)
	viper.AutomaticEnv()
	viper.SetConfigType("env")

	if _, err := os.Stat(ConfigFile); err == nil {
		viper.SetConfigFile(ConfigFile)

		err := viper.ReadInConfig()
		if err != nil {
			fmt.Printf("Config file reading error: %v", err)
		}
	}

	pflag.Parse()
	viper.BindPFlags(pflag.CommandLine)
}
```
I was able to get only the command line option, config file option, or default value. So, the environment variable value was always ignored.

Once I removed the `viper.SetEnvPrefix(...)`:
```
package config

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

const (
	defaultFlagValue = "my value"

	ConfigFile = "/myApp/configfile"
	EnvPrefix = "MY_APP"
)

var (
	_ = pflag.String("my_app_my_flag", defaultFlagValue, "flag description")
)

func init() {
	viper.AutomaticEnv()
	viper.SetConfigType("env")

	if _, err := os.Stat(ConfigFile); err == nil {
		viper.SetConfigFile(ConfigFile)

		err := viper.ReadInConfig()
		if err != nil {
			fmt.Printf("Config file reading error: %v", err)
		}
	}

	pflag.Parse()
	viper.BindPFlags(pflag.CommandLine)
}
```
everything became as expected for me: command line option -> environment variable value -> config file value -> default value.

**Comment by fauzanfebrian** [comment]
> my workaround, seem silly but it worked
> 
> ```go
> func Parse(i interface{}) error {
> 	r := reflect.TypeOf(i)
> 	for r.Kind() == reflect.Ptr {
> 		r = r.Elem()
> 	}
> 	for i := 0; i < r.NumField(); i++ {
> 		env := r.Field(i).Tag.Get("mapstructure")
> 		if err := viper.BindEnv(env); err != nil {
> 			return err
> 		}
> 	}
> 	return viper.Unmarshal(i)
> }
> ```

Thanks, this helped me alot
