### ISSUE TITLE
toml format doesn's work all right

### ISSUE THREAD

**Issue by ichsonx** [spf13/viper#595]
thx your project first.
then i use the toml example format like https://github.com/toml-lang/toml , i found the "hosts" can not read. if the format like " somename = ''content" " not top on the config file, viper cant read it or get nil

my simple code:
[main.txt](https://github.com/spf13/viper/files/2579919/main.txt)

my test toml file:
[ex.txt](https://github.com/spf13/viper/files/2579922/ex.txt)

**Comment by sagikazarmark** [comment]
This has nothing to do with Viper itself.

There is an open issue in the linked repository discussing the matter: https://github.com/toml-lang/toml/issues/565

Looks like that currently what you are asking for is not possible, at least not supported by the majority of toml parsers (which in this cases is `github.com/pelletier/go-toml`)

You might want to comment on the linked issue thread, or open an issue in the parser package, but in any cases, this is not Viper specific.

**Comment by ichsonx** [comment]
@sagikazarmark thanks for the response.
it is not the bug of Viper
