### ISSUE TITLE
Is this repository actively maintained?

### ISSUE THREAD

**Issue by bndw** [spf13/viper#626]
At a glance, it appears that issues dating back [roughly 1 year](https://github.com/spf13/viper/issues/472) haven't been acknowledged.

**Comment by sagikazarmark** [comment]
This project is quite mature, works well for most of the cases. I agree that maintenance could be better, but it's Open Source....

I have a few private forks fixing a few issues, I'm trying to contribute those back.

**Comment by bndw** [comment]
I was genuinely curious if this project was maintained, thanks for the response.
