### ISSUE TITLE
ETCD API V3 support

### ISSUE THREAD

**Issue by Reasno** [spf13/viper#630]
Hi, I wonder if viper support ETCD API V3? My test result is negative. Thanks.

**Comment by west3316** [comment]
need modify xordataexchange/crypt, i had a try

**Comment by ya0yy** [comment]
i got same result , but how solve, etcd api v3 support stopped : (

**Comment by liuqianhong6007** [comment]
I have the same trouble

**Comment by sagikazarmark** [comment]
Tracking it in #1155
