### ISSUE TITLE
use viper v1.3.1 and gin v1.3.1-0.20181126150151-b97ccf3a43d2 has unknown import path error

### ISSUE THREAD

**Issue by walnut-tom** [spf13/viper#633]
unknown import path "github.com/ugorji/go/codec": ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.1 (/Users/xxx/workspace/go/pkg/mod/github.com/ugorji/go@v1.1.1/codec)
        github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/Users/xxx/workspace/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)

**Comment by walnut-tom** [comment]
Possibility from 

> github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 

 to 

> github.com/ugorji/go v1.1.1

**Comment by sagikazarmark** [comment]
I'm not sure this is a Viper issue. After googling a bit I found this: https://github.com/golang/go/issues/29332#issuecomment-448669442

**Comment by amarox** [comment]
I have same problem. Etcd does't work correctly. 
`github.com/ugorji/go v1.1.1` solve this problem but viper uses `github.com/ugorji/go latest`

**Comment by heschik** [comment]
This triggers https://github.com/golang/go/issues/31766.

**Comment by kernle32dll** [comment]
Poking around a bit in https://github.com/ugorji/go, I would suspect that this should be fixed by [its latest release](https://github.com/ugorji/go/releases/tag/v1.1.4). So, time to update to 1.1.4 here?

I would argue that is better to use a v1+ version of a lib anyhow, instead of relying on a v0.0.0 commit.

**Comment by Tinyjimmy** [comment]
`github.com/ugorji/go` and `github.com/ugorji/go/codec` was two mod in the pass version. 

The author remove `github.com/ugorji/go/codec` , just keep `github.com/ugorji/go` in latest version. So a project use two module with `github.com/ugorji/go/codec` , it may ambiguous. Such like viper with gin, viper with etcd.

* Easy way

We can use local package replace online version as:

```mod
require (
	github.com/gin-gonic/gin v1.3.0
	github.com/spf13/viper v1.3.2
)

replace github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 => /Users/Jimmy/go/src/github.com/ugorji/go
```

* Best way

Online module change go.mod require , as  @walnut-tom said, use `github.com/ugorji/go` replace with `github.com/ugorji/go/codec`

**Comment by bvisness** [comment]
The following just worked for me:

```
replace github.com/ugorji/go/codec => github.com/ugorji/go v1.1.2
```

Why I couldn't use the `v1.1.4` (the latest) is beyond me. I got the following error when I attempted that:

```
go: github.com/ugorji/go@v1.1.4 used for two different module paths (github.com/ugorji/go and github.com/ugorji/go/codec)
```

**Comment by walnut-tom** [comment]
> The following just worked for me:
> 
> ```
> replace github.com/ugorji/go/codec => github.com/ugorji/go v1.1.2
> ```
> 
> Why I couldn't use the `v1.1.4` (the latest) is beyond me. I got the following error when I attempted that:
> 
> ```
> go: github.com/ugorji/go@v1.1.4 used for two different module paths (github.com/ugorji/go and github.com/ugorji/go/codec)
> ```

try remove "github.com/ugorji/go/codec"

**Comment by sagikazarmark** [comment]
This shouldn't be an issue anymore.

**Comment by hn-n** [comment]
got the same error after installing viper 
i reinstalled gin with "go get" and everything worked fine
