### ISSUE TITLE
panic: codecgen version mismatch: current: 8, need 10 when trying to use remote k/v store

### ISSUE THREAD

**Issue by reefbarman** [spf13/viper#644]
I get the below error when trying to add a remote provider, it only happens when I import the remote package. I am on go 1.11 and using go modules

panic: codecgen version mismatch: current: 8, need 10. Re-generate file: C:/Go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go

goroutine 1 [running]:
github.com/coreos/etcd/client.init.0()
        C:/Go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:45 +0x10b
exit status 2

**Comment by davidqhr** [comment]
rm the keys.generated.go file. It will be auto regenerated.

**Comment by dsxack** [comment]
But this doesn't seem to be a targeted solution.

**Comment by sagikazarmark** [comment]
This shouldn't be an issue anymore.
