### ISSUE TITLE
Persistent Flags not binding correctly 

### ISSUE THREAD

**Issue by colin-axner** [spf13/viper#646]
```
rootCmd.PersistentFlags().StringP(cli.HomeFlag, "", homeDir, "directory for plasmacli")
viper.BindPFlags(rootCmd.Flags())
```

In a subcommand when I call `viper.GetString(cli.HomeFlag)` nothing is returned. 
No errors from BindPFlags are returned.

 I have also tried `viper.BindPFlag(cli.HomeFlag, rootCmd.Flags().Lookup(cli.HomeFlag))`

Calling ` viper.Set(cli.HomeFlag, homeDir)` allows `viper.GetString(cli.HomeFlag)`  to return the correct value but then in command line when I call `--home` the specified value is not returned from the `viper.GetString(cli.HomeFlag)` call.

Currently on version 1.0.3

**Comment by sagikazarmark** [comment]
`viper.BindPFlags(rootCmd.Flags())`

This won't work, because you used `rootCmd.PersistentFlags()` and these are two different flag sets.

**Comment by colin-axner** [comment]
According to cobra documentation. `*Command.Flags()` returns the complete FlagSet. So wouldn't the above code be adding a persistent flag and bind all flags?

**Comment by sagikazarmark** [comment]
That will only be true once ParseFlags is called here: https://github.com/spf13/cobra/blob/7547e83b2d85fd1893c7d76916f67689d761fecb/command.go#L1462

Specifically this line: https://github.com/spf13/cobra/blob/7547e83b2d85fd1893c7d76916f67689d761fecb/command.go#L1471

But you are calling BindPFlags long before that.

**Comment by colin-axner** [comment]
Thanks! I think my issue was also related to a dependency using the same name for a flag and calling `Set()` on that flag.
