### ISSUE TITLE
Storing username / password in yaml issues

### ISSUE THREAD

**Issue by rmasci** [spf13/viper#650]
I want to have a simple config file that just stores the username / encrypted password into a config file.  The username for this application can be just a username, or username with email address.

For just the username I get the desired results:
Fred: U2FsdGVkZ16452duNsBbv+OEHe3gVKqd49U71BVKYvrD=

But when I have a user that is in the form of an email address  Fred@test.app.domain.com get this:
Fred@test:
  app:
     domain:
        com: U2FsdGVkD18N3fgV4n7+7Df2Y4Ps1UZPYLyM3EQP4KD= 

It works this way This isn't the way I want it stored.  I want it to look like this:
Fred@test.app.domain.com: <encrypted password>

I don't understand why this isn't doable.  Well I do understand why, v.keyDelim is set to "." and can't be changed.  So I edited the viper.go and added this function

```
// Set keyDelimeter to something other than "."
func SetKeyDelim(in string) {
	if in != "" {
		v.keyDelim = in
	}
}
```

If this is acceptable can I create a branch and do a pull request?

**Comment by StevenACoffman** [comment]
Hello! email addresses do contain dots, so you need to do it this way:

```
func initConfig() {
  // default delimiter is "." and emails contain these
  v := viper.NewWithOptions(viper.KeyDelimiter("::"))
  v.SetConfigType("json")

  if cfgFile != "" {
    // Use config file from the flag.
    v.SetConfigFile(cfgFile)
  } else {
    // Find home directory.
    home, err := homedir.Dir()
    if err != nil {
      fmt.Println(err)
      os.Exit(1)
    }

    // Search config in home directory with name ".jira-cli" (without extension).
    v.AddConfigPath(home+"/.config")
    v.SetConfigName("jira")
  }

  // If a config file is found, read it in.
  if err := v.ReadInConfig(); err == nil {
    fmt.Println("Using config file:", v.ConfigFileUsed())
  }
// ... more code here
}
```

**Comment by StevenACoffman** [comment]
I think you can close this issue.
