### ISSUE TITLE
xordataexchange is outdated

### ISSUE THREAD

**Issue by eclipseo** [spf13/viper#679]
xordataexchange is outdated and unmaintained, could you please find an alternative to it?

**Comment by at15** [comment]
+1 on this, also it is importing etcd and drags in a bunch of dependencies.

**Comment by jcmurray** [comment]
Fell over this one as well. xordataexchange supports only the V2 etcd API and not the V3 one. V2 data in etcd is not visible to V3 clients and vice versa. It results in a confusing and remote api in viper.

**Comment by sagikazarmark** [comment]
The library is already replaced with another one.
