### ISSUE TITLE
Application exits when marshallConfigReader encounters parsing errors

### ISSUE THREAD

**Issue by FZambia** [spf13/viper#68]
Hello!

When I send  SIGHUP signal to my already running server application - I want to reload configuration on the fly. But when updated configuration file has errors - wrong JSON format for example - my application exits as `marshallConfigReader` [calls](https://github.com/spf13/viper/blob/master/util.go#L134) `Fatalf`. I just want to log that configuration file contains errors that must be fixed before reloading.

`ReadInConfig` already [returns an error](https://github.com/spf13/viper/blob/master/viper.go#L702) – maybe it's better to return an error from `marshallConfigReader` too so my application code could decide what to do with error if it occurred?

**Comment by kzvezdarov** [comment]
Good call. I'll get a fix for that up.

**Comment by didenko** [comment]
This is a **BREAKING** change which introduces a **NEW BEHAVIOUR**. The code which relied on the process failure when a configuration fails to parse will now continue running. Instead the parse function returns an error.

To reintroduce the old behaviour analyse the returned error and use something like this after reading the configuration:

```go
	err := viper.ReadInConfig()

	switch et := err.(type) {
	case viper.ConfigParseError:
		jww.ERROR.Fatalf("Error parsing config: %s", err)
	default:
		fmt.Printf("Decide what to do about another error type: %T: %s\n", et, err)
	}
```
