### ISSUE TITLE
No way to read in config from io.Reader

### ISSUE THREAD

**Issue by natefinch** [spf13/viper#70]
I want to be able to give viper an io.Reader to read from, rather than having viper always read from a file... this makes it a lot easier for me to test - I can just hand viper a bytes.Buffer{} rather than having to write a config to disk during tests.  I could make a PR, but I noticed that there used to be a viper.MarshalReader which has since disappeared.... so I wanted to post this first to see if the PR is a good idea in general before doing the work.  I see there's already a (non-exported) marshalReader function, so hopefully it wouldn't require much to make something like that publicly visible in a nice way.

**Comment by spf13** [comment]
Does this do what you are looking to do? https://github.com/oliveagle/viper/commit/5736fabdfa955468b811e700f35d79cacdeb76b1

**Comment by natefinch** [comment]
Yes, that looks great.  I guess I missed the original ReadBufConfig method, but this is even better.

**Comment by spf13** [comment]
You didn't miss it. I merged it this morning and he's developed this at the same time as your request.
