### ISSUE TITLE
 Viper How to Read a Environment Array Variable

### ISSUE THREAD

**Issue by himansh-23** [spf13/viper#715]
how to read a array of values with single key in go lang

#Linux export a variable to environment
export key=(abc def sos ded)

how to read this in viper

**Comment by sagikazarmark** [comment]
You will have to write your own parsing logic.

You can:

- use `viper.GetString` and further parse the string value
- use `viper.UnmarshalKey` and do the same
- use decode hooks in [mapstructure](https://github.com/mitchellh/mapstructure)

Hope that helps

**Comment by himansh-23** [comment]
thank you @sagikazarmark it works
