### ISSUE TITLE
Remote config reader xordata/crypt is deprecated?

### ISSUE THREAD

**Issue by zarraozaga** [spf13/viper#716]
Etcd current uses port 2379 instead of 4001. Even though there is a workaround by setting a 
different endpoint, there is another issue with the encryption. 

GPG 2.1+ doesn't use secret keyring anymore. Is there a possible workaround? GnuPG 2.1 (and upwards) switched to a new keyring format with better performance. For newly generated keyrings, the keys are stored in the pubring.kbx file. Another change was merging public and private keyrings, that's why there is no additional secring.kbx.

So since xordata/crypt is deprecated is there any new library which viper supports for remote config read?

**Comment by chunshengster** [comment]
Yes，I found this issue too.
and now, I want to design a new protocol for viper and etcdv3, like this:
1. etcd's kvstore  may have mutil parent path for a key, like "/OneService/mysql/master/host" and "/OneService/mysql/slave/host" , I think it("mysql.master.host") should be stored in viper's map store like it read from yaml
2. in etcd we may also have big parent path for a group of keys(like "/OneService "), but, this should not be store in viper's map store
3. Watch should be set to both a key or a key prefix, like "/OneService/mysql/master", for "master/{host,port,user,pass,db}" these keys may be used to join together as DSN(database source name)
4. WatchRemote should trigger to update viper's map store automatically
5.each WatchRemote should trigger a callback function for application to update some data structure(like database connection).

that's all, thx.

**Comment by sagikazarmark** [comment]
Package is already replaced.

See #1155 for etcd v3 support.
