### ISSUE TITLE
tree bug？

### ISSUE THREAD

**Issue by lifegit** [spf13/viper#738]
README.md demo：
![image](https://user-images.githubusercontent.com/33006878/61626401-d0921680-acaf-11e9-8f9a-6acda556d173.png)

codeing：
![image](https://user-images.githubusercontent.com/33006878/61626492-ffa88800-acaf-11e9-89e6-2620f751cd71.png)
![image](https://user-images.githubusercontent.com/33006878/61626501-03d4a580-acb0-11e9-905b-09ee6c93d8be.png)

logs：
![image](https://user-images.githubusercontent.com/33006878/61626515-12bb5800-acb0-11e9-8b44-ed2699758259.png)

doubt：
Is it a problem with my code ?

**Comment by messias72** [comment]
Hi,

I have the same issue with a json config.

viper.AllKeys() list the key and if I do a viper.sub("keyfromAllKeys") a get a nil reference.
Has anyone a idea?

best regards
Torsten

**Comment by lifegit** [comment]
hi，
my problem is not the cause of viper，
my toml conf file err.

now:
[app]
    name = "binapp" 
    [app.tree]
         name = "22"
        [app.tree.test]
            addr = "127.0.0.1"

**Comment by messias72** [comment]
in my Case the
func ToStringMapE(i interface{}) (map[string]interface{}, error)
throw a error unable to cast []interface {}

best regards

**Comment by lifegit** [comment]
You can display your code?
