### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by shawnps-sigsci** [spf13/viper#744]
Hello, is there any way you could tag a new release? Seems there are quite a lot of changes in master:

https://github.com/spf13/viper/compare/b5bf975e5823809fb22c7644d008757f78a4259e..33bf76add3b746c1d275f0a5451b4d5750b2f2ff

Thank you very much for making this library!

**Comment by RiCoTeRoX** [comment]
@anthonyfok @spf13 @bep ... zzZZZ

**Comment by sagikazarmark** [comment]
Unfortunately there is a regression on the master branch at the moment, so releasing is temporarily blocked.

**Comment by sagikazarmark** [comment]
1.5.0 release is out for some time now.
