### ISSUE TITLE
codecgen version mismatch

### ISSUE THREAD

**Issue by afret0** [spf13/viper#746]
import _ "github.com/spf13/viper/remote"

get a panic 

panic: codecgen version mismatch: current: 8, need 10. Re-generate file: /Users/afreto/mine/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go

I tried other people's methods, but they didn't work here.

please help me

**Comment by sagikazarmark** [comment]
This shouldn't be an issue anymore.
