### ISSUE TITLE
Deeply nested (more than 2 level) config fails

### ISSUE THREAD

**Issue by jondot** [spf13/viper#75]
I have illustrated this with a failing test. But before I go ahead and submit a pull request - is this known?

**Comment by kzvezdarov** [comment]
Not known, must be a bug.

**Comment by jondot** [comment]
I think unit test has exactly 2 levels. This is an edge case - i think first searchMap iteration (hits at the second nesting level) succeeds, and the next iterations return map[interface{}]interface{} instead of map[string]interface{}.

See my failing test and fix:
https://github.com/spf13/viper/pull/76
