### ISSUE TITLE
About how viper use hcl and LICENSE 

### ISSUE THREAD

**Issue by qingguee** [spf13/viper#765]
Hello,
This is a question related with LICENSE.
Our software is using cobra and viper, so we'd like to know that have viper modify anything about hcl? 

On page below, hcl is using MPL. So, if I understand correctly, if viper modify hcl, then viper need be MPL.
https://github.com/hashicorp/hcl/blob/master/LICENSE

If viper only use hcl without any modify, then it's fine. 
I guess viper didn't, but could you help to confirm?

BRs,
Fan

**Comment by sagikazarmark** [comment]
@qingguee I can confirm that Viper does not contain a modified version of the hcl library. In fact, Viper does not ship with the hcl library, go will download that for you when you build a binary.
