### ISSUE TITLE
Recommend to split remote implements to multi repos

### ISSUE THREAD

**Issue by wyxloading** [spf13/viper#770]
Now package remote stick in the viper repo, leave us many dependencies.

How about spliting those remote implements to separate repos, like viper-consul, viper-etcd. Then we could choose what we actually need.  
Also contributors can write different remote implementations of their own, which should not fire as a mr to viper.

**Comment by sagikazarmark** [comment]
Eventually that would be nice, but for v1 we can't really remove those dependencies without breaking BC.

Since the package now uses go modules, we could make the remote package a separate module.

**Comment by wyxloading** [comment]
see #772
