### ISSUE TITLE
(CVSS 5.9) Vulnerability due to usage of golang.org/x:crypto:0.0.0-20181203042331-505ab145d0a9 worth looking into?

### ISSUE THREAD

**Issue by tsatke** [spf13/viper#777]
DepShield just showed me the vulnerability here: gojisvm/gojis#72

It would be nice if this, if possible, could get a fix in the next version, if you think this is worth fixing.
A dependency upgrade should do the trick.

**Comment by sagikazarmark** [comment]
I've looked into the issue and it seems to me that `golang.org/x/crypto` is an indirect dependency of Viper.

I think the solution is to update the package in your application:

```
go get golang.org/x/crypto
```

It should place the package in your `go.mod` with an `// indirect` directive.

**Comment by TimSatke** [comment]
It does, but it's being removed upon `go mod tidy`.

**Comment by sagikazarmark** [comment]
This should be fixed by now.
