### ISSUE TITLE
remove field 

### ISSUE THREAD

**Issue by jiftle** [spf13/viper#781]
remove field , what to do

**Comment by sagikazarmark** [comment]
Do you want to remove a key from Viper? I'm afraid there is no support for that at the moment. You could try `viper.Set` to a nil value.

**Comment by jiftle** [comment]
> Do you want to remove a key from Viper? I'm afraid there is no support for that at the moment. You could try `viper.Set` to a nil value.

yes ,I want to remove a key for Viper.  I try it `viper.Set  nil value`, but it is no work.

**Comment by sagikazarmark** [comment]
Anyway, this is a duplicate, please follow #632 and #290
