### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by miobook** [spf13/viper#787]
After running for a while ，System error, what is the problem?
----------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x57c5f9]

goroutine 20 [running]:
path/filepath.Ext(0x0, 0x1d, 0x1d, 0x0)
	/usr/local/go/src/path/filepath/path.go:218 +0x19
github.com/spf13/viper.(*Viper).getConfigType(0xc000240000, 0xc0001a6da0, 0x1d)
	/Users/xxx/src/github.com/spf13/viper/viper.go:1744 +0x5c
github.com/spf13/viper.(*Viper).ReadInConfig(0xc000240000, 0xce5355, 0x1)
	/Users/xxx/src/github.com/spf13/viper/viper.go:1170 +0xc7
github.com/spf13/viper.ReadInConfig(...)
	/Users/xxx/src/github.com/spf13/viper/viper.go:1162

**Comment by lukehinds** [comment]
Did you ever resolve this issue @miobook ?

**Comment by miobook** [comment]
yes

**Comment by miobook** [comment]
issue

**Comment by Virgil-N** [comment]
> yes

How did you solve this problem?

**Comment by sagikazarmark** [comment]
Please open a new issue with more details if this is still a problem.
