### ISSUE TITLE
Read unstructured data (JSON)

### ISSUE THREAD

**Issue by Merith-TK** [spf13/viper#788]
So right now i am making a program to launch another program, but with user specified env variables. such as follows
```json
{
    "launch": "./test.ext",
    "env": {
        "ConsoleZSettingsdir": "./",
        "testEnv": "Hello_World"
    }
}
```
`launch` will be the executable `os.Exec` will run
and i want `env` to have everything iside it, be set as a env.
AKA,
```
$ConsoleZSettingsdir=./
$testEnv=Hello_World
```
any ideas? and no, the `env.testEnv` thing won't work for me as that specifies a specific value,

**Comment by cyberbeast** [comment]
I am doing something similar in yaml, but in my case, reading the "env" properties is not a big deal.
```
type LaunchConfig struct {
    launch string
    env      map[string]string
}

var someStruct LaunchConfig
c := viper.Unmarshal(&someStruct)
for idx, val := range env {
    fmt.Println(val)
}
```

My issue is with being able to modify the individual values of the list and write it back to the config file.

**Comment by sagikazarmark** [comment]
I believe the readme comes without enough examples. If you still need help with this, please open a discussion with some sample code of what you are trying to do.
