### ISSUE TITLE
Use unmashal with embedded struct

### ISSUE THREAD

**Issue by PePoDev** [spf13/viper#797]
I try to use unmarshal to struct and It's work great.

And now, I want to unmarshal yaml file to embedded struct. See example.

main.go
```go
type Base struct {
    Foo string
}

type SomeStruct struct {
    Base
}

func ReturnToStruct(fileName string, dir string) SomeStruct {
    viper.SetConfigFile(fileName)
    viper.AddConfigPath(dir)
    if err := viper.ReadInConfig(); err != nil {
        xlog.Fatalf("fatal error config file: %s \n", err)
    }
    someStruct := SomeStruct{}
    if err := viper.Unmarshal(&someStruct); err != nil {
        xlog.Fatalf("%v", err)
    }

return someStruct
}
```

test.yml
```yml
Foo: asd
```

When I use

```go
    xlog.Infof("%s", someStruct.Foo)
```

It will return empty string.

Can I use viper with embedded struct ?

**Comment by sagikazarmark** [comment]
Viper actually uses [mapstructure](https://godoc.org/github.com/mitchellh/mapstructure).

Try `mapstructure:",squash"` struct tag on the embedded struct.

**Comment by PePoDev** [comment]
@sagikazarmark It work like a charm. Thanks you.

**Comment by ayanmw** [comment]
Why should I add a tag ?  Can Viper set this feature as default ? 
Default to support emebeded field is a good idea!!!!
