### ISSUE TITLE
downloading gopkg.in/yaml.v2 v2.2.4 failed

### ISSUE THREAD

**Issue by marcelloh** [spf13/viper#799]
gopkg.in/yaml.v2: git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ f221b8435cfb71e54062f6c6e99e9ade30b124d5 in /Users/marcelloh/go/pkg/mod/cache/vcs/748bced43cf7672b862fbc52430e98581510f4f2c34fb30c0064b7102a68ae2c: exit status 255:
        error: invalid object 100644 8dada3edaf50dbc082c9a125058f25def75e625a for 'LICENSE'
        error: cannot read 8dada3edaf50dbc082c9a125058f25def75e625a

Perhaps switch to a newer YAML version?

**Comment by sagikazarmark** [comment]
[2.2.4](https://github.com/go-yaml/yaml/releases/tag/v2.2.4) was released in october.

I can install it (with an empty go mod cache):

```
go: finding gopkg.in/yaml.v2 v2.2.4
go: downloading gopkg.in/yaml.v2 v2.2.4
go: extracting gopkg.in/yaml.v2 v2.2.4
```

Can you try cleaning your cache?

**Comment by marcelloh** [comment]
I did.
Dponwloaded the tagged 2.2.4 version as a zip, unzipped it at the same directory as the 2.2.5 was, with a name yaml.v2@v2.2.4, and now it works
