### ISSUE TITLE
add func: GetEnvPrefix() string

### ISSUE THREAD

**Issue by gbolo** [spf13/viper#802]
we have the `func SetEnvPrefix(in string)`, can we also add `func GetEnvPrefix() string`?

My use case for this is to find keys related to the application which viper cannot detect on it's own.
I don't mind creating the PR if needed.

**Comment by sagikazarmark** [comment]
Why not just use the prefix that you used for Viper? I don't really see Viper involved in this particular use case at all.

**Comment by gbolo** [comment]
> Why not just use the prefix that you used for Viper? I don't really see Viper involved in this particular use case at all.

because im trying to pick it up from another package ofcourse. If you feel that there is no valid use case here (despite me briefly describing one), then I suppose I should close this issue? I should point out that the effort to add this is very low. I will give it a few days, no traction and ill close.

**Comment by gbolo** [comment]
abandoning due to lack of interest...
