### ISSUE TITLE
How do I read an array of maps in toml

### ISSUE THREAD

**Issue by schmilwenspire** [spf13/viper#812]
Hi,

In my configuration file I have the following configuration
users = [
  {firstname="jhon", surname="smith"},
  {firstname="Anne", surname=Marry"}
]

What method should I use to read this configuration

Samuel

**Comment by Jensderond** [comment]
This should work
```golang
type User struct {
    Firstname, Surname string
}
var users []User

err = viper.UnmarshalKey("users", &users)
if err != nil {
    fmt.Printf("unable to decode into struct, %v", err)
    err = nil
}
```
https://github.com/spf13/viper#unmarshaling

**Comment by schmilwenspire** [comment]
thanks
