### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by vitalyisaev2** [spf13/viper#815]
Hi, I would like to use your library in a proprietary project, but it turns out that `viper` depends on https://github.com/hashicorp/hcl, which is licensed under MPL. In Go we have only static linking (with the exception to `Go plugins`), therefore, `viper` is infected and should be licensed under MPL as well. Another option is to completely drop support of `hcl` to get rid of infecting dependency.

**Comment by sagikazarmark** [comment]
Well, since the project itself does not contain any code from the hcl project I would argue it **has** to be licensed under MPL.

In the future different encoders might be in separate modules, so the main project wouldn't depend directly on them.

**Comment by vitalyisaev2** [comment]
@sagikazarmark thank you for the clarification. I thought that project that import other projects with MPL  should be licensed under MPL as well, but I might be wrong.
