### ISSUE TITLE
WriteConfig does not respect mapstructure declaration

### ISSUE THREAD

**Issue by Freshwood** [spf13/viper#816]
Hello guys,
Maybe I found a bug, but I'am not sure...
I just want to write a config with mapstructure annotations on it...
Struct:

    type Person struct {
        Age    int    `mapstructure:"a"`
        Gender string `mapstructure:"g"`
        Family string `mapstructure:"f"`
        Name   string `mapstructure:"n"`
    }

When you want to read this struct you should have "a", "g", "f", "n" field in your json file.
Unfortunately the write method does not respect the declaration inside mapstructure field.

The write method to write a config file:

```
import (
    "bytes"
    "github.com/spf13/viper"
    "gopkg.in/yaml.v2"
)


func WriteConfig(configInstance interface{}, filePath string,) error {

    v := viper.New()

    b, err := yaml.Marshal(&configInstance)

    if err != nil {
        return err
    }

    defaultConfig := bytes.NewReader(b)
    v.SetConfigType("yaml")

    if err := v.MergeConfig(defaultConfig); err != nil {
        return err
    }

    return v.WriteConfigAs(filePath)
}

```
The result for yaml or json is always:

json
```
{
  "age": 48,
  "family": "Family-Name",
  "gender": "m",
  "name": "Name"
}
```
yaml

```
age: 48
family: Family-Name
gender: m
name: Name
```

The mapstructure annotation are not respected..
Do I make something wrong here???

btw. I am using the latest version from viper v1.6.1

**Comment by sagikazarmark** [comment]
Unfortunately YAML and JSON libs are unaware of the `mapstructure` tag.

There are two ways to achieve what you are trying to do:

- Add `json` and `yaml` tags to your struct
- Marshal your struct to a `map[string]interface{}` first using mapstructure (which obviously respects its own struct tag) and marshal it to the desired format.

BTW it looks like you just want to write a structure to a file. Why do you need Viper for it? (Unless this is just some sort of sample code)

Closing as this is not related to Viper itself, but the lack of integration between encoding libraries.

**Comment by NefixEstrada** [comment]
For future reference, I've ended up doing the following:

```go
	cfg := &Cfg{
                Item: "content"
	}

	items := map[string]interface{}{}
	if err := mapstructure.Decode(cfg, &items); err != nil {
		return err
	}

	if err := viper.MergeConfigMap(items); err != nil {
		return err
	}

	return viper.WriteConfigAs("config.toml")
```
