### ISSUE TITLE
WriteConfig does not respect empty declarations

### ISSUE THREAD

**Issue by Freshwood** [spf13/viper#817]
Hello guys,
Maybe I found a bug, but I'am not sure...
During writing a struct with viper config I found out that all config options are written even when there are empty objects on it.
Struct:

```
	type EmptyType struct {
		Value string
	}
	type SomeType struct {
		Name  string    `json:"name"`
		Value string    `json:"value"`
		Empty EmptyType `json:"empty,omitempty"`
	}
	someType := SomeType{
		Name:  "Name",
		Value: "Value",
	}
```
Here is the write method to write the above struct to file system:

```
import (
    "bytes"
    "github.com/spf13/viper"
    "gopkg.in/yaml.v2"
)


func WriteConfig(configInstance interface{}, filePath string,) error {

    v := viper.New()

    b, err := yaml.Marshal(&configInstance)

    if err != nil {
        return err
    }

    defaultConfig := bytes.NewReader(b)
    v.SetConfigType("yaml")

    if err := v.MergeConfig(defaultConfig); err != nil {
        return err
    }

    return v.WriteConfigAs(filePath)
}

```

After write is done. The output is the following

Actual:
```
{
  "empty": {
    "value": ""
  },
  "name": "Name",
  "value": "Value"
}
```
Expected:

```
{
  "name": "Name",
  "value": "Value"
}

```
Empty fields are not respected..
Do I make something wrong here???

A sidenote:
```
	type SomeType struct {
		Name  string    `json:"name"`
		Value string    `json:"value"`
		Empty *EmptyType `json:"empty,omitempty"`
	}
```
I found out when I set the config to a pointer then the empty field not be written out with default values but can not be read with viper because it is a pointer oO

btw. I am using the latest version from viper v1.6.1

**Comment by sagikazarmark** [comment]
Well, you can easily try this for yourself: https://play.golang.org/p/vYNfg0mZ-LW

The problem is that a struct is never really empty, even if all of it's fields are set to the field type's default value.

A pointer to a struct on the other hand can be empty (nil). That's why it worked for you.

This isn't an issue with Viper, this is how Go works.
