### ISSUE TITLE
Want to use goccy/go-yaml instead of niemeyer's go-yaml

### ISSUE THREAD

**Issue by kyoh86** [spf13/viper#824]
Now https://github.com/goccy/go-yaml is better than neimeyer's go-yaml.

> As of this writing, there already exists a defacto standard library for YAML processing Go: https://github.com/go-yaml/yaml. However we feel that some features are lacking, namely:
> 
> - Pretty format for error notifacations
> - Directly manipulate the YAML abstract syntax tree
> - Support Anchor and Alias when marshaling
> - Allow referencing elements declared in another file via anchors

see also: [3 reasons to use github.com/goccy/go-yaml to handle YAML in Go | by Daisuke Maki | Medium](https://lestrrat.medium.com/3-reasons-to-use-github-com-goccy54-go-yaml-to-handle-yaml-in-go-5ccfd662191f)

**Comment by kyoh86** [comment]
that library is not stable

**Comment by kyoh86** [comment]
It's been stable.

**Comment by sagikazarmark** [comment]
Please see the new encoding layer introduced in #986 

Once it becomes stable, replacing the builtin yaml codec will be easy.
