### ISSUE TITLE
Flag type incompatible with FlagValue interface

### ISSUE THREAD

**Issue by mightymatth** [spf13/viper#825]
Consider this line documentation of this method:
https://github.com/spf13/viper/blob/eabbc68a3ecd5cf8c11a2f84dbda5e7a38493b2f/viper.go#L1002

Here `serverCmd.Flags().Lookup("port")` returns [Flag](https://github.com/spf13/pflag/blob/2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab/flag.go#L170-L183) type.

And `Viper.BindFlagValue()` accepts [FlagValue](https://github.com/spf13/viper/blob/eabbc68a3ecd5cf8c11a2f84dbda5e7a38493b2f/flags.go#L11-L18) interface.

The problem is that `Flag` type does not match `FlagValue` interface. 

One example is `Changed` method (defined on `Flag` type) which differs from `HasChanged` method (defined in `FlagValue` interface).

Versions:
`viper@v1.6.1`
`pflag@v1.0.5`

**Comment by sagikazarmark** [comment]
That's obviously a documentation bug, probably copy pasted from a few lines above the linked code:

https://github.com/spf13/viper/blob/eabbc68a3ecd5cf8c11a2f84dbda5e7a38493b2f/viper.go#L981

`FlagValue` is an interface defined by Viper. Viper also defines an unexported, `pflagValue` type that wraps `pflag.Flag` to make it compatible with the interface.

PRs are always welcome for these kind of bugs.

**Comment by mightymatth** [comment]
> That's obviously a documentation bug...

I don't get it because it seems like the bug in signature of this function:
https://github.com/spf13/viper/blob/eabbc68a3ecd5cf8c11a2f84dbda5e7a38493b2f/viper.go#L1004

If this function is meant to be used outside viper package, how it should be called?

I can see that it's used in tests and constructed with unexported `pflagValue`.

```go
func TestBindFlagValue(t *testing.T) {
	var testString = "testing"
	var testValue = newStringValue(testString, &testString)

	flag := &pflag.Flag{
		Name:    "testflag",
		Value:   testValue,
		Changed: false,
	}

	flagValue := pflagValue{flag}
	BindFlagValue("testvalue", flagValue)
	// ...
```

It should either be unexported function or the signature should have `flag *pflag.Flag`instead of `flag FlagValue` (and then casted with `pflagValue{flag}`). Or do I miss something?

**Comment by sagikazarmark** [comment]
`FlagValue` is an interface, so anything that implements it (custom flag package) can be used with Viper.

`pflag` is integrated directly into Viper, so there is no need to call `BindFlagValue`, you can use `BindPFlag` instead. You don't need to wrap `pflag.Flag` manually, Viper does that for you. It's a convenience feature.

If you take a look at the two functions, you will notice that their godoc is identical, only the function name is different. Chances are this is a copy-paste error.

**Comment by mightymatth** [comment]
> pflag is integrated directly into Viper, so there is no need to call BindFlagValue, you can use BindPFlag instead. You don't need to wrap pflag.Flag manually, Viper does that for you. It's a convenience feature.

Exactly what I wanted to point out. `BindPFlag` is the same like `BindFlagValue`, but `BindFlagValue` is hardly unusable from user of viper package. The only thing I'm concerned about is the reason why `BindFlagValue` is even exported. It confused me at first, even though I figure out to rather use `BindPFlag`.

I'm not ready to make a PR because I don't have high overview of viper, so I don't have any good decision to make. I'll leave it to someone who understands it.

**Comment by sagikazarmark** [comment]
`BindFlagValue` allows you to integrate a flag package into Viper (other than pflag). Viper supports pflag out of the box, but you can implement the `FlagValue` interface for your own flag package if you want.

Believe me, this is a copy-paste error in the documentation.

**Comment by mightymatth** [comment]
> ...but you can implement the FlagValue interface for your own flag package if you want.

Fine, that makes sense!

I would need to write something like this:

```go
type myFlagValue struct{ flag *pflag.Flag }

func (p myFlagValue) HasChanged() bool    { return p.flag.Changed }
func (p myFlagValue) Name() string        { return p.flag.Name }
func (p myFlagValue) ValueString() string { return p.flag.Value.String() }
func (p myFlagValue) ValueType() string   { return p.flag.Value.Type() }

func init() {
	viper.BindFlagValue("hello", myFlagValue{helloCmd.Flags().Lookup("hello")})
}
```

It's clear now, but I'm concerned what to do with the documentation. To write all this is terrible, avoiding to provide an example is bad, but providing non-working example is even worse. What's your opinion?

**Comment by sagikazarmark** [comment]
I'll come up with something.

Most people probably don't need to worry about this and can just use pflag integration.
