### ISSUE TITLE
Need help with parsing the config

### ISSUE THREAD

**Issue by fd98279** [spf13/viper#828]
Hello if the config is like below in JSON:
{
app:  [ {"max-items": 100, "item-size": 64},
           {"max-items": 100, "item-size": 64} ]
}

How to get the slice of apps?

I got something like this:
viper.AllSettings()["app"].([]interface{})[0]
Which prints:
map[item-size:[*] max-items:Test]

Is there a better way to get list of objects?

**Comment by sagikazarmark** [comment]
`viper.Get("app").([]interface{})[0]` is one way to do it.

```
var apps []interface{}

viper.UnmarshalKey("app", &apps)
```

is another.

**Comment by fd98279** [comment]
Thanks for the quick response.
