### ISSUE TITLE
Struct method BindPFlag calls package function SetDefault instead of method of the same name

### ISSUE THREAD

**Issue by leolara** [spf13/viper#83]
I think method `v.BindPFlag` should call `v.SetDefault` instead of just `SetDefault`

**Comment by leolara** [comment]
https://github.com/spf13/viper/blob/master/viper.go#L522

**Comment by didenko** [comment]
Nice find!

**Comment by leolara** [comment]
just happen to be reading the code and found it. I feel it is clear enough
in README.md how to use pflags with viper.

**Comment by didenko** [comment]
Fixed in SHA: 1241d2e04b9d3a9d345bf62dd3f60ca40c7dfa0a

**Comment by leolara** [comment]
:+1:

**Comment by didenko** [comment]
FYI, the fix is in my development, not the "official" `spf13/viper`, branch yet. If not merged in a week-two, will ask to reopen this issue.
