### ISSUE TITLE
Unmarshal returning empty struct

### ISSUE THREAD

**Issue by marcofranssen** [spf13/viper#832]
I'm facing the same issue as #740, but not with the root cause as the guys are describing in this ticket.

In this branch I upgraded Viper to the latest version available, so I could benefit from the Unmarshal functionality added in there.

In general after adding some defaults, Loading the config and overriding some values with Cobra cli values I want to unmarshal into a struct. This struct unfortunately ends up as an empty struct.

https://github.com/marcofranssen/notary/blob/feature/typed-config/cmd/notary/main.go#L79

These are the structs matching the Notary config.json

https://github.com/marcofranssen/notary/blob/feature/typed-config/client/config.go

I have also tried by specifiying my own TagName instead of leaning on the `mapstructure` Tag.

```go
config.Unmarshal(&notaryCfg, func(config *mapstructure.DecoderConfig) {
	config.TagName = "json"
})
```

Any clue why my struct ends up empty?

**Comment by sagikazarmark** [comment]
Chances are this won't work:

`viper.SetDefault("remote_server", client.RemoteServerConfig{URL: defaultServerURL})`

Viper uses a normalized internal state for unmarshaling config and won't be able to unmarshal the defaults to your struct. It would probably work if you didn't have any additional keys defined under `remote_server`.

So if you are supposed to see default values there, chances are you won't. Try setting the individual values.


I copied a part of your config and tried it locally: https://play.golang.org/p/aa2C1TXYYVp

It works (although for some reason it won't compile on play)

Try debugging your code. Without going deeper I have no idea what could cause your problem, sorry.

**Comment by sagikazarmark** [comment]
Looks like your test breaks because of what I mentioned above.

**Comment by marcofranssen** [comment]
🤦‍♂ that did the trick. So in general we should never set a map kind of structure default. This was already in the original codebase as a map. 

**Rule of thumb.**

> Always set the most specific nested keys on nested configuration structures when setting defaults.

**Comment by sagikazarmark** [comment]
Alternatively, you can set a `map[string]interface{}` as a default. That's how Viper internally stores values.

**Comment by marcofranssen** [comment]
@sagikazarmark that was originally in there and gave me same issues. I guess because of the set on these lines...

https://github.com/marcofranssen/notary/blob/feature/typed-config/cmd/notary/main.go#L156

**Comment by marcofranssen** [comment]
Correction. Originally it was `map[string]string`. That must have been the issue. Will update the previous comment with a full summary for documentation purposes or others facing similar in the future.

**Comment by gbolo** [comment]
> Chances are this won't work:
> 
> `viper.SetDefault("remote_server", client.RemoteServerConfig{URL: defaultServerURL})`
> 
> Viper uses a normalized internal state for unmarshaling config and won't be able to unmarshal the defaults to your struct. It would probably work if you didn't have any additional keys defined under `remote_server`.
> 
> So if you are supposed to see default values there, chances are you won't. Try setting the individual values.
> 
> I copied a part of your config and tried it locally: https://play.golang.org/p/aa2C1TXYYVp
> 
> It works (although for some reason it won't compile on play)
> 
> Try debugging your code. Without going deeper I have no idea what could cause your problem, sorry.

it probably fails due to the sheer amount of dependencies required when importing viper.

```
There are also limits on execution time and on CPU and memory usage.
```
