### ISSUE TITLE
consul token support

### ISSUE THREAD

**Issue by vpotap** [spf13/viper#841]
How can i add acl consul token to viper config ?  i have tried 
```
consulConfigKey := "default_config.json?token=secret"
err = viper.AddRemoteProvider("consul", consulAddr, consulConfigKey)
```
but param is escaped without result

**Comment by sabir012** [comment]
Hi team, any comments?  How I can use ACL token while requesting to consul?

**Comment by sagikazarmark** [comment]
Looking at the Consul API and the crypt package you can use environment variables to configure a token:

https://github.com/bketelsen/crypt/blob/5cbc8cc4026c0c1d3bf9c5d4e5a30398f99c99a9/vendor/github.com/hashicorp/consul/api/api.go#L358

Unfortunately, I don't see any other way at the moment and it would be quite hard to implement with the current crypt package.

**Comment by sabir012** [comment]
Hey @sagikazarmark , thanks for comment. Actually I have checked crypt and it uses 	`github.com/hashicorp/consul/api v1.1.0` which does not include consul API with token version. Is it possible to use the latest version of consul API?

**Comment by sagikazarmark** [comment]
go modules lets you upgrade to the latest v1 version in your application

**Comment by sabir012** [comment]
Thank you for comment. I wrote wrong library name. Crypt and Viper using "github.com/armon/consul-api" for consul API which does not include Token injection logic. Is there any way to force them to use a specific version of consul API? I want to send a token from environment variable as you suggested.

**Comment by sagikazarmark** [comment]
Just do `go get consulapiname@tag_you_want` in your project and you are good to go.

**Comment by cosmin-mogos** [comment]
Looks like release 1.6.3 does not contain the changes in this PR https://github.com/spf13/viper/commit/502400c0d97d71d9c21ad9171ac0a8b0a73126aa which updated crypt from `github.com/xordataexchange/crypt/config` to `github.com/bketelsen/crypt/config`.

The import in `remote.go` is still 
```
import (
	crypt "github.com/xordataexchange/crypt/config"
)
```

**Comment by cosmin-mogos** [comment]
@sagikazarmark when will the next viper version be released? Before that I guess there is no way to configure ACLs as 1.6.3 still uses the deprecated `xordataexchange` version of crypt.

**Comment by sagikazarmark** [comment]
You can always use the latest master (go mod will lock to the current latest commit)

**Comment by sagikazarmark** [comment]
Viper 1.7.0 has been released.
