### ISSUE TITLE
Viper cannot parse a string with asterisk

### ISSUE THREAD

**Issue by calazans10** [spf13/viper#843]
I tried to create a key with this string inside my config file and it didn't show the "*" character.

`cors_allowed_origins: "\u002A.example.com"`

It returns:

` .example.com`

**Comment by tacnoman** [comment]
Same problem here.

I tried with `*` and with unicode `\u002A`

If I try another char with unicode, works, but if i try with asterisk unicode the viper are replacing to space.

**Comment by calazans10** [comment]
After we did some research, we found out that the problem was with the lib we use to control the [cors](https://github.com/rs/cors/issues/88) config of the app.
