### ISSUE TITLE
Get config values from environment variables

### ISSUE THREAD

**Issue by r0l1** [spf13/viper#85]
It is common to use environment variables in container systems as docker to configure settings. It would be great if viper would handle this too:

`Defaults -> Environment Variables -> Settings Files -> Command Options`

**Comment by yesnault** [comment]
It's already possible, with https://github.com/spf13/cobra  / https://github.com/spf13/pflag and viper, something like that : 

```
viper.AutomaticEnv()
flags := rootCmd.Flags()
flags.StringVarP(&username, "username", "u", "", "username, facultative if you have config file")
viper.BindPFlag("username", flags.Lookup("username"))
```

**Comment by m4ng0squ4sh** [comment]
Perfect, thank you!

**Comment by rogierlommers** [comment]
Working fine, I like!

**Comment by four2five** [comment]
Does it make sense to close this issue if the indicated functionality is present (and therefore not an issue) ?

**Comment by scotthew1** [comment]
does anyone have a full working example of this env binding? i've seen @yesnault's snippit in a few different places, but i'm not actually getting the var i care about populated with the env. am i missing something here?

```golang
package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func main() {
	var thing1 string
	var thing2 string

	var cmd = &cobra.Command{
		Use:   "viper-test",
		Short: "testing viper",
		Run: func(command *cobra.Command, args []string) {
			fmt.Printf("thing1: %q\n", thing1)
			fmt.Printf("thing2: %q\n", thing2)
		},
	}

	viper.AutomaticEnv()
	flags := cmd.Flags()
	flags.StringVar(&thing1, "thing1", "", "The first thing")
	viper.BindPFlag("thing1", flags.Lookup("thing1"))
	flags.StringVar(&thing2, "thing2", "", "The second thing")
	viper.BindPFlag("thing2", flags.Lookup("thing2"))

	cmd.Execute()
}
```
```sh
$ export THING1=hello THING2=world

$ ./viper-test
thing1: ""
thing2: ""

$ ./viper-test --thing1 hello --thing2 world
thing1: "hello"
thing2: "world"
```

**Comment by yesnault** [comment]
@scotthew1 

```go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func main() {
	var cmd = &cobra.Command{
		Use:   "viper-test",
		Short: "testing viper",
		Run: func(command *cobra.Command, args []string) {
			fmt.Printf("thing1: %q\n", viper.GetString("thing1"))
			fmt.Printf("thing2: %q\n", viper.GetString("thing2"))
		},
	}

	viper.AutomaticEnv()
	flags := cmd.Flags()
	flags.String("thing1", "", "The first thing")
	viper.BindPFlag("thing1", flags.Lookup("thing1"))
	flags.String("thing2", "", "The second thing")
	viper.BindPFlag("thing2", flags.Lookup("thing2"))

	cmd.Execute()
}
```

**Comment by scotthew1** [comment]
@yesnault yeah i was able to get something like that working, but i was hoping viper would work with the `*Var()` flags.. your example from before uses `StringVarP()` and the [example from the cobra readme](https://github.com/spf13/cobra#bind-flags-with-config) shows the same. i was ultimately hoping to have a config struct that viper/pflags would populate that my code could use without having to cal `viper.Get()`. is this not possible as the examples imply?

**Comment by scotthew1** [comment]
ah... i just read past further past the example i linked...

> Note, that the variable author will not be set to the value from config, when the --author flag is not provided by user.

that makes for a pretty unfortunate example... any ideas for doing what i described in my previous comment? or am i misunderstanding viper's utility?

**Comment by danielmai** [comment]
Is there any updates on @scotthew1's question? Using the options like `StringVar` or `StringVarP` and having the config value be populated into the var would be ideal. There shouldn't be a need to call `Viper.Get()` in order to get the value from the CLI options, config file, environment variables, etc.

**Comment by McShauno** [comment]
I truly don't understand the usefulness of the viper integration if I still have to call Viper.get() instead of it automatically being bound to the variable.  Is there any movement on this?

**Comment by sagikazarmark** [comment]
You don't have to call `Get`. You can unmarshal values into a struct from Viper.

`*Var` will never work though, because pflag is integrated into Viper, not the other way around. pflag is used as a source, values never travel from viper to pflag and `*Var` is a pflag feature.

**Comment by lindenquan** [comment]
> @scotthew1
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/spf13/cobra"
> 	"github.com/spf13/viper"
> )
> 
> func main() {
> 	var cmd = &cobra.Command{
> 		Use:   "viper-test",
> 		Short: "testing viper",
> 		Run: func(command *cobra.Command, args []string) {
> 			fmt.Printf("thing1: %q\n", viper.GetString("thing1"))
> 			fmt.Printf("thing2: %q\n", viper.GetString("thing2"))
> 		},
> 	}
> 
> 	viper.AutomaticEnv()
> 	flags := cmd.Flags()
> 	flags.String("thing1", "", "The first thing")
> 	viper.BindPFlag("thing1", flags.Lookup("thing1"))
> 	flags.String("thing2", "", "The second thing")
> 	viper.BindPFlag("thing2", flags.Lookup("thing2"))
> 
> 	cmd.Execute()
> }
> ```



> does anyone have a full working example of this env binding? i've seen @yesnault's snippit in a few different places, but i'm not actually getting the var i care about populated with the env. am i missing something here?
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/spf13/cobra"
> 	"github.com/spf13/viper"
> )
> 
> func main() {
> 	var thing1 string
> 	var thing2 string
> 
> 	var cmd = &cobra.Command{
> 		Use:   "viper-test",
> 		Short: "testing viper",
> 		Run: func(command *cobra.Command, args []string) {
> 			fmt.Printf("thing1: %q\n", thing1)
> 			fmt.Printf("thing2: %q\n", thing2)
> 		},
> 	}
> 
> 	viper.AutomaticEnv()
> 	flags := cmd.Flags()
> 	flags.StringVar(&thing1, "thing1", "", "The first thing")
> 	viper.BindPFlag("thing1", flags.Lookup("thing1"))
> 	flags.StringVar(&thing2, "thing2", "", "The second thing")
> 	viper.BindPFlag("thing2", flags.Lookup("thing2"))
> 
> 	cmd.Execute()
> }
> ```
> 
> ```shell
> $ export THING1=hello THING2=world
> 
> $ ./viper-test
> thing1: ""
> thing2: ""
> 
> $ ./viper-test --thing1 hello --thing2 world
> thing1: "hello"
> thing2: "world"
> ```

It seems cobra default value will override viper's environment variables.  It is a known bug. Integration between Viper and Cobra has this issue.

**Comment by lindenquan** [comment]
```
viper.AutomaticEnv() 
var cmd = &cobra.Command{
	Use:   "",
	Short: "",
	PreRun: func(cmd *cobra.Command, args []string) {
		variable1 = viper.GetString("ENVIRONMENT_VARIABLE")
	},

```

**Comment by lindenquan** [comment]
This works for me.
```
package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func main() {
	var thing1 string
	var thing2 string

	var cmd = &cobra.Command{
		Use:   "viper-test",
		Short: "testing viper",
		PreRun: func(cmd *cobra.Command, args []string) {
			thing1 = viper.GetString("thing1")
			thing2 = viper.GetString("thing2")
		},
		Run: func(command *cobra.Command, args []string) {
			fmt.Printf("thing1: %q\n", thing1)
			fmt.Printf("thing2: %q\n", thing2)
		},
	}

	viper.AutomaticEnv()
	flags := cmd.Flags()
	flags.StringVar(&thing1, "thing1", "", "The first thing")
	flags.StringVar(&thing2, "thing2", "", "The second thing")
	viper.BindPFlag("thing1", flags.Lookup("thing1"))
	viper.BindPFlag("thing2", flags.Lookup("thing2"))

	cmd.Execute()
}
```
```
 ./viper-test --thing1 1 --thing2 2
thing1: "1"
thing2: "2"
```
```
export THING1=evn1
export THING2=env2
./viper-test 
thing1: "evn1"
thing2: "env2"
```
```
export THING1=evn1
export THING2=env2
./viper-test --thing1 1 --thing2 2
thing1: "1"
thing2: "2"
```

**Comment by sagikazarmark** [comment]
Closing as this feature is already implemented. Please open separate discussions.
