### ISSUE TITLE
Can we have a `func WriteConfig...(w io.Writer) error`?

### ISSUE THREAD

**Issue by dionysius** [spf13/viper#856]
I know we already have several WriteConfig functions. Especially we have [this one](https://github.com/spf13/viper/blob/97ee7adfef4882d78c0ef26e22a0c8a7a8bf6776/viper.go#L1399
) writing the config file to a specific location. But wouldn't it be anyway more flexible if the argument was a io.Writer? The user would have more control about the permissions and settings of that io.File then. Anyway...

My use case is to provide the caller a `program config show <format>` command to present him the current config in his wished format. My current attempt is `WriteConfigAs` into a temporary file and reading that again, but this is uglyish...

**Comment by sam6258** [comment]
Easier solution if you know your output format:

```
	b, err := yaml.Marshal(viper.AllSettings())
	if err != nil {
		return err
	}
	fmt.Println(string(b))
```

Can take a look at https://github.com/spf13/viper/tree/master/internal/encoding to see how each one is internally marshalled.

**Comment by sam6258** [comment]
It would be nice if the encoding library could just be moved out of `internal` though.

**Comment by sagikazarmark** [comment]
What do you think about the function added in https://github.com/spf13/viper/pull/1885 ?

**Comment by sam6258** [comment]
That works for my use case! I want to have a way to dump config on load/reload in logs easily

**Comment by dionysius** [comment]
I like it as well, I can write it to os.Stdout this way
