### ISSUE TITLE
remove usage of deprecated package `github.com/coreos/go-etcd`

### ISSUE THREAD

**Issue by asilverman** [spf13/viper#865]
Currently viper is depending on a package that is deprecated, this issue is to request viper to upgrade its dependencies so it uses the maintained package found here `https://github.com/etcd-io/etcd/tree/master/client`

**Comment by sagikazarmark** [comment]
etcd is a transitive dependency, used by this package: https://github.com/bketelsen/crypt

Related bketelsen/crypt#6

**Comment by breml** [comment]
@sagikazarmark the issue in https://github.com/bketelsen/crypt/issues/6 is fixed. I would really appreciate, if viper could be updated.

**Comment by breml** [comment]
Related: #956 and #957

**Comment by sagikazarmark** [comment]
The above PR will eventually solve this issue. It's currently blocked on etcd-io/etcd#12498 and etcd-io/etcd#12498
