### ISSUE TITLE
Is it possible to bind a global(persistent) flag with subCmd config?

### ISSUE THREAD

**Issue by edieYoung** [spf13/viper#872]
I have a root cmd which defines a persistent flag `context`, and I also have a sub cmd using a config file with a field `args.context`, I want to bind this persistent flag with the config file in sub cmd like this:
 `viper.BindPFlag("args.context", rootCmd.Flags().Lookup("context"))`

Is this possible? 
From my observation, it didn't handle the override(flag overrides config) properly like other local flags.

**Comment by sagikazarmark** [comment]
I think this should possibly be a Cobra question, not a Viper one.
