### ISSUE TITLE
Is it possible to add support for AWS System Manager parameter store?

### ISSUE THREAD

**Issue by praveentiru** [spf13/viper#877]
After reading the code in remote, my understanding is that support for remote parameter stores and watch is kind of coded into the library and additional systems cannot be added on need basis.

I am working with apps on AWS and we use AWS SSM to manage our configuration. Is my understanding incorrect? Can I add support for AWS SSM on my own?

**Comment by sagikazarmark** [comment]
Here is an example how you can do that:

https://github.com/sagikazarmark/viperx

In Viper 2 adding configuration sources should become much easier.

**Comment by praveentiru** [comment]
@sagikazarmark Is there some place where Viper 2 goals are laid out. I would love to contribute where I can.

**Comment by sagikazarmark** [comment]
I've started an issue to track it #772, but it's basically still in the planning phase.
