### ISSUE TITLE
question to set proper env

### ISSUE THREAD

**Issue by skygragon** [spf13/viper#878]
let's say I have a expected config layout:
```
[aaa.bbb]
ccc = 123
```
how to set proper env here to make viper.GetString("aaa.bbb.ccc")? Have tried AAA_BBB_CCC but not work

**Comment by sagikazarmark** [comment]
https://github.com/spf13/viper#working-with-environment-variables

> SetEnvKeyReplacer allows you to use a strings.Replacer object to rewrite Env keys to an extent. This is useful if you want to use - or something in your Get() calls, but want your environmental variables to use _ delimiters. An example of using it can be found in viper_test.go.
