### ISSUE TITLE
github.com/spf13/viper/remote error:

### ISSUE THREAD

**Issue by feiquan123** [spf13/viper#883]
go.mod 
github.com/spf13/viper v1.6.2

when import `_ "github.com/spf13/viper/remote"` then `go run ` , error:

# github.com/coreos/etcd/client
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:63:14: z.HasExtensions undefined (type codec.genHelperEncoder has no field or method HasExtensions)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:63:35: z.EncExt undefined (type codec.genHelperEncoder has no field or method EncExt)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:75:6: r.WriteArrayElem undefined (type codec.genHelperEncDriver has no field or method WriteArrayElem)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:83:6: r.WriteMapElemKey undefined (type codec.genHelperEncDriver has no field or method WriteMapElemKey)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:84:19: too many arguments in call to r.encDriver.EncodeString
        have (number, string)
        want (string)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:85:6: r.WriteMapElemValue undefined (type codec.genHelperEncDriver has no field or method WriteMapElemValue)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:94:6: r.WriteArrayElem undefined (type codec.genHelperEncDriver has no field or method WriteArrayElem)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:99:20: too many arguments in call to r.encDriver.EncodeString
        have (number, string)
        want (string)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:102:6: r.WriteMapElemKey undefined (type codec.genHelperEncDriver has no field or method WriteMapElemKey)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:103:19: too many arguments in call to r.encDriver.EncodeString
        have (number, string)
        want (string)
../../../pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:103:19: too many errors

**Comment by sagikazarmark** [comment]
Fixed in https://github.com/spf13/viper/releases/tag/v1.6.3

Please try it! Thanks!

**Comment by feiquan123** [comment]
fine, it working :smile_cat:
