### ISSUE TITLE
How to get the currently used config path?

### ISSUE THREAD

**Issue by gregf** [spf13/viper#89]
Is there a way to get the config path that viper has decided to go with? For example if I set

```
viper.AddConfgPath("/etc/somename")
viper.AddConfigPath("$HOME/.config/somename")
```

Viper decides to read the config file from etc how can I retrieve that path later on?

**Comment by didenko** [comment]
https://github.com/spf13/viper/blob/db7ff930a189b98d602179d9001d33345f42b8c7/viper.go#L253 should do
