### ISSUE TITLE
Optionally strip comments in JSON

### ISSUE THREAD

**Issue by mmindenhall** [spf13/viper#90]
I'm working on my first Go project.  Our configuration is part configuration files (generated and maintained by humans), and part generated by code on the server and retrieved by clients.  For the human part, I'd favor YAML or TOML (or HOCON which I use in the JVM world), but generating the config in code is much easier in JSON, and we would prefer to use the same format for both.

It would make things much easier if viper supported an option for stripping comments in JSON configuration files.  Douglas Crockford actually [suggests this approach](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr):

> Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser.﻿

Thanks!

**Comment by spf13** [comment]
What comment format would we use?

Is there a library in go that already does this?

**Comment by mmindenhall** [comment]
Weird...I thought I replied to this already...I guess I typed the comment and never submitted it last week.

The comment formats handled should be the same supported by JavaScript -- i.e.:
```
// line comments 

/* and 
   block 
   comments 
 */
```

There are a couple of existing libraries that I've found:
https://github.com/DisposaBoy/JsonConfigReader
https://github.com/hnakamur/jsonpreprocess

**Comment by mmindenhall** [comment]
Another interesting option here would be to just support [JSON5](http://json5.org/).  It's a superset of JSON, so existing config files would still parse correctly.  There's a golang implementation here:  
[https://github.com/yosuke-furukawa/json5](https://github.com/yosuke-furukawa/json5)

**Comment by yawn** [comment]
Just use YML. JSON is valid [YML 12](http://www.yaml.org/spec/1.2/spec.html).

**Comment by tomdavidson** [comment]
A solid json minifier to strip comments prior to loading as suggested but Crockford in the op doesnt exist in go? https://github.com/getify/JSON.minify has many languages ... but not go...

I prefer a minifier as suggested by @mmindenhall rather than JSON5

**Comment by moorereason** [comment]
Frankly, I would close this request since JSON doesn't support comments.  End of discussion.  If you don't like that, lobby the JSON community to change the standard.

However, if you want JSON+comments, use [HCL](https://github.com/hashicorp/hcl), which Viper already supports.  HCL has comments and supports full JSON syntax (plus non-JSON features, but I would avoid those features to simplify interop).

**Comment by awishformore** [comment]
I concur, in my view, viper should handle the standards as specified.
