### ISSUE TITLE
Doest not unmarshall if the model is not title case

### ISSUE THREAD

**Issue by sushruthajirnis** [spf13/viper#902]
What works
yaml
```
policyConfig:
  - apiEndpoint: "postsvce.a.signals.com"
```
unmarshalls into 
```
type ProfilePolicy struct {
	PolicyConfig []struct {
		ApiEndpoint string `mapstructure:"apiEndpoint"`
	} `mapstructure:"policyConfig"`
}
```
but does not unmarshall into
```
type ProfilePolicy struct {
	PolicyConfig []struct {
		apiEndpoint string `mapstructure:"apiEndpoint"`
	} `mapstructure:"policyConfig"`
}
```
My steps
```
	viper.SetConfigName("<yaml_location>")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(".")
	if err := viper.ReadInConfig(); err != nil {
		log.Fatalf("Error reading config file, %s", err)
	}
	err := viper.Unmarshal(&policymap)
	if err != nil {
		log.Fatalf("unable to decode into struct, %v", err)
	}
}
```
will the unmarshalling class always need to have the title case
difference being
_apiEndpoint string_ vs  _ApiEndpoint string_

**Comment by sagikazarmark** [comment]
In Go, a field (or any type) being started with an uppercase character controls whether it's _exported_ or not. Unexported fields are unavailable for anything outside your package, so marshaling/unmarshaling requires fields to be exported.

This isn't unique to Viper, every encoding library (even the ones in the standard library) works that way.
