### ISSUE TITLE
Could viper support merge two config files?

### ISSUE THREAD

**Issue by ahuigo** [spf13/viper#938]
I have serval env config file:
```
config/
    default.yaml
    conf_dev.yaml
    conf_test.yaml
    conf_production.yaml
```
Could viper support merge two config files(e.g.  `    default.yaml`+`conf_dev.yaml`  )

**Comment by sagikazarmark** [comment]
Currently Viper only supports a single file source. If/when #889 gets implemented, this should be possible. Closing as the linked issue covers this use case and we can track it there.

**Comment by ahuigo** [comment]
A demo to merge multiple yaml files via viper:
https://tonybai.com/2022/09/20/use-viper-to-do-merge-of-yml-configuration-files/
