### ISSUE TITLE
Upgrade gopkg.in/yaml/v2 to v3

### ISSUE THREAD

**Issue by andig** [spf13/viper#942]
According to https://github.com/go-yaml/yaml/tree/v3, the v3 version has suport for yaml 1.2:

> The yaml package supports most of YAML 1.2, but preserves some behavior from 1.1 for backwards compatibility.
> Specifically, as of v3 of the yaml package:
> YAML 1.1 bools (yes/no, on/off) are supported as long as they are being decoded into a typed bool value. Otherwise they behave as a string. Booleans in YAML 1.2 are true/false only.

As viper decodes into `map[string]interface{}`, moving from v2 to v3 would eliminate some ugly surprises like when decoding `value: off`:
- v2: `map[value:false]`
- v3: `map[value:off]`

It's probably too big a change but would fit with #772. Alternatively, passing your own pluggable decoders into viper could be another option.

**Comment by sagikazarmark** [comment]
Thanks! I added it to the Viper 2 project.

**Comment by martinrode** [comment]
This issue is biting me just now. Reading a .yml config results in a 

```
map[interface {}]interface {}
```

This cannot be encoded into JSON by the STDLIB:

```
executing "tmpl" at <marshal $email>: error calling marshal: json: unsupported type: map[interface {}]interface {}
```

In our App it was simply a matter of simply replacing v2 with v3, everything kept working, except that the map[string]interface decodes more JSON friendly.

**So may be this can be a simple enhancement in Viper v1?**

**Comment by sagikazarmark** [comment]
It feels like a breaking change though, so I'd suggest replacing it locally if you need it.

**Comment by andig** [comment]
@martinrode you might be able to work around this by typing your target config that viper unmarshals into.

**Comment by sagikazarmark** [comment]
In the next release yaml 3 will be available by passing the `viper_yaml3` tag to the go build command.

**Comment by andig** [comment]
@sagikazarmark is this something I could already use now? It keeps hitting my users time and again and seems almost impossible to work around inside mapstructure.

**Comment by sagikazarmark** [comment]
@andig see the latest release.

**Comment by sagikazarmark** [comment]
Experimental support coming in v1.11.0
