### ISSUE TITLE
viper@1.7.1 is not support toml-v1.0.0-rc.1

### ISSUE THREAD

**Issue by nicoxb** [spf13/viper#959]
viper@v1.7.1 depends "github.com/mitchellh/mapstructure@v1.1.2" is not support toml@v1.0.0-rc.1.
The latest version  of "github.com/mitchellh/mapstructure" is support toml@v1.0.0-rc.1 now.

**Comment by sagikazarmark** [comment]
I'm not sure how mapstructure is related to toml and which toml package has a `v1.0.0-rc.1` version, but the linked PR updates mapstructure to the latest version.
