### ISSUE TITLE
Hello,how can i use viper if my config file dose't exist auto create config file and use  config value by default.  else use config by config file? thanks 

### ISSUE THREAD

**Issue by olongfen** [spf13/viper#973]

**Comment by kingmorning** [comment]
maybe you can use viper.setDefault to set default value.

**Comment by olongfen** [comment]
i tried before, but i rebuild code my config file overridden by default

**Comment by sagikazarmark** [comment]
Can you share some code and config samples please? Sounds like your config file is not loaded at all or is in a different structure.

Viper cannot create a default config file for you, but can set defaults.

**Comment by olongfen** [comment]
# 1. init and auto created config file use value by default
```golang
package main

import (
	"fmt"
	"log"

	"github.com/spf13/viper"
)

type conf struct {
	User user
}

type user struct {
	Name string `json:"name"`
	Age  string `json:"age"`
}

func main() {
	viper.SetConfigFile("demo.yaml")
	viper.SetDefault("user", user{
		Name: "Tom",
		Age:  "29",
	})
	c := &conf{}
	viper.WriteConfig()
	viper.ReadInConfig()
	if err := viper.Unmarshal(c); err != nil {
		log.Fatal(err)
	}
	fmt.Println(viper.Get("user"))
	fmt.Println(c)
}

```
output: 
   map[age:29 name:Tom]
   &{{Tom 29}}


# 2. Now there is a configuration file, i modify age=30, name=Jack in config file, and run again.
   output: 
      map[age:30 name:Jack]
     &{{Jack 30}}
so here output value by config file and not by defalut

**Comment by sagikazarmark** [comment]
There are several issues with your example:

- Viper doesn't support `json` tags, you should use `mapstructure` instead
- Viper doesn't support setting structs as defaults. You should set the individual keys (see the example below).
- Calling WriteConfig before reading anything will overwrite your file with the defaults

Here is the fixed version that works for me:

```
package main

import (
	"fmt"
	"log"

	"github.com/spf13/viper"
)

type conf struct {
	User user
}

type user struct {
	Name string `mapstructure:"name"`
	Age  string `mapstructure:"age"`
}

func main() {
	viper.SetConfigFile("demo.yaml")
	viper.SetDefault("user.name", "Tom")
	viper.SetDefault("user.age", "29")
	c := &conf{}
	viper.ReadInConfig()
	if err := viper.Unmarshal(c); err != nil {
		log.Fatal(err)
	}
	fmt.Println(viper.Get("user"))
	fmt.Println(c)
}
```
