### ISSUE TITLE
How can i list the key from a yaml?

### ISSUE THREAD

**Issue by linker0512** [spf13/viper#975]
Hello, i have a yaml file and its structure is as follows:

Test:
&ensp;&ensp;&ensp;&ensp;A: value a
&ensp;&ensp;&ensp;&ensp;B: value b
&ensp;&ensp;&ensp;&ensp;..................

and how can i get the key (A,B...) without knowing that exist? I used viper.Sub() and get the map(Viper.config).
However, Viper.config is a private type that cannot be accessed externally. Is there any other ways to get the keys from yaml file?

**Comment by sagikazarmark** [comment]
Try https://pkg.go.dev/github.com/spf13/viper@v1.7.1?tab=doc#AllKeys

**Comment by linker0512** [comment]
@sagikazarmark Thank you! AllKeys worked for my job
