### ISSUE TITLE
expected type 'bool', got unconvertible type 'map[string]interface {}'

### ISSUE THREAD

**Issue by siddjain** [spf13/viper#977]
I am trying to parse a struct that has a map[string]bool inside it. E.g.,

```
type SigningProfile struct {
	ExtensionWhitelist          map[string]bool
}
```

My yaml looks like

```
ExtensionWhitelist:
                1.2.3.4.5.6.7.8.1: true
```

When i try to unmarhsall this with viper I get this error:

```
expected type 'bool', got unconvertible type 'map[string]interface {}'
```

If I change the yaml to:

```
ExtensionWhitelist:
                1.2.3.4.5.6.7.8.1: 
```

there is no error but the map is nil. Can somebody help?

EDIT: The problem here is that my key has . characters in it and that is confusing viper. How can I tell it that the entire 1.2.3.4.5.6.7.8.1 is a string?

**Comment by siddjain** [comment]
The solution is to use

```
v := viper.NewWithOptions(viper.KeyDelimiter("::"))
```

refer: https://github.com/spf13/viper/pull/794/files

If you want to unmarshal configuration where the keys themselves contain dot (the default key delimiter), you have to change the delimiter

**Comment by sagikazarmark** [comment]
Indeed, that seems to be the solution.
