### ISSUE TITLE
TypeAssertion to be mentioned in the example

### ISSUE THREAD

**Issue by thatsarunb4u** [spf13/viper#981]
If I simply follow the readme to get configuration value from an yaml file, I would get the following error.

`(type interface {}) as type string in assignment: need type assertion
`

For the below code, if I assign using := and then use the variable later somewhere down, I'd get Type assertion error also.

```
var esHost,esUser string

esHost = viper.Get("es.host")
esUser = viper.Get("es.user")
```

**Comment by sagikazarmark** [comment]
You can use `viper.GetString("es.host")` to return the values as string: https://github.com/spf13/viper#getting-values-from-viper

I checked the readme for errors, but I can't find any code that would require type assertions.
