### ISSUE TITLE
viper.Sub may return nil and may encounter an invalid memory address error.

### ISSUE THREAD

**Issue by j2gg0s** [spf13/viper#987]
``viper.Sub("foo").Get("A")`` may encounter an invalid memory address error.
Should we let viper.Sub return with viper.New when not sub tree exists?

**Comment by sagikazarmark** [comment]
I'm afraid it would cause more confusion, since it would implicitly fall back to an empty instance, there would be no way to detect if there way an issue.

I think adding guards around `Sub` calls (ie. check if it's nil) is a better solution.

**Comment by j2gg0s** [comment]
> I'm afraid it would cause more confusion, since it would implicitly fall back to an empty instance, there would be no way to detect if there was an issue.

I agree with this.

Open this issue for other people who encountered this problem to find answer quickly.

Should we add tips in README?  Such as https://github.com/spf13/viper/pull/988
