### ISSUE TITLE
GetStringSlice and Unmarshal use different field separators

### ISSUE THREAD

**Issue by j2gg0s** [spf13/viper#990]
Thanks for the convenience broghut by viper.

Please notice that,
When use viper.GetStringSlice, we call ``strings.Field`` to split string and use asciiSpace as sep.
``var asciiSpace = [256]uint8{'\t': 1, '\n': 1, '\v': 1, '\f': 1, '\r': 1, ' ': 1}``

When use viper.Unmarshal with default config, we call ``strings.Splitt`` and use ``,`` as sep. 

Are these inconsistencies caused by us unintentionally?
Should we avoid these in viper2?

**Comment by sagikazarmark** [comment]
Hey @j2gg0s 

I honestly don't understand what you mean. Where are `strings.Field` and `strings.Split` called?

**Comment by j2gg0s** [comment]
Ignore my bad english, plz.

One Example:
```
package main

import (
	"testing"

	"github.com/spf13/viper"
	"github.com/stretchr/testify/require"
)

func TestViper(t *testing.T) {
	viper.Reset()
	viper.SetDefault("A", "B C D")
	viper.SetDefault("X", "Y,Z")
	require.ElementsMatch(t, []string{"B", "C", "D"}, viper.GetStringSlice("A"))
	require.Equal(t, []string{"Y,Z"}, viper.GetStringSlice("X"))

	viper.Reset()
	viper.SetDefault("A", "B C D")
	viper.SetDefault("X", "Y,Z")

	c := struct {
		A []string
		X []string
	}{}

	err := viper.Unmarshal(&c)
	require.NoError(t, err)
	require.Equal(t, []string{"B C D"}, c.A, viper.AllSettings())
	require.ElementsMatch(t, []string{"Y", "Z"}, c.X)
}
```

viper.GetStringSlice use space as string sep, because it call ``strings.Field``.
viper.Unmarshal use ``,`` as string sep, because it call ``strings.Split`` with ``,``.

It is ok? Will we change this in furture?

**Comment by sagikazarmark** [comment]
Oh, I see now. Well, those two are working totally differently and are usually not used in the same context, so the inconsistency itself shouldn't be an issue, unless you are using one of them and want the behavior of the other.

I'd say this is one of the weird edge cases that probably doesn't worth fixing, but I'd accept PRs (provided they are not rough patches, but actual fixes. my gut tells me that you would have to send PRs to at least github.com/spf13/cast)

**Comment by j2gg0s** [comment]
``I'd say this is one of the weird edge cases that probably doesn't worth fixing``

Agree, and we can change ``viper.Unmarshal``'s rule by option arguments, like this
```golang
	err := viper.Unmarshal(c, func(config *mapstructure.DecoderConfig) {
		config.DecodeHook = mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			func(f reflect.Kind, t reflect.Kind, data interface{}) (interface{}, error) {
				if f != reflect.String || t != reflect.Slice {
					return data, nil
				}

				raw := data.(string)
				if raw == "" {
					return []string{}, nil
				}

				return strings.Fields(raw), nil
			},
		)
	})
```
