### ISSUE TITLE
Same config name, different formats (YAML & properties) => reads from YAML

### ISSUE THREAD

**Issue by DevDevious** [spf13/viper#999]
Hello,

2 config files in the same folder: **config.properties** and **config.yaml**. Setting-up **viper** thus:

```
config.SetConfigName("config")
config.SetConfigType("properties")
config.AddConfigPath(".")
```

Viper reads from **config.yaml** instead of **config.properties**.

**Comment by sagikazarmark** [comment]
Use [SetConfigFile](https://pkg.go.dev/github.com/spf13/viper@v1.7.1#SetConfigFile) if you want to use a specific file.
